# GENERATED by `npx ray gen` from implementation/physics.ray - do not edit
Gem::Specification.new do |s|
  s.name = "orbitmines-physics"
  s.version = "0.0.1"
  s.summary = "The discrete theory G - the rules, and the smallest thing that runs them. Generated from implementation/physics.ray."
  s.authors = ["OrbitMines"]
  s.homepage = "https://github.com/orbitmines/physics"
  s.required_ruby_version = ">= 3.1"
  s.files = Dir["lib/**/*", "README.md"]
  s.require_paths = ["lib"]
end
