// GENERATED by `npx ray gen` from implementation/physics.ray - do not edit
// one part of the physics core and the theories, emitted from implementation/physics.ray: every class is registered here and made when the package is first used
#include "orbitmines/physics/rt.hpp"

#if defined(__GNUC__)
#pragma GCC diagnostic ignored "-Wunused-parameter"
#pragma GCC diagnostic ignored "-Wunused-variable"
#endif

namespace orbitmines::physics {

static void C_Aggregate(Cls& c) {
  c.field("theory", nullptr);
  c.staticField("CACHE", [](const Value& self) -> Value { return make(S<"Node">(), { }); });
  c.staticField("ROUNDS", [](const Value& self) -> Value { return 4.0; });
  c.staticField("FOLDS_NAMES", [](const Value& self) -> Value { return list({ "\\rho", "n_{f}" }); });
  c.field("D", [](const Value& self) -> Value { return 2.0; });
  c.field("DEG", [](const Value& self) -> Value { return 8.0; });
  c.statik("of", [](Value self, const Args& a1) -> Value {
    auto theory_0 = cell(arg(a1, 0)); auto DEG_0 = cell(arg(a1, 1)); auto D_0 = cell(arg(a1, 2));
    if (truthy(eq(DEG_0->v, null))) {
      DEG_0->v = null;
    }
    if (truthy(eq(D_0->v, null))) {
      D_0->v = null;
    }
    auto deg_0 = cell(); deg_0->v = orElse(DEG_0->v, [&]() -> Value { return get(get(theory_0->v, S<"lattice">()), S<"DEG">()); });
    auto dim_0 = cell(); dim_0->v = orElse(D_0->v, [&]() -> Value { return get(get(theory_0->v, S<"lattice">()), S<"D">()); });
    auto key_0 = cell(); key_0->v = "" + str(get(theory_0->v, S<"name">())) + "/" + str(dim_0->v) + "/" + str(deg_0->v) + "";
    if (truthy(eq(elem(get(K(S<"Aggregate">()), S<"CACHE">()), key_0->v), null))) {
      setAt(get(K(S<"Aggregate">()), S<"CACHE">()), key_0->v, make(S<"Aggregate">(), { kw(S<"theory">(), theory_0->v), kw(S<"DEG">(), deg_0->v), kw(S<"D">(), dim_0->v) }));
    }
    return elem(get(K(S<"Aggregate">()), S<"CACHE">()), key_0->v);
    return null;
  });
  c.field("prover", [](const Value& self) -> Value { return make(S<"Prover">(), { kw(S<"theory">(), get(self, S<"theory">())) }); });
  c.field("store", [](const Value& self) -> Value { return get(get(self, S<"prover">()), S<"closure">()); });
  c.field("chain", [](const Value& self) -> Value { return call(get(self, S<"prover">()), S<"chain">(), { get(self, S<"store">()) }); });
  c.field("NEAR", [](const Value& self) -> Value { return 0.5; });
  c.getter("env", [](Value self, const Args& a1) -> Value {
    auto e_0 = cell(); e_0->v = make(S<"Node">(), { });
    for (const Value& e1 : Each(call(get(self, S<"store">()), S<"all">(), { "is" }))) {
      auto f_1 = cell(e1);
      auto v_1 = cell(); v_1->v = call(K(S<"Expr">()), S<"simplify">(), { get(f_1->v, S<"to">()) });
      if (truthy(eq(get(v_1->v, S<"kind">()), "num"))) {
        setAt(e_0->v, get(f_1->v, S<"of">()), get(v_1->v, S<"value">()));
      }
    };
    set(e_0->v, Sym(str("D")), get(self, S<"D">()));
    set(e_0->v, Sym(str("DEG")), get(self, S<"DEG">()));
    set(e_0->v, Sym(str("l.DEG")), get(self, S<"DEG">()));
    set(e_0->v, Sym(str("\\bar{c}")), 1.0);
    return e_0->v;
    return null;
  });
  c.statik("numeric_of", [](Value self, const Args& a1) -> Value {
    auto e_0 = cell(arg(a1, 0)); auto at_0 = cell(arg(a1, 1));
    return call(K(S<"Expr">()), S<"numeric">(), { call(K(S<"Expr">()), S<"evaluate">(), { e_0->v, at_0->v }), at_0->v });
    return null;
  });
  c.method("fact_at", [](Value self, const Args& a1) -> Value {
    auto name_0 = cell(arg(a1, 0)); auto at_0 = cell(arg(a1, 1));
    auto f_0 = cell(); f_0->v = call(get(self, S<"store">()), S<"fact">(), { "is", name_0->v });
    if (truthy(eq(f_0->v, null))) {
      return RAY_NAN;
    }
    return call(K(S<"Aggregate">()), S<"numeric_of">(), { get(f_0->v, S<"to">()), at_0->v });
    return null;
  });
  c.method("step", [](Value self, const Args& a1) -> Value {
    auto role_0 = cell(arg(a1, 0));
    return call(get(self, S<"chain">()), S<"get">(), { role_0->v });
    return null;
  });
  c.method("says", [](Value self, const Args& a1) -> Value {
    auto role_0 = cell(arg(a1, 0));
    auto st_0 = cell(); st_0->v = call(self, S<"step">(), { role_0->v });
    return (truthy(eq(st_0->v, null)) ? Value("-") : Value("" + str(get(get(st_0->v, S<"fact">()), S<"of">())) + " = " + str(call(K(S<"Expr">()), S<"show">(), { get(get(st_0->v, S<"fact">()), S<"to">()) })) + ""));
    return null;
  });
  c.getter("rho_inf", [](Value self, const Args& a1) -> Value {
    return call(self, S<"fact_at">(), { "\\rho_{\\infty}", get(self, S<"env">()) });
    return null;
  });
  c.getter("settled_env", [](Value self, const Args& a1) -> Value {
    auto e_0 = cell(); e_0->v = get(self, S<"env">());
    set(e_0->v, Sym(str("\\rho")), get(self, S<"rho_inf">()));
    set(e_0->v, Sym(str("\\rho_{\\infty}")), get(self, S<"rho_inf">()));
    return e_0->v;
    return null;
  });
  c.getter("nf_inf", [](Value self, const Args& a1) -> Value {
    auto st_0 = cell(); st_0->v = call(self, S<"step">(), { "settled" });
    if (truthy(eq(st_0->v, null))) {
      return RAY_NAN;
    }
    return call(K(S<"Aggregate">()), S<"numeric_of">(), { get(get(st_0->v, S<"fact">()), S<"to">()), get(self, S<"settled_env">()) });
    return null;
  });
  c.field("base", [](const Value& self) -> Value { return get(self, S<"settled_env">()); });
  c.getter("fold_weight", [](Value self, const Args& a1) -> Value {
    return call(K(S<"Aggregate">()), S<"numeric_of">(), { get(get(self, S<"prover">()), S<"fold_weight">()), get(self, S<"env">()) });
    return null;
  });
  c.method("shell_at", [](Value self, const Args& a1) -> Value {
    auto R_0 = cell(arg(a1, 0));
    auto e_0 = cell(); e_0->v = get(self, S<"base">());
    set(e_0->v, Sym(str("\\bar{R}")), (truthy(lt(R_0->v, get(self, S<"NEAR">()))) ? Value(get(self, S<"NEAR">())) : Value(R_0->v)));
    auto got_0 = cell(); got_0->v = call(self, S<"fact_at">(), { "l.shell\\paren{\\bar{R}}", e_0->v });
    set(e_0->v, Sym(str("\\bar{R}")), null);
    return got_0->v;
    return null;
  });
  c.method("ball_at", [](Value self, const Args& a1) -> Value {
    auto R_0 = cell(arg(a1, 0));
    auto e_0 = cell(); e_0->v = get(self, S<"base">());
    set(e_0->v, Sym(str("\\bar{R}")), (truthy(lt(R_0->v, get(self, S<"NEAR">()))) ? Value(get(self, S<"NEAR">())) : Value(R_0->v)));
    auto got_0 = cell(); got_0->v = call(self, S<"fact_at">(), { "l.ball\\paren{\\bar{R}}.count", e_0->v });
    set(e_0->v, Sym(str("\\bar{R}")), null);
    return got_0->v;
    return null;
  });
  c.method("skin_at", [](Value self, const Args& a1) -> Value {
    auto face_0 = cell(arg(a1, 0));
    auto at_one_0 = cell(); at_one_0->v = sub(1.0, call(self, S<"reach_at">(), { get(self, S<"NEAR">()) }));
    auto got_0 = cell(); got_0->v = sub(1.0, call(self, S<"reach_at">(), { (truthy(lt(face_0->v, get(self, S<"NEAR">()))) ? Value(get(self, S<"NEAR">())) : Value(face_0->v)) }));
    return (truthy(gt(at_one_0->v, 0.0)) ? Value(div(got_0->v, at_one_0->v)) : Value(1.0));
    return null;
  });
  c.method("held_over_sent", [](Value self, const Args& a1) -> Value {
    auto face_0 = cell(arg(a1, 0)); auto beta_0 = cell(arg(a1, 1));
    auto lets_0 = cell(); lets_0->v = mul(call(self, S<"skin_at">(), { face_0->v }), (sub(1.0, beta_0->v)));
    return (truthy(gt(lets_0->v, 0.0)) ? Value(div(call(self, S<"ball_at">(), { face_0->v }), (mul(call(self, S<"ball_at">(), { get(self, S<"NEAR">()) }), lets_0->v)))) : Value(RAY_NAN));
    return null;
  });
  c.field("FACES", [](const Value& self) -> Value { return list({ 1.0, 1.5, 2.0, 3.0, 4.0, 6.0, 8.0, 12.0, 16.0, 24.0, 32.0 }); });
  c.field("BETAS", [](const Value& self) -> Value { return list({ 0.0, 0.225, 0.45, 0.675, 0.9 }); });
  c.getter("carries", [](Value self, const Args& a1) -> Value {
    auto most_0 = cell(); most_0->v = 0.0;
    for (const Value& e1 : Each(get(self, S<"FACES">()))) {
      auto face_1 = cell(e1);
      for (const Value& e2 : Each(get(self, S<"BETAS">()))) {
        auto beta_2 = cell(e2);
        auto q_2 = cell(); q_2->v = call(K(S<"Fmt">()), S<"log10">(), { call(self, S<"held_over_sent">(), { face_1->v, beta_2->v }) });
        if (truthy((truthy(call(K(S<"Fmt">()), S<"finite">(), { q_2->v })) && truthy(gt(q_2->v, most_0->v))))) {
          most_0->v = q_2->v;
        }
      };
    };
    return most_0->v;
    return null;
  });
  c.method("reach_at", [](Value self, const Args& a1) -> Value {
    auto R_0 = cell(arg(a1, 0));
    auto e_0 = cell(); e_0->v = get(self, S<"base">());
    set(e_0->v, Sym(str("\\bar{R}")), (truthy(lt(R_0->v, 0.0)) ? Value(0.0) : Value(R_0->v)));
    auto got_0 = cell(); got_0->v = call(self, S<"fact_at">(), { "l.reach\\paren{\\bar{R}}", e_0->v });
    set(e_0->v, Sym(str("\\bar{R}")), null);
    return got_0->v;
    return null;
  });
  c.field("STEP", [](const Value& self) -> Value { return 0.01; });
  c.field("FAR", [](const Value& self) -> Value { return 400.0; });
  c.field("shells", [](const Value& self) -> Value { return m_map(rng(add(m_round((div(get(self, S<"FAR">()), get(self, S<"STEP">())))), 1.0)), fn([=](const Args& a2) -> Value {
    auto i_1 = cell(arg(a2, 0));
    return call(self, S<"shell_at">(), { mul(i_1->v, get(self, S<"STEP">())) });
    return null;
  })); });
  c.field("reaches", [](const Value& self) -> Value { return m_map(rng(add(m_round((div(get(self, S<"FAR">()), get(self, S<"STEP">())))), 1.0)), fn([=](const Args& a2) -> Value {
    auto i_1 = cell(arg(a2, 0));
    return call(self, S<"reach_at">(), { mul(i_1->v, get(self, S<"STEP">())) });
    return null;
  })); });
  c.method("tabled", [](Value self, const Args& a1) -> Value {
    auto table_0 = cell(arg(a1, 0)); auto R_0 = cell(arg(a1, 1));
    auto u_0 = cell(); u_0->v = div(R_0->v, get(self, S<"STEP">()));
    auto i_0 = cell(); i_0->v = m_floor(u_0->v);
    if (truthy(ge(i_0->v, sub(len(table_0->v), 1.0)))) {
      return elem(table_0->v, sub(len(table_0->v), 1.0));
    }
    if (truthy(lt(i_0->v, 0.0))) {
      return elem(table_0->v, 0.0);
    }
    auto f_0 = cell(); f_0->v = sub(u_0->v, i_0->v);
    return add(mul(elem(table_0->v, i_0->v), (sub(1.0, f_0->v))), mul(elem(table_0->v, add(i_0->v, 1.0)), f_0->v));
    return null;
  });
  c.method("shell", [](Value self, const Args& a1) -> Value {
    auto R_0 = cell(arg(a1, 0));
    return (truthy(gt(R_0->v, get(self, S<"FAR">()))) ? Value(call(self, S<"shell_at">(), { R_0->v })) : Value(call(self, S<"tabled">(), { get(self, S<"shells">()), R_0->v })));
    return null;
  });
  c.method("reach", [](Value self, const Args& a1) -> Value {
    auto R_0 = cell(arg(a1, 0));
    return (truthy(gt(R_0->v, get(self, S<"FAR">()))) ? Value(call(self, S<"reach_at">(), { R_0->v })) : Value(call(self, S<"tabled">(), { get(self, S<"reaches">()), R_0->v })));
    return null;
  });
  c.method("record_at", [](Value self, const Args& a1) -> Value {
    auto masses_0 = cell(arg(a1, 0)); auto xs_0 = cell(arg(a1, 1)); auto ys_0 = cell(arg(a1, 2)); auto x_0 = cell(arg(a1, 3)); auto y_0 = cell(arg(a1, 4)); auto skip_0 = cell(arg(a1, 5));
    return call(self, S<"record_of">(), { masses_0->v, m_map(rng(len(masses_0->v)), fn([=](const Args& a3) -> Value {
      auto i_2 = cell(arg(a3, 0));
      return call(K(S<"Fmt">()), S<"hypot">(), { sub(elem(xs_0->v, i_2->v), x_0->v), sub(elem(ys_0->v, i_2->v), y_0->v) });
      return null;
    })), skip_0->v });
    return null;
  });
  c.method("record_of", [](Value self, const Args& a1) -> Value {
    auto masses_0 = cell(arg(a1, 0)); auto Rs_0 = cell(arg(a1, 1)); auto skip_0 = cell(arg(a1, 2));
    auto st_0 = cell(); st_0->v = call(self, S<"step">(), { "record" });
    if (truthy(eq(st_0->v, null))) {
      return RAY_NAN;
    }
    return call(self, S<"value">(), { get(get(st_0->v, S<"fact">()), S<"to">()), get(self, S<"base">()), masses_0->v, Rs_0->v, skip_0->v });
    return null;
  });
  c.method("value", [](Value self, const Args& a1) -> Value {
    auto e_0 = cell(arg(a1, 0)); auto at_0 = cell(arg(a1, 1)); auto masses_0 = cell(arg(a1, 2)); auto Rs_0 = cell(arg(a1, 3)); auto skip_0 = cell(arg(a1, 4));
    auto k_0 = cell(); k_0->v = get(e_0->v, S<"kind">());
    if (truthy((truthy(eq(k_0->v, "call")) && truthy(m_starts_with(get(e_0->v, S<"label">()), "\\sum"))))) {
      auto total_0 = cell(); total_0->v = 0.0;
      auto names_0 = cell(); names_0->v = get(self, S<"per_body">());
      auto kinds_0 = cell(); kinds_0->v = get(self, S<"per_body_kinds">());
      for (double i1 = 0, n1 = num(len(masses_0->v)); i1 < n1; i1++) {
        auto i_1 = cell(i1);
        if (!truthy(eq(i_1->v, skip_0->v))) {
          auto R_1 = cell(); R_1->v = elem(Rs_0->v, i_1->v);
          for (double i2 = 0, n2 = num(len(names_0->v)); i2 < n2; i2++) {
            auto j_2 = cell(i2);
            setAt(at_0->v, elem(names_0->v, j_2->v), call(self, S<"per_body_value">(), { elem(kinds_0->v, j_2->v), elem(masses_0->v, i_1->v), R_1->v }));
          };
          total_0->v = add(total_0->v, call(self, S<"value">(), { get(e_0->v, S<"base">()), at_0->v, masses_0->v, Rs_0->v, skip_0->v }));
          for (const Value& e2 : Each(names_0->v)) {
            auto nm_2 = cell(e2);
            setAt(at_0->v, nm_2->v, null);
          };
        }
      };
      return total_0->v;
    }
    if (truthy(eq(k_0->v, "num"))) {
      return get(e_0->v, S<"value">());
    }
    if (truthy((truthy(eq(k_0->v, "sym")) || truthy(eq(k_0->v, "field"))))) {
      auto v_0 = cell(); v_0->v = elem(at_0->v, get(e_0->v, S<"label">()));
      return (truthy(eq(v_0->v, null)) ? Value(RAY_NAN) : Value(v_0->v));
    }
    if (truthy(eq(k_0->v, "add"))) {
      auto total_0 = cell(); total_0->v = 0.0;
      for (const Value& e1 : Each(get(e_0->v, S<"of">()))) {
        auto p_1 = cell(e1);
        total_0->v = add(total_0->v, call(self, S<"value">(), { p_1->v, at_0->v, masses_0->v, Rs_0->v, skip_0->v }));
      };
      return total_0->v;
    }
    if (truthy(eq(k_0->v, "mul"))) {
      auto prod_0 = cell(); prod_0->v = 1.0;
      for (const Value& e1 : Each(get(e_0->v, S<"of">()))) {
        auto p_1 = cell(e1);
        prod_0->v = mul(prod_0->v, call(self, S<"value">(), { p_1->v, at_0->v, masses_0->v, Rs_0->v, skip_0->v }));
      };
      return prod_0->v;
    }
    if (truthy(eq(k_0->v, "pow"))) {
      return power(call(self, S<"value">(), { get(e_0->v, S<"base">()), at_0->v, masses_0->v, Rs_0->v, skip_0->v }), call(self, S<"value">(), { get(e_0->v, S<"power">()), at_0->v, masses_0->v, Rs_0->v, skip_0->v }));
    }
    if (truthy(eq(k_0->v, "log"))) {
      return m_ln(call(self, S<"value">(), { get(e_0->v, S<"base">()), at_0->v, masses_0->v, Rs_0->v, skip_0->v }));
    }
    if (truthy(eq(k_0->v, "exp"))) {
      return m_exp(call(self, S<"value">(), { get(e_0->v, S<"base">()), at_0->v, masses_0->v, Rs_0->v, skip_0->v }));
    }
    return call(K(S<"Aggregate">()), S<"numeric_of">(), { e_0->v, at_0->v });
    return null;
  });
  c.method("lean_at", [](Value self, const Args& a1) -> Value {
    auto masses_0 = cell(arg(a1, 0)); auto xs_0 = cell(arg(a1, 1)); auto ys_0 = cell(arg(a1, 2)); auto x_0 = cell(arg(a1, 3)); auto y_0 = cell(arg(a1, 4)); auto skip_0 = cell(arg(a1, 5));
    auto h_0 = cell(); h_0->v = 0.25;
    auto gx_0 = cell(); gx_0->v = div((sub(call(self, S<"record_at">(), { masses_0->v, xs_0->v, ys_0->v, add(x_0->v, h_0->v), y_0->v, skip_0->v }), call(self, S<"record_at">(), { masses_0->v, xs_0->v, ys_0->v, sub(x_0->v, h_0->v), y_0->v, skip_0->v }))), (mul(2.0, h_0->v)));
    auto gy_0 = cell(); gy_0->v = div((sub(call(self, S<"record_at">(), { masses_0->v, xs_0->v, ys_0->v, x_0->v, add(y_0->v, h_0->v), skip_0->v }), call(self, S<"record_at">(), { masses_0->v, xs_0->v, ys_0->v, x_0->v, sub(y_0->v, h_0->v), skip_0->v }))), (mul(2.0, h_0->v)));
    return list({ gx_0->v, gy_0->v });
    return null;
  });
  c.method("read_at", [](Value self, const Args& a1) -> Value {
    auto hx_0 = cell(arg(a1, 0)); auto hy_0 = cell(arg(a1, 1)); auto x_0 = cell(arg(a1, 2)); auto y_0 = cell(arg(a1, 3));
    auto last_0 = cell(); last_0->v = sub(len(hx_0->v), 1.0);
    auto R_0 = cell(); R_0->v = call(K(S<"Fmt">()), S<"hypot">(), { sub(elem(hx_0->v, last_0->v), x_0->v), sub(elem(hy_0->v, last_0->v), y_0->v) });
    auto px_0 = cell(); px_0->v = elem(hx_0->v, last_0->v);
    auto py_0 = cell(); py_0->v = elem(hy_0->v, last_0->v);
    for (double i1 = 0, n1 = num(get(K(S<"Aggregate">()), S<"ROUNDS">())); i1 < n1; i1++) {
      auto r_1 = cell(i1);
      auto back_1 = cell(); back_1->v = m_round(R_0->v);
      if (truthy(gt(back_1->v, last_0->v))) {
        back_1->v = last_0->v;
      }
      auto at_1 = cell(); at_1->v = sub(last_0->v, back_1->v);
      auto vx_1 = cell(); vx_1->v = (truthy(gt(at_1->v, 0.0)) ? Value(sub(elem(hx_0->v, at_1->v), elem(hx_0->v, sub(at_1->v, 1.0)))) : Value(0.0));
      auto vy_1 = cell(); vy_1->v = (truthy(gt(at_1->v, 0.0)) ? Value(sub(elem(hy_0->v, at_1->v), elem(hy_0->v, sub(at_1->v, 1.0)))) : Value(0.0));
      px_0->v = add(elem(hx_0->v, at_1->v), mul(vx_1->v, back_1->v));
      py_0->v = add(elem(hy_0->v, at_1->v), mul(vy_1->v, back_1->v));
      R_0->v = call(K(S<"Fmt">()), S<"hypot">(), { sub(px_0->v, x_0->v), sub(py_0->v, y_0->v) });
    };
    return list({ px_0->v, py_0->v, R_0->v });
    return null;
  });
  c.method("retarded", [](Value self, const Args& a1) -> Value {
    auto hx_0 = cell(arg(a1, 0)); auto hy_0 = cell(arg(a1, 1)); auto x_0 = cell(arg(a1, 2)); auto y_0 = cell(arg(a1, 3));
    return elem(call(self, S<"read_at">(), { hx_0->v, hy_0->v, x_0->v, y_0->v }), 2.0);
    return null;
  });
  c.method("record_history", [](Value self, const Args& a1) -> Value {
    auto masses_0 = cell(arg(a1, 0)); auto hx_0 = cell(arg(a1, 1)); auto hy_0 = cell(arg(a1, 2)); auto x_0 = cell(arg(a1, 3)); auto y_0 = cell(arg(a1, 4)); auto skip_0 = cell(arg(a1, 5));
    return call(self, S<"record_of">(), { masses_0->v, m_map(rng(len(masses_0->v)), fn([=](const Args& a3) -> Value {
      auto i_2 = cell(arg(a3, 0));
      return call(self, S<"retarded">(), { elem(hx_0->v, i_2->v), elem(hy_0->v, i_2->v), x_0->v, y_0->v });
      return null;
    })), skip_0->v });
    return null;
  });
  c.method("lean_history", [](Value self, const Args& a1) -> Value {
    auto masses_0 = cell(arg(a1, 0)); auto hx_0 = cell(arg(a1, 1)); auto hy_0 = cell(arg(a1, 2)); auto x_0 = cell(arg(a1, 3)); auto y_0 = cell(arg(a1, 4)); auto skip_0 = cell(arg(a1, 5));
    auto h_0 = cell(); h_0->v = 0.25;
    auto gx_0 = cell(); gx_0->v = div((sub(call(self, S<"record_history">(), { masses_0->v, hx_0->v, hy_0->v, add(x_0->v, h_0->v), y_0->v, skip_0->v }), call(self, S<"record_history">(), { masses_0->v, hx_0->v, hy_0->v, sub(x_0->v, h_0->v), y_0->v, skip_0->v }))), (mul(2.0, h_0->v)));
    auto gy_0 = cell(); gy_0->v = div((sub(call(self, S<"record_history">(), { masses_0->v, hx_0->v, hy_0->v, x_0->v, add(y_0->v, h_0->v), skip_0->v }), call(self, S<"record_history">(), { masses_0->v, hx_0->v, hy_0->v, x_0->v, sub(y_0->v, h_0->v), skip_0->v }))), (mul(2.0, h_0->v)));
    return list({ gx_0->v, gy_0->v });
    return null;
  });
  c.method("pull", [](Value self, const Args& a1) -> Value {
    auto m_0 = cell(arg(a1, 0)); auto R_0 = cell(arg(a1, 1));
    auto g_0 = cell(); g_0->v = call(self, S<"lean_at">(), { list({ m_0->v }), list({ 0.0 }), list({ 0.0 }), R_0->v, 0.0, neg(1.0) });
    return sub(0.0, elem(g_0->v, 0.0));
    return null;
  });
  c.field("pulls", [](const Value& self) -> Value { return m_map(rng(add(m_round((div(get(self, S<"FAR">()), get(self, S<"STEP">())))), 1.0)), fn([=](const Args& a2) -> Value {
    auto i_1 = cell(arg(a2, 0));
    return call(self, S<"pull">(), { 1.0, mul(i_1->v, get(self, S<"STEP">())) });
    return null;
  })); });
  c.field("linear", [](const Value& self) -> Value { return lt(m_abs((sub(call(self, S<"pull">(), { 2.0, 5.0 }), mul(2.0, call(self, S<"pull">(), { 1.0, 5.0 }))))), mul(0.000000001, (add(m_abs(call(self, S<"pull">(), { 1.0, 5.0 })), 0.000000000001)))); });
  c.method("quick", [](Value self, const Args& a1) -> Value {
    auto m_0 = cell(arg(a1, 0)); auto R_0 = cell(arg(a1, 1));
    if (truthy((!truthy(get(self, S<"linear">()))))) {
      invoke(fail, { "the record is not linear in a body's mass under this derivation: the tabled pull cannot stand in for it" });
    }
    return (truthy(gt(R_0->v, get(self, S<"FAR">()))) ? Value(call(self, S<"pull">(), { m_0->v, R_0->v })) : Value(mul(m_0->v, call(self, S<"tabled">(), { get(self, S<"pulls">()), R_0->v }))));
    return null;
  });
  c.method("circling", [](Value self, const Args& a1) -> Value {
    auto m_0 = cell(arg(a1, 0)); auto R_0 = cell(arg(a1, 1)); auto rho_0 = cell(arg(a1, 2));
    auto a_0 = cell(); a_0->v = call(self, S<"pull">(), { m_0->v, R_0->v });
    return (truthy(gt(a_0->v, 0.0)) ? Value(m_sqrt((mul(a_0->v, rho_0->v)))) : Value(RAY_NAN));
    return null;
  });
  c.method("profile", [](Value self, const Args& a1) -> Value {
    auto radii_0 = cell(arg(a1, 0));
    return m_map(radii_0->v, fn([=](const Args& a3) -> Value {
      auto R_2 = cell(arg(a3, 0));
      return call(self, S<"pull">(), { 1.0, R_2->v });
      return null;
    }));
    return null;
  });
  c.method("well", [](Value self, const Args& a1) -> Value {
    auto m_0 = cell(arg(a1, 0)); auto R_0 = cell(arg(a1, 1));
    auto step_0 = cell(); step_0->v = 0.05;
    auto total_0 = cell(); total_0->v = 0.0;
    auto r_0 = cell(); r_0->v = R_0->v;
    while (truthy(lt(r_0->v, get(self, S<"FAR">())))) {
      total_0->v = add(total_0->v, div(mul(step_0->v, (add(call(self, S<"quick">(), { m_0->v, r_0->v }), call(self, S<"quick">(), { m_0->v, add(r_0->v, step_0->v) })))), 2.0));
      r_0->v = add(r_0->v, step_0->v);
    }
    return sub(0.0, total_0->v);
    return null;
  });
  c.method("arriving", [](Value self, const Args& a1) -> Value {
    auto m_0 = cell(arg(a1, 0)); auto R_far_0 = cell(arg(a1, 1)); auto R_near_0 = cell(arg(a1, 2)); auto twins_0 = cell(arg(a1, 3));
    auto both_0 = cell(); both_0->v = (truthy(twins_0->v) ? Value(2.0) : Value(1.0));
    auto drop_0 = cell(); drop_0->v = mul(both_0->v, (sub(call(self, S<"well">(), { m_0->v, R_far_0->v }), call(self, S<"well">(), { m_0->v, R_near_0->v }))));
    auto ratio_0 = cell(); ratio_0->v = sub(power((div(R_far_0->v, R_near_0->v)), 2.0), 1.0);
    if (truthy((truthy((!truthy((gt(drop_0->v, 0.0))))) || truthy((!truthy((gt(ratio_0->v, 0.0)))))))) {
      return RAY_NAN;
    }
    auto v_rel_0 = cell(); v_rel_0->v = m_sqrt((div(mul(2.0, drop_0->v), ratio_0->v)));
    return (truthy(twins_0->v) ? Value(div(v_rel_0->v, 2.0)) : Value(v_rel_0->v));
    return null;
  });
  c.method("step_bodies", [](Value self, const Args& a1) -> Value {
    auto ms_0 = cell(arg(a1, 0)); auto hx_0 = cell(arg(a1, 1)); auto hy_0 = cell(arg(a1, 2)); auto vx_0 = cell(arg(a1, 3)); auto vy_0 = cell(arg(a1, 4)); auto moving_0 = cell(arg(a1, 5));
    auto n_0 = cell(); n_0->v = len(ms_0->v);
    auto xs_0 = cell(); xs_0->v = m_map(hx_0->v, fn([=](const Args& a3) -> Value {
      auto h_2 = cell(arg(a3, 0));
      return m_last(h_2->v);
      return null;
    }));
    auto ys_0 = cell(); ys_0->v = m_map(hy_0->v, fn([=](const Args& a3) -> Value {
      auto h_2 = cell(arg(a3, 0));
      return m_last(h_2->v);
      return null;
    }));
    for (double i1 = 0, n1 = num(n_0->v); i1 < n1; i1++) {
      auto i_1 = cell(i1);
      if (truthy(elem(moving_0->v, i_1->v))) {
        auto ax_1 = cell(); ax_1->v = 0.0;
        auto ay_1 = cell(); ay_1->v = 0.0;
        for (double i2 = 0, n2 = num(n_0->v); i2 < n2; i2++) {
          auto j_2 = cell(i2);
          if (truthy((!eq(j_2->v, i_1->v)))) {
            auto got_2 = cell(); got_2->v = call(self, S<"read_at">(), { elem(hx_0->v, j_2->v), elem(hy_0->v, j_2->v), elem(xs_0->v, i_1->v), elem(ys_0->v, i_1->v) });
            auto R_2 = cell(); R_2->v = elem(got_2->v, 2.0);
            auto dx_2 = cell(); dx_2->v = sub(elem(got_2->v, 0.0), elem(xs_0->v, i_1->v));
            auto dy_2 = cell(); dy_2->v = sub(elem(got_2->v, 1.0), elem(ys_0->v, i_1->v));
            auto there_2 = cell(); there_2->v = call(K(S<"Fmt">()), S<"hypot">(), { dx_2->v, dy_2->v });
            if (truthy(gt(there_2->v, 0.0))) {
              auto a_2 = cell(); a_2->v = call(self, S<"quick">(), { elem(ms_0->v, j_2->v), R_2->v });
              ax_1->v = add(ax_1->v, div(mul(a_2->v, dx_2->v), there_2->v));
              ay_1->v = add(ay_1->v, div(mul(a_2->v, dy_2->v), there_2->v));
            }
          }
        };
        setAt(vx_0->v, i_1->v, add(elem(vx_0->v, i_1->v), ax_1->v));
        setAt(vy_0->v, i_1->v, add(elem(vy_0->v, i_1->v), ay_1->v));
        auto speed_1 = cell(); speed_1->v = call(K(S<"Fmt">()), S<"hypot">(), { elem(vx_0->v, i_1->v), elem(vy_0->v, i_1->v) });
        if (truthy(gt(speed_1->v, 1.0))) {
          setAt(vx_0->v, i_1->v, div(elem(vx_0->v, i_1->v), speed_1->v));
          setAt(vy_0->v, i_1->v, div(elem(vy_0->v, i_1->v), speed_1->v));
        }
      }
    };
    for (double i1 = 0, n1 = num(n_0->v); i1 < n1; i1++) {
      auto i_1 = cell(i1);
      m_push(elem(hx_0->v, i_1->v), add(elem(xs_0->v, i_1->v), ((truthy(elem(moving_0->v, i_1->v)) ? Value(elem(vx_0->v, i_1->v)) : Value(0.0)))));
      m_push(elem(hy_0->v, i_1->v), add(elem(ys_0->v, i_1->v), ((truthy(elem(moving_0->v, i_1->v)) ? Value(elem(vy_0->v, i_1->v)) : Value(0.0)))));
    };
    return null;
  });
  c.method("nearest", [](Value self, const Args& a1) -> Value {
    auto ms_0 = cell(arg(a1, 0)); auto fars_0 = cell(arg(a1, 1)); auto speeds_0 = cell(arg(a1, 2)); auto k_0 = cell(arg(a1, 3)); auto held_0 = cell(arg(a1, 4)); auto limit_0 = cell(arg(a1, 5));
    auto n_0 = cell(); n_0->v = len(ms_0->v);
    auto hx_0 = cell(); hx_0->v = m_map(fars_0->v, fn([=](const Args& a3) -> Value {
      auto f_2 = cell(arg(a3, 0));
      return list({ f_2->v });
      return null;
    }));
    auto hy_0 = cell(); hy_0->v = m_map(fars_0->v, fn([=](const Args& a3) -> Value {
      auto f_2 = cell(arg(a3, 0));
      return list({ 0.0 });
      return null;
    }));
    auto vx_0 = cell(); vx_0->v = m_map(fars_0->v, fn([=](const Args& a3) -> Value {
      auto f_2 = cell(arg(a3, 0));
      return 0.0;
      return null;
    }));
    auto vy_0 = cell(); vy_0->v = m_map(speeds_0->v, fn([=](const Args& a3) -> Value {
      auto v_2 = cell(arg(a3, 0));
      return sub(0.0, v_2->v);
      return null;
    }));
    auto moving_0 = cell(); moving_0->v = m_map(rng(n_0->v), fn([=](const Args& a3) -> Value {
      auto i_2 = cell(arg(a3, 0));
      return (truthy(gt(i_2->v, 0.0)) || truthy((!truthy(held_0->v))));
      return null;
    }));
    setAt(vy_0->v, 0.0, (truthy(held_0->v) ? Value(0.0) : Value(elem(speeds_0->v, 1.0))));
    auto least_0 = cell(); least_0->v = call(K(S<"Fmt">()), S<"hypot">(), { sub(m_last(elem(hx_0->v, k_0->v)), m_last(elem(hx_0->v, 0.0))), sub(m_last(elem(hy_0->v, k_0->v)), m_last(elem(hy_0->v, 0.0))) });
    auto was_0 = cell(); was_0->v = least_0->v;
    auto t_0 = cell(); t_0->v = 0.0;
    auto turned_0 = cell(); turned_0->v = false;
    while (truthy((truthy(lt(t_0->v, limit_0->v)) && truthy((!truthy(turned_0->v)))))) {
      call(self, S<"step_bodies">(), { ms_0->v, hx_0->v, hy_0->v, vx_0->v, vy_0->v, moving_0->v });
      auto d_0 = cell(); d_0->v = call(K(S<"Fmt">()), S<"hypot">(), { sub(m_last(elem(hx_0->v, k_0->v)), m_last(elem(hx_0->v, 0.0))), sub(m_last(elem(hy_0->v, k_0->v)), m_last(elem(hy_0->v, 0.0))) });
      if (truthy(lt(d_0->v, least_0->v))) {
        least_0->v = d_0->v;
      }
      if (truthy((truthy(gt(d_0->v, was_0->v)) && truthy(lt(d_0->v, add(mul(0.75, elem(fars_0->v, k_0->v)), mul(0.25, least_0->v))))))) {
        turned_0->v = true;
      }
      was_0->v = d_0->v;
      t_0->v = add(t_0->v, 1.0);
    }
    return least_0->v;
    return null;
  });
  c.method("launches", [](Value self, const Args& a1) -> Value {
    auto ms_0 = cell(arg(a1, 0)); auto fars_0 = cell(arg(a1, 1)); auto nears_0 = cell(arg(a1, 2)); auto held_0 = cell(arg(a1, 3)); auto rounds_0 = cell(arg(a1, 4));
    auto n_0 = cell(); n_0->v = len(ms_0->v);
    auto speeds_0 = cell(); speeds_0->v = m_map(rng(n_0->v), fn([=](const Args& a3) -> Value {
      auto k_2 = cell(arg(a3, 0));
      return (truthy(eq(k_2->v, 0.0)) ? Value(0.0) : Value(call(self, S<"arriving">(), { elem(ms_0->v, 0.0), elem(fars_0->v, k_2->v), elem(nears_0->v, k_2->v), (!truthy(held_0->v)) })));
      return null;
    }));
    for (double i1 = 0, n1 = num(n_0->v); i1 < n1; i1++) {
      auto k_1 = cell(i1);
      if (truthy((!truthy(call(K(S<"Fmt">()), S<"finite">(), { elem(speeds_0->v, k_1->v) }))))) {
        setAt(speeds_0->v, k_1->v, 0.0);
      }
    };
    for (double i1 = 0, n1 = num(rounds_0->v); i1 < n1; i1++) {
      auto r_1 = cell(i1);
      for (double i2 = 0, n2 = num(n_0->v); i2 < n2; i2++) {
        auto k_2 = cell(i2);
        if (truthy(gt(k_2->v, 0.0))) {
          auto lo_2 = cell(); lo_2->v = mul(elem(speeds_0->v, k_2->v), 0.5);
          auto hi_2 = cell(); hi_2->v = mul(elem(speeds_0->v, k_2->v), 1.5);
          if (truthy(gt(hi_2->v, 1.0))) {
            hi_2->v = 1.0;
          }
          auto limit_2 = cell(); limit_2->v = m_round((div(mul(20.0, elem(fars_0->v, k_2->v)), ((truthy(gt(elem(speeds_0->v, k_2->v), 0.001)) ? Value(elem(speeds_0->v, k_2->v)) : Value(0.001))))));
          if (truthy(gt(limit_2->v, 40000.0))) {
            limit_2->v = 40000.0;
          }
          for (double i3 = 0, n3 = num(14.0); i3 < n3; i3++) {
            auto b_3 = cell(i3);
            auto mid_3 = cell(); mid_3->v = div((add(lo_2->v, hi_2->v)), 2.0);
            setAt(speeds_0->v, k_2->v, mid_3->v);
            auto got_3 = cell(); got_3->v = call(self, S<"nearest">(), { ms_0->v, fars_0->v, speeds_0->v, k_2->v, held_0->v, limit_2->v });
            if (truthy(lt(got_3->v, elem(nears_0->v, k_2->v)))) {
              lo_2->v = mid_3->v;
            } else {
              hi_2->v = mid_3->v;
            }
          };
          setAt(speeds_0->v, k_2->v, div((add(lo_2->v, hi_2->v)), 2.0));
        }
      };
    };
    return speeds_0->v;
    return null;
  });
  c.statik("kind_of", [](Value self, const Args& a1) -> Value {
    auto name_0 = cell(arg(a1, 0));
    if (truthy(m_starts_with(name_0->v, "l.shell"))) {
      return "shell";
    }
    if (truthy(m_starts_with(name_0->v, "l.reach"))) {
      return "reach";
    }
    if (truthy(m_contains(name_0->v, "\\bar{m}"))) {
      return "mass";
    }
    if (truthy(m_contains(name_0->v, "\\bar{R}"))) {
      return "distance";
    }
    return "constant";
    return null;
  });
  c.getter("per_body", [](Value self, const Args& a1) -> Value {
    return filt(call(K(S<"Model">()), S<"unbound">(), { get(self, S<"summand">()) }), fn([=](const Args& a3) -> Value {
      auto n_2 = cell(arg(a3, 0));
      return (!eq(call(K(S<"Aggregate">()), S<"kind_of">(), { n_2->v }), "constant"));
      return null;
    }));
    return null;
  });
  c.getter("per_body_kinds", [](Value self, const Args& a1) -> Value {
    return m_map(get(self, S<"per_body">()), fn([=](const Args& a3) -> Value {
      auto n_2 = cell(arg(a3, 0));
      return call(K(S<"Aggregate">()), S<"kind_of">(), { n_2->v });
      return null;
    }));
    return null;
  });
  c.method("per_body_value", [](Value self, const Args& a1) -> Value {
    auto kind_0 = cell(arg(a1, 0)); auto m_0 = cell(arg(a1, 1)); auto R_0 = cell(arg(a1, 2));
    if (truthy(eq(kind_0->v, "mass"))) {
      return m_0->v;
    }
    if (truthy(eq(kind_0->v, "distance"))) {
      return R_0->v;
    }
    if (truthy(eq(kind_0->v, "shell"))) {
      return call(self, S<"shell">(), { R_0->v });
    }
    return call(self, S<"reach">(), { R_0->v });
    return null;
  });
  c.statik("summing", [](Value self, const Args& a1) -> Value {
    auto e_0 = cell(arg(a1, 0));
    auto k_0 = cell(); k_0->v = get(e_0->v, S<"kind">());
    if (truthy((truthy(eq(k_0->v, "call")) && truthy(m_starts_with(get(e_0->v, S<"label">()), "\\sum"))))) {
      return e_0->v;
    }
    if (truthy((truthy(eq(k_0->v, "add")) || truthy(eq(k_0->v, "mul"))))) {
      auto found_0 = cell(); found_0->v = null;
      for (const Value& e1 : Each(get(e_0->v, S<"of">()))) {
        auto x_1 = cell(e1);
        if (truthy(eq(found_0->v, null))) {
          found_0->v = call(K(S<"Aggregate">()), S<"summing">(), { x_1->v });
        }
      };
      return found_0->v;
    }
    if (truthy(eq(k_0->v, "pow"))) {
      return orElse(call(K(S<"Aggregate">()), S<"summing">(), { get(e_0->v, S<"base">()) }), [&]() -> Value { return call(K(S<"Aggregate">()), S<"summing">(), { get(e_0->v, S<"power">()) }); });
    }
    if (truthy((truthy((truthy((truthy(eq(k_0->v, "log")) || truthy(eq(k_0->v, "exp")))) || truthy(eq(k_0->v, "call")))) || truthy(eq(k_0->v, "grad"))))) {
      return call(K(S<"Aggregate">()), S<"summing">(), { get(e_0->v, S<"base">()) });
    }
    return null;
    return null;
  });
  c.getter("record_expr", [](Value self, const Args& a1) -> Value {
    auto st_0 = cell(); st_0->v = call(self, S<"step">(), { "record" });
    return (truthy(eq(st_0->v, null)) ? Value(call(K(S<"Expr">()), S<"num">(), { 0.0 })) : Value(get(get(st_0->v, S<"fact">()), S<"to">())));
    return null;
  });
  c.getter("summand", [](Value self, const Args& a1) -> Value {
    auto sum_0 = cell(); sum_0->v = call(K(S<"Aggregate">()), S<"summing">(), { get(self, S<"record_expr">()) });
    return (truthy(eq(sum_0->v, null)) ? Value(call(K(S<"Expr">()), S<"num">(), { 0.0 })) : Value(get(sum_0->v, S<"base">())));
    return null;
  });
  c.getter("outer", [](Value self, const Args& a1) -> Value {
    auto sum_0 = cell(); sum_0->v = call(K(S<"Aggregate">()), S<"summing">(), { get(self, S<"record_expr">()) });
    return (truthy(eq(sum_0->v, null)) ? Value(get(self, S<"record_expr">())) : Value(call(K(S<"Expr">()), S<"swap">(), { get(self, S<"record_expr">()), sum_0->v, call(K(S<"Expr">()), S<"field">(), { "SUM" }) })));
    return null;
  });
  c.getter("shell_expr", [](Value self, const Args& a1) -> Value {
    auto f_0 = cell(); f_0->v = call(get(self, S<"store">()), S<"fact">(), { "is", "l.shell\\paren{\\bar{R}}" });
    return (truthy(eq(f_0->v, null)) ? Value(call(K(S<"Expr">()), S<"num">(), { 1.0 })) : Value(get(f_0->v, S<"to">())));
    return null;
  });
  c.getter("reach_expr", [](Value self, const Args& a1) -> Value {
    auto f_0 = cell(); f_0->v = call(get(self, S<"store">()), S<"fact">(), { "is", "l.reach\\paren{\\bar{R}}" });
    return (truthy(eq(f_0->v, null)) ? Value(call(K(S<"Expr">()), S<"num">(), { 0.0 })) : Value(get(f_0->v, S<"to">())));
    return null;
  });
  c.getter("names", [](Value self, const Args& a1) -> Value {
    auto out_0 = cell(); out_0->v = m_map(get(self, S<"per_body">()), fn([=](const Args& a3) -> Value {
      auto n_2 = cell(arg(a3, 0));
      return n_2->v;
      return null;
    }));
    m_push(out_0->v, "SUM");
    for (const Value& e1 : Each(list({ get(self, S<"outer">()), get(self, S<"summand">()), get(self, S<"shell_expr">()), get(self, S<"reach_expr">()) }))) {
      auto e_1 = cell(e1);
      for (const Value& e2 : Each(call(K(S<"Model">()), S<"unbound">(), { e_1->v }))) {
        auto n_2 = cell(e2);
        if (truthy((truthy((truthy((!truthy(m_contains(out_0->v, n_2->v)))) && truthy((!eq(n_2->v, "\\bar{R}"))))) && truthy((!truthy(m_ends_with(n_2->v, "\\paren{...}"))))))) {
          m_push(out_0->v, n_2->v);
        }
      };
    };
    return out_0->v;
    return null;
  });
  c.getter("constants", [](Value self, const Args& a1) -> Value {
    return m_map(get(self, S<"names">()), fn([=](const Args& a3) -> Value {
      auto n_2 = cell(arg(a3, 0));
      auto v_2 = cell(); v_2->v = (truthy(((truthy(eq(n_2->v, "SUM")) || truthy((!eq(call(K(S<"Aggregate">()), S<"kind_of">(), { n_2->v }), "constant")))))) ? Value(0.0) : Value(elem(get(self, S<"base">()), n_2->v)));
      if (truthy(eq(v_2->v, null))) {
        invoke(fail, { "the record stands on " + str(n_2->v) + ", which the settled vacuum does not bind - bind it in Aggregate.env or fix the derivation" });
      }
      return v_2->v;
      return null;
    }));
    return null;
  });
  c.getter("bindings", [](Value self, const Args& a1) -> Value {
    auto names_0 = cell(); names_0->v = get(self, S<"names">());
    return m_map(get(self, S<"per_body">()), fn([=](const Args& a3) -> Value {
      auto n_2 = cell(arg(a3, 0));
      return "" + str(m_index_of(names_0->v, n_2->v)) + ":" + str(call(K(S<"Aggregate">()), S<"kind_of">(), { n_2->v })) + "";
      return null;
    }));
    return null;
  });
  c.getter("folds_expr", [](Value self, const Args& a1) -> Value {
    auto st_0 = cell(); st_0->v = call(self, S<"step">(), { "folds" });
    return (truthy(eq(st_0->v, null)) ? Value(call(K(S<"Expr">()), S<"num">(), { 0.0 })) : Value(get(get(st_0->v, S<"fact">()), S<"to">())));
    return null;
  });
  c.method("folds_rate", [](Value self, const Args& a1) -> Value {
    auto rho_0 = cell(arg(a1, 0)); auto nf_0 = cell(arg(a1, 1));
    auto at_0 = cell(); at_0->v = get(self, S<"base">());
    auto was_rho_0 = cell(); was_rho_0->v = get(at_0->v, Sym(str("\\rho")));
    set(at_0->v, Sym(str("\\rho")), rho_0->v);
    set(at_0->v, Sym(str("n_{f}")), nf_0->v);
    auto got_0 = cell(); got_0->v = call(K(S<"Expr">()), S<"numeric">(), { get(self, S<"folds_expr">()), at_0->v });
    set(at_0->v, Sym(str("\\rho")), was_rho_0->v);
    set(at_0->v, Sym(str("n_{f}")), null);
    return got_0->v;
    return null;
  });
  c.getter("wgsl", [](Value self, const Args& a1) -> Value {
    auto stray_0 = cell(); stray_0->v = filt(call(K(S<"Model">()), S<"unbound">(), { get(self, S<"folds_expr">()) }), fn([=](const Args& a3) -> Value {
      auto n_2 = cell(arg(a3, 0));
      return (!truthy(m_contains(get(K(S<"Aggregate">()), S<"FOLDS_NAMES">()), n_2->v)));
      return null;
    }));
    if (truthy((!truthy(m_empty(stray_0->v))))) {
      invoke(fail, { "the record's line stands on " + str(get(stray_0->v, S<"join">())) + "", ")}, which a cell does not hold - fill the derivation's constants in" });
    }
    auto folds_code_0 = cell(); folds_code_0->v = call(K(S<"Shaded">()), S<"wgsl">(), { get(self, S<"folds_expr">()), get(K(S<"Aggregate">()), S<"FOLDS_NAMES">()), null });
    auto names_0 = cell(); names_0->v = get(self, S<"names">());
    auto NV_0 = cell(); NV_0->v = len(names_0->v);
    auto rb_0 = cell(); rb_0->v = "\\bar{R}";
    auto shell_code_0 = cell(); shell_code_0->v = call(K(S<"Shaded">()), S<"wgsl">(), { get(self, S<"shell_expr">()), names_0->v, rb_0->v });
    auto reach_code_0 = cell(); reach_code_0->v = call(K(S<"Shaded">()), S<"wgsl">(), { get(self, S<"reach_expr">()), names_0->v, rb_0->v });
    auto summand_code_0 = cell(); summand_code_0->v = call(K(S<"Shaded">()), S<"wgsl">(), { get(self, S<"summand">()), names_0->v, null });
    auto outer_code_0 = cell(); outer_code_0->v = call(K(S<"Shaded">()), S<"wgsl">(), { get(self, S<"outer">()), names_0->v, null });
    auto nl_0 = cell(); nl_0->v = fromCodepoints(list({ 10.0 }));
    return m_join(list({ "var<private> e: array<f32, " + str(NV_0->v) + ">;", "fn shell_at(x: f32) -> f32 { return " + str(shell_code_0->v) + "; }", "fn reach_at(x: f32) -> f32 { return " + str(reach_code_0->v) + "; }", "fn summand() -> f32 { return " + str(summand_code_0->v) + "; }", "fn record_of() -> f32 { return " + str(outer_code_0->v) + "; }", "fn folds_rate(rho: f32, nf: f32) -> f32 { e[0] = rho; e[1] = nf; return " + str(folds_code_0->v) + "; }" }), nl_0->v);
    return null;
  });
}
static const bool R_Aggregate = define_class("Aggregate", "Node", &C_Aggregate);



void part_6() { }

}  // namespace orbitmines::physics
