// GENERATED by `npx ray gen` from implementation/physics.ray - do not edit
import Foundation

/** what the rules come to, as something to look up: every theorem, keyed by theory and then by question, as JSON */
public enum Theorems {
  public static func json() throws -> String {
    guard let url = Bundle.module.url(forResource: "theorems", withExtension: "json") else { throw RayError("theorems.json is not in the package") }
    return try String(contentsOf: url, encoding: .utf8)
  }
}
