(* GENERATED by `npx ray gen` from implementation/physics.ray - do not edit *)
PacletObject[<|
  "Name" -> "OrbitMines/Physics",
  "Version" -> "0.0.1",
  "WolframVersion" -> "13.0+",
  "Description" -> "The discrete theory G - the rules, and the smallest thing that runs them - with the continuous model derived from them and the plan of a simulation of sources. Generated from implementation/physics.ray.",
  "Creator" -> "OrbitMines",
  "License" -> "MIT",
  "PublisherID" -> "OrbitMines",
  "URL" -> "https://github.com/orbitmines/physics",
  "Extensions" -> {
    {"Kernel", "Root" -> "Kernel", "Context" -> {"OrbitMines`Physics`"}},
    {"Asset", "Assets" -> {{"theorems", "Data/theorems.json"}}}
  }
|>]
