[project]
name = "orbitmines-physics"
version = "0.0.1.dev1"
readme = "README.md"
license = "MIT"
authors = [{ name = "OrbitMines", email = "fadi.shawki@orbitmines.com" }]
description = "OrbitMines: Physics Project"
requires-python = ">=3.10"

[project.urls]
Homepage = "https://github.com/orbitmines/physics"

[build-system]
requires = ["setuptools>=77"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
include = ["orbitmines*"]
