-- GENERATED by `npx ray gen` from implementation/physics.ray and implementation/gen - do not edit
import OrbitMines.Physics.Proofs.Basic
set_option linter.unusedVariables false
set_option linter.unusedSimpArgs false
set_option linter.unusedTactic false
set_option maxHeartbeats 4000000
open OrbitMines.Physics.Proofs

/-!
# gravity.doppler (G)

a body that is going somewhere shines on fewer of its ticks, and what it does send arrives closer together ahead of it than behind. What is that worth?

Lean checked 1 of its 3 steps; 2 are premises read off the program and 0 are not checked. And the answer is CHECKED (claim 3 with the settled numbers put in).

- step 3 (what motion does to what a body sends), checked: the inference's relation (claim 4, read off its code) with the lines it stands on put in -  - is this line, by algebra
- answer (the answer), checked: claim 3 with the settled numbers put in
-/

namespace OrbitMines.Physics.Proofs.G.«gravity.doppler»

/-- What the prover takes from the rules: the premises, read off the program BY DESIGN - a rule's own body, the
continuous model the rules were read into, the lattice, a count. None is believed or measured; each is already in the
theory's .ray. -/
structure Premises («the continuous model» «\sigma» «F» «n» «DEG» «\nu» «\rho» «l.\bar{m}» «\omega» «what is taken» «\mathcal{D}» «\beta\cdot\hat{d}» : ℝ) : Prop where
  /-- step 1 (the reading): the continuous model = DEG·\nu·\paren{1 - \rho} + l.\bar{m}·\omega - 2·\sigma·F·n^{2} - the rules read as a line (Reading.ray): the root every derivation passes through -/
  «the reading: the continuous model» : «the continuous model» = (((-1 : ℝ) * (2 : ℝ) * «\sigma» * «F» * («n» ^ 2)) + («DEG» * «\nu» * ((1 : ℝ) + ((-1 : ℝ) * «\rho»))) + ((1 : ℝ) * «l.\bar{m}» * «\omega»))
  /-- step 2 (read off the continuous model): what is taken = \sigma·F·\rho^{2} - read off the continuous model - a term of the line the rules were read into, or how the line is made -/
  «read off the continuous model: what is taken» : «what is taken» = («\sigma» * «F» * («\rho» ^ 2))
  /-- the relation its inference applies (the inference 'what motion does to what a body sends'): \mathcal{D} = \frac{1}{1 - \beta\cdot\hat{d}} - read off its own code (Inferences.ray, or the method of Prove.ray that builds the equation's chain): run on the store as it stood when step 3 arrived, with the lines it stands on as their names, it concludes this - the relation it applies, taken from the program as every premise is -/
  «the inference 'what motion does to what a body sends': \mathcal{D}» : «\mathcal{D}» = (((1 : ℝ) + ((-1 : ℝ) * «\beta\cdot\hat{d}»)))⁻¹

/-- The steps Lean does not check, each with the reason. They are hypotheses of every theorem below - stated, never proven. -/
structure Unchecked («the continuous model» «\sigma» «F» «n» «DEG» «\nu» «\rho» «l.\bar{m}» «\omega» «what is taken» «\mathcal{D}» «\beta\cdot\hat{d}» : ℝ) : Prop

/-- Where the lines are defined: what the prover divides by. Its algebra cancels across these, so they are taken to be nonzero. -/
structure Defined («the continuous model» «\sigma» «F» «n» «DEG» «\nu» «\rho» «l.\bar{m}» «\omega» «what is taken» «\mathcal{D}» «\beta\cdot\hat{d}» : ℝ) : Prop where
  /-- 1 - \beta\cdot\hat{d} is not nought -/
  ne_0 : ((1 : ℝ) + ((-1 : ℝ) * «\beta\cdot\hat{d}»)) ≠ 0

/-- step 3 (what motion does to what a body sends): \mathcal{D} = \frac{1}{1 - \beta\cdot\hat{d}} - CHECKED: the inference's relation (claim 4, read off its code) with the lines it stands on put in -  - is this line, by algebra -/
theorem check_3 («the continuous model» «\sigma» «F» «n» «DEG» «\nu» «\rho» «l.\bar{m}» «\omega» «what is taken» «\mathcal{D}» «\beta\cdot\hat{d}» : ℝ)
    (p : Premises «the continuous model» «\sigma» «F» «n» «DEG» «\nu» «\rho» «l.\bar{m}» «\omega» «what is taken» «\mathcal{D}» «\beta\cdot\hat{d}») (u : Unchecked «the continuous model» «\sigma» «F» «n» «DEG» «\nu» «\rho» «l.\bar{m}» «\omega» «what is taken» «\mathcal{D}» «\beta\cdot\hat{d}») (w : Defined «the continuous model» «\sigma» «F» «n» «DEG» «\nu» «\rho» «l.\bar{m}» «\omega» «what is taken» «\mathcal{D}» «\beta\cdot\hat{d}») :
    «\mathcal{D}» = (((1 : ℝ) + ((-1 : ℝ) * «\beta\cdot\hat{d}»)))⁻¹ := by
  have h4 := p.«the inference 'what motion does to what a body sends': \mathcal{D}»
  have w0 := w.ne_0
  check_algebra

/-- the answer (the answer): \mathcal{D} = \frac{1}{1 - \beta\cdot\hat{d}} - CHECKED: claim 3 with the settled numbers put in -/
theorem answer («the continuous model» «\sigma» «F» «n» «DEG» «\nu» «\rho» «l.\bar{m}» «\omega» «what is taken» «\mathcal{D}» «\beta\cdot\hat{d}» : ℝ)
    (p : Premises «the continuous model» «\sigma» «F» «n» «DEG» «\nu» «\rho» «l.\bar{m}» «\omega» «what is taken» «\mathcal{D}» «\beta\cdot\hat{d}») (u : Unchecked «the continuous model» «\sigma» «F» «n» «DEG» «\nu» «\rho» «l.\bar{m}» «\omega» «what is taken» «\mathcal{D}» «\beta\cdot\hat{d}») (w : Defined «the continuous model» «\sigma» «F» «n» «DEG» «\nu» «\rho» «l.\bar{m}» «\omega» «what is taken» «\mathcal{D}» «\beta\cdot\hat{d}») :
    «\mathcal{D}» = ((((-1 : ℝ) * «\beta\cdot\hat{d}») + (1 : ℝ)))⁻¹ := by
  have h3 := check_3 «the continuous model» «\sigma» «F» «n» «DEG» «\nu» «\rho» «l.\bar{m}» «\omega» «what is taken» «\mathcal{D}» «\beta\cdot\hat{d}» p u w
  have w0 := w.ne_0
  check_algebra



end OrbitMines.Physics.Proofs.G.«gravity.doppler»
