-- GENERATED by `npx ray gen` from implementation/physics.ray and implementation/gen - do not edit
import OrbitMines.Physics.Proofs.Basic
set_option linter.unusedVariables false
set_option linter.unusedSimpArgs false
set_option linter.unusedTactic false
set_option maxHeartbeats 4000000
open OrbitMines.Physics.Proofs

/-!
# gravity.bending (G)

light crossing a body's field is turned by it. How far, and is that the Newtonian answer or twice it?

Lean checked 2 of its 11 steps; 6 are premises read off the program and 3 are not checked. And the answer is CHECKED (claim 11 with the settled numbers put in, with \omega = 1, \sigma = 1, F = \frac{1}{2} put in).

- step 7 (where the making pays for the taking), NOT checked: the inference 'where the making pays for the taking' (Inferences.ray) was run again with the lines it cites standing as their names, to read the relation it applies off its code: its relation holds a root in the name the lines it cites are written in, and they are put in under the root by name - which substitution in a prover does not do; and with every line of the store standing as its name: its relation holds a root in the name the lines it cites are written in, and they are put in under the root by name - which substitution in a prover does not do. So there is no relation to check the line against, and it is stated as the prover wrote it
- step 8 (one over the rate it is removed at), checked: the inference's relation (claim 12, read off its code) with the lines it stands on put in - what is taken = \sigma·F·\rho^{2}, with \sigma = 1, F = \frac{1}{2} put in - is this line, by algebra
- step 9 (a body's own cells thin one another), checked: the inference's relation (claim 15, read off its code) with the lines it stands on put in - \lambda = \frac{1}{\sigma·F·\rho}, with \omega = 1, \sigma = 1, F = \frac{1}{2} put in - is this line, by algebra
- step 10 (what a place has swallowed, where the folding pays for the handing back), NOT checked: the inference 'what a place has swallowed, where the folding pays for the handing back' (Inferences.ray) was run again with the lines it cites standing as their names, to read the relation it applies off its code: it concluded nothing for this line (it looks inside a value, or a guard went the other way); and with every line of the store standing as its name: it concluded nothing for this line (it looks inside a value, or a guard went the other way). So there is no relation to check the line against, and it is stated as the prover wrote it
- step 11 (the integral of the index across the path), NOT checked: the inference 'the integral of the index across the path' (Inferences.ray) was run again with the lines it cites standing as their names, to read the relation it applies off its code: its relation, \alpha = 2·\delta n_{f}, with the lines put back is not this line by algebra; and with every line of the store standing as its name: its relation, \alpha = 2·\delta n_{f}, with the lines put back is not this line by algebra. So there is no relation to check the line against, and it is stated as the prover wrote it
- settled number 14 (isotropy leaves no mean heading), NOT checked: the inference 'isotropy leaves no mean heading' reached it from what the store held in its own code (Inferences.ray, Prove.ray): the relation it applies to them is not recorded with the step, so there is nothing to check the line against - it is stated as the prover wrote it
- answer (the answer), checked: claim 11 with the settled numbers put in, with \omega = 1, \sigma = 1, F = \frac{1}{2} put in
-/

namespace OrbitMines.Physics.Proofs.G.«gravity.bending»

/-- What the prover takes from the rules: the premises, read off the program BY DESIGN - a rule's own body, the
continuous model the rules were read into, the lattice, a count. None is believed or measured; each is already in the
theory's .ray. -/
structure Premises («the continuous model» «\sigma» «F» «n» «DEG» «\nu» «\rho» «l.\bar{m}» «\omega» «the folds line nets» «n_{f}» «what a body feels» «\sum\hat{d}» «S» «what is taken» «what is made» «\rho_{\infty}» «\lambda» «what a body puts into the medium» «\bar{m}_{x}» «l.DEG» «\beta» «A» «\bar{R}» «\delta n_{f}» «r» «D» «\alpha» «b» : ℝ) : Prop where
  /-- step 1 (the reading): the continuous model = DEG·\nu·\paren{1 - \rho} + l.\bar{m}·\omega - 2·\sigma·F·n^{2} - the rules read as a line (Reading.ray): the root every derivation passes through -/
  «the reading: the continuous model» : «the continuous model» = (((-1 : ℝ) * (2 : ℝ) * «\sigma» * «F» * («n» ^ 2)) + («DEG» * «\nu» * ((1 : ℝ) + ((-1 : ℝ) * «\rho»))) + ((1 : ℝ) * «l.\bar{m}» * «\omega»))
  /-- step 2 (read off the continuous model): the folds line nets = \sigma·F·\rho^{2} - \nu·n_{f}·\paren{1 - \rho} - read off the continuous model - a term of the line the rules were read into, or how the line is made -/
  «read off the continuous model: the folds line nets» : «the folds line nets» = ((«\sigma» * «F» * («\rho» ^ 2)) + ((-1 : ℝ) * «\nu» * «n_{f}» * (((-1 : ℝ) * «\rho») + (1 : ℝ))))
  /-- step 3 (EMISSION): what a body feels = \sum\hat{d} - the rule EMISSION, read off its own body -/
  «EMISSION: what a body feels» : «what a body feels» = «\sum\hat{d}»
  /-- step 4 (read off the continuous model): S = 0 - read off the continuous model - a term of the line the rules were read into, or how the line is made -/
  «read off the continuous model: S» : «S» = (0 : ℝ)
  /-- step 5 (read off the continuous model): what is taken = \sigma·F·\rho^{2} - read off the continuous model - a term of the line the rules were read into, or how the line is made -/
  «read off the continuous model: what is taken» : «what is taken» = («\sigma» * «F» * («\rho» ^ 2))
  /-- step 6 (read off the continuous model): what is made = \nu·\paren{1 - \rho} - read off the continuous model - a term of the line the rules were read into, or how the line is made -/
  «read off the continuous model: what is made» : «what is made» = («\nu» * (((-1 : ℝ) * «\rho») + (1 : ℝ)))
  /-- the relation its inference applies (the inference 'one over the rate it is removed at'): \lambda = \frac{\rho}{what is taken} - read off its own code (Inferences.ray, or the method of Prove.ray that builds the equation's chain): run on the store as it stood when step 8 arrived, with the lines it stands on as their names, it concludes this - the relation it applies, taken from the program as every premise is -/
  «the inference 'one over the rate it is removed at': \lambda» : «\lambda» = ((«what is taken»)⁻¹ * «\rho»)
  /-- a settled number (read off the continuous model): \sigma = 1 - read off the continuous model - a term of the line the rules were read into, or how the line is made -/
  «read off the continuous model: \sigma» : «\sigma» = (1 : ℝ)
  /-- the relation its inference applies (the inference 'a body's own cells thin one another'): what a body puts into the medium = l.choose\paren{\bar{m}_{x·l.DEG·\paren{1 - \beta}}}·\omega·A·\lambda·\paren{1 - \paren{1 - \frac{1}{\lambda}}^{\bar{R}}} - read off its own code (Inferences.ray, or the method of Prove.ray that builds the equation's chain): run on the store as it stood when step 9 arrived, with the lines it stands on as their names, it concludes this - the relation it applies, taken from the program as every premise is -/
  «the inference 'a body's own cells thin one another': what a body puts into the medium» : «what a body puts into the medium» = ((Fn "l.choose" («\bar{m}_{x}» * «l.DEG» * (((-1 : ℝ) * «\beta») + (1 : ℝ)))) * «\omega» * «A» * «\lambda» * (((-1 : ℝ) * ((((-1 : ℝ) * («\lambda»)⁻¹) + (1 : ℝ)) ^ «\bar{R}»)) + (1 : ℝ)))
  /-- a settled number (read off the continuous model): \omega = 1 - read off the continuous model - a term of the line the rules were read into, or how the line is made -/
  «read off the continuous model: \omega» : «\omega» = (1 : ℝ)

/-- The steps Lean does not check, each with the reason. They are hypotheses of every theorem below - stated, never proven. -/
structure Unchecked («the continuous model» «\sigma» «F» «n» «DEG» «\nu» «\rho» «l.\bar{m}» «\omega» «the folds line nets» «n_{f}» «what a body feels» «\sum\hat{d}» «S» «what is taken» «what is made» «\rho_{\infty}» «\lambda» «what a body puts into the medium» «\bar{m}_{x}» «l.DEG» «\beta» «A» «\bar{R}» «\delta n_{f}» «r» «D» «\alpha» «b» : ℝ) : Prop where
  /-- step 7 (where the making pays for the taking): \rho_{\infty} = \text{the } \rho \text{ where } DEG·\paren{1 - \rho} - 2·F·\rho^{2} = 0 - NOT CHECKED: the inference 'where the making pays for the taking' (Inferences.ray) was run again with the lines it cites standing as their names, to read the relation it applies off its code: its relation holds a root in the name the lines it cites are written in, and they are put in under the root by name - which substitution in a prover does not do; and with every line of the store standing as its name: its relation holds a root in the name the lines it cites are written in, and they are put in under the root by name - which substitution in a prover does not do. So there is no relation to check the line against, and it is stated as the prover wrote it -/
  unchecked_gravity_bending_7 : «\rho_{\infty}» = (RootOf (fun («\rho» : ℝ) => ((«DEG» * (((-1 : ℝ) * «\rho») + (1 : ℝ))) + ((-2 : ℝ) * «F» * («\rho» ^ 2)))))
  /-- step 10 (what a place has swallowed, where the folding pays for the handing back): \delta n_{f} = \frac{l.choose\paren{\bar{m}_{x·l.DEG·\paren{1 - \beta}}}·\omega·A·\paren{1 - \paren{1 - \sigma·F·\rho}^{\bar{R}}}·r^{-\paren{D - 2}}}{\sigma·F·\rho} - NOT CHECKED: the inference 'what a place has swallowed, where the folding pays for the handing back' (Inferences.ray) was run again with the lines it cites standing as their names, to read the relation it applies off its code: it concluded nothing for this line (it looks inside a value, or a guard went the other way); and with every line of the store standing as its name: it concluded nothing for this line (it looks inside a value, or a guard went the other way). So there is no relation to check the line against, and it is stated as the prover wrote it -/
  unchecked_gravity_bending_10 : «\delta n_{f}» = ((Fn "l.choose" («\bar{m}_{x}» * «l.DEG» * (((-1 : ℝ) * «\beta») + (1 : ℝ)))) * «\omega» * «A» * («\sigma»)⁻¹ * («F»)⁻¹ * («\rho»)⁻¹ * (((-1 : ℝ) * ((((-1 : ℝ) * «\sigma» * «F» * «\rho») + (1 : ℝ)) ^ «\bar{R}»)) + (1 : ℝ)) * («r» ^ ((-1 : ℝ) * («D» + (-2 : ℝ)))))
  /-- step 11 (the integral of the index across the path): \alpha = \frac{2·l.choose\paren{\bar{m}_{x·l.DEG·\paren{1 - \beta}}}·\omega·A·\paren{1 - \paren{1 - \sigma·F·\rho}^{\bar{R}}}·b^{-\paren{D - 2}}}{\sigma·F·\rho} - NOT CHECKED: the inference 'the integral of the index across the path' (Inferences.ray) was run again with the lines it cites standing as their names, to read the relation it applies off its code: its relation, \alpha = 2·\delta n_{f}, with the lines put back is not this line by algebra; and with every line of the store standing as its name: its relation, \alpha = 2·\delta n_{f}, with the lines put back is not this line by algebra. So there is no relation to check the line against, and it is stated as the prover wrote it -/
  unchecked_gravity_bending_11 : «\alpha» = ((2 : ℝ) * (Fn "l.choose" («\bar{m}_{x}» * «l.DEG» * (((-1 : ℝ) * «\beta») + (1 : ℝ)))) * «\omega» * «A» * («\sigma»)⁻¹ * («F»)⁻¹ * («\rho»)⁻¹ * (((-1 : ℝ) * ((((-1 : ℝ) * «\sigma» * «F» * «\rho») + (1 : ℝ)) ^ «\bar{R}»)) + (1 : ℝ)) * («b» ^ ((-1 : ℝ) * («D» + (-2 : ℝ)))))
  /-- a settled number (isotropy leaves no mean heading): F = \frac{1}{2} - NOT CHECKED: the inference 'isotropy leaves no mean heading' reached it from what the store held in its own code (Inferences.ray, Prove.ray): the relation it applies to them is not recorded with the step, so there is nothing to check the line against - it is stated as the prover wrote it -/
  unchecked_gravity_bending_14 : «F» = ((1 : ℝ) * ((2 : ℝ))⁻¹)

/-- Where the lines are defined: what the prover divides by. Its algebra cancels across these, so they are taken to be nonzero. -/
structure Defined («the continuous model» «\sigma» «F» «n» «DEG» «\nu» «\rho» «l.\bar{m}» «\omega» «the folds line nets» «n_{f}» «what a body feels» «\sum\hat{d}» «S» «what is taken» «what is made» «\rho_{\infty}» «\lambda» «what a body puts into the medium» «\bar{m}_{x}» «l.DEG» «\beta» «A» «\bar{R}» «\delta n_{f}» «r» «D» «\alpha» «b» : ℝ) : Prop where
  /-- \sigma is not nought -/
  ne_0 : «\sigma» ≠ 0
  /-- F is not nought -/
  ne_1 : «F» ≠ 0
  /-- \rho is not nought -/
  ne_2 : «\rho» ≠ 0
  /-- what is taken is not nought -/
  ne_3 : «what is taken» ≠ 0
  /-- \lambda is not nought -/
  ne_4 : «\lambda» ≠ 0
  /-- 1 - \sigma·F·\rho is positive: it is raised to a real power -/
  pos_0 : 0 < (((-1 : ℝ) * «\sigma» * «F» * «\rho») + (1 : ℝ))
  /-- r is positive: it is raised to a real power -/
  pos_1 : 0 < «r»
  /-- b is positive: it is raised to a real power -/
  pos_2 : 0 < «b»
  /-- 1 - \frac{1}{\lambda} is positive: it is raised to a real power -/
  pos_3 : 0 < (((-1 : ℝ) * («\lambda»)⁻¹) + (1 : ℝ))
  /-- 1 - \frac{\rho}{2} is positive: it is raised to a real power -/
  pos_4 : 0 < ((((-5 : ℝ) / 10) * «\rho») + (1 : ℝ))

/-- step 8 (one over the rate it is removed at): \lambda = \frac{1}{\sigma·F·\rho} - CHECKED: the inference's relation (claim 12, read off its code) with the lines it stands on put in - what is taken = \sigma·F·\rho^{2}, with \sigma = 1, F = \frac{1}{2} put in - is this line, by algebra -/
theorem check_8 («the continuous model» «\sigma» «F» «n» «DEG» «\nu» «\rho» «l.\bar{m}» «\omega» «the folds line nets» «n_{f}» «what a body feels» «\sum\hat{d}» «S» «what is taken» «what is made» «\rho_{\infty}» «\lambda» «what a body puts into the medium» «\bar{m}_{x}» «l.DEG» «\beta» «A» «\bar{R}» «\delta n_{f}» «r» «D» «\alpha» «b» : ℝ)
    (p : Premises «the continuous model» «\sigma» «F» «n» «DEG» «\nu» «\rho» «l.\bar{m}» «\omega» «the folds line nets» «n_{f}» «what a body feels» «\sum\hat{d}» «S» «what is taken» «what is made» «\rho_{\infty}» «\lambda» «what a body puts into the medium» «\bar{m}_{x}» «l.DEG» «\beta» «A» «\bar{R}» «\delta n_{f}» «r» «D» «\alpha» «b») (u : Unchecked «the continuous model» «\sigma» «F» «n» «DEG» «\nu» «\rho» «l.\bar{m}» «\omega» «the folds line nets» «n_{f}» «what a body feels» «\sum\hat{d}» «S» «what is taken» «what is made» «\rho_{\infty}» «\lambda» «what a body puts into the medium» «\bar{m}_{x}» «l.DEG» «\beta» «A» «\bar{R}» «\delta n_{f}» «r» «D» «\alpha» «b») (w : Defined «the continuous model» «\sigma» «F» «n» «DEG» «\nu» «\rho» «l.\bar{m}» «\omega» «the folds line nets» «n_{f}» «what a body feels» «\sum\hat{d}» «S» «what is taken» «what is made» «\rho_{\infty}» «\lambda» «what a body puts into the medium» «\bar{m}_{x}» «l.DEG» «\beta» «A» «\bar{R}» «\delta n_{f}» «r» «D» «\alpha» «b») :
    «\lambda» = ((«\sigma»)⁻¹ * («F»)⁻¹ * («\rho»)⁻¹) := by
  have h12 := p.«the inference 'one over the rate it is removed at': \lambda»
  have h5 := p.«read off the continuous model: what is taken»
  have h13 := p.«read off the continuous model: \sigma»
  have h14 := u.unchecked_gravity_bending_14
  have w0 := w.ne_0
  have w1 := w.ne_1
  have w2 := w.ne_2
  have w3 := w.ne_3
  have w4 := w.ne_4
  have p0 := w.pos_0
  have r0 := fun (y : ℝ) => Real.rpow_neg (le_of_lt w.pos_0) y
  have q0 := fun (y : ℝ) => (Real.rpow_pos_of_pos w.pos_0 y).ne'
  have p1 := w.pos_1
  have r1 := fun (y : ℝ) => Real.rpow_neg (le_of_lt w.pos_1) y
  have q1 := fun (y : ℝ) => (Real.rpow_pos_of_pos w.pos_1 y).ne'
  have p2 := w.pos_2
  have r2 := fun (y : ℝ) => Real.rpow_neg (le_of_lt w.pos_2) y
  have q2 := fun (y : ℝ) => (Real.rpow_pos_of_pos w.pos_2 y).ne'
  have p3 := w.pos_3
  have r3 := fun (y : ℝ) => Real.rpow_neg (le_of_lt w.pos_3) y
  have q3 := fun (y : ℝ) => (Real.rpow_pos_of_pos w.pos_3 y).ne'
  have p4 := w.pos_4
  have r4 := fun (y : ℝ) => Real.rpow_neg (le_of_lt w.pos_4) y
  have q4 := fun (y : ℝ) => (Real.rpow_pos_of_pos w.pos_4 y).ne'
  subst_vars
  try simp only [neg_one_mul, r0, r1, r2, r3, r4] at *
  check_algebra

/-- step 9 (a body's own cells thin one another): what a body puts into the medium = \frac{l.choose\paren{\bar{m}_{x·l.DEG·\paren{1 - \beta}}}·\omega·A·\paren{1 - \paren{1 - \sigma·F·\rho}^{\bar{R}}}}{\sigma·F·\rho} - CHECKED: the inference's relation (claim 15, read off its code) with the lines it stands on put in - \lambda = \frac{1}{\sigma·F·\rho}, with \omega = 1, \sigma = 1, F = \frac{1}{2} put in - is this line, by algebra -/
theorem check_9 («the continuous model» «\sigma» «F» «n» «DEG» «\nu» «\rho» «l.\bar{m}» «\omega» «the folds line nets» «n_{f}» «what a body feels» «\sum\hat{d}» «S» «what is taken» «what is made» «\rho_{\infty}» «\lambda» «what a body puts into the medium» «\bar{m}_{x}» «l.DEG» «\beta» «A» «\bar{R}» «\delta n_{f}» «r» «D» «\alpha» «b» : ℝ)
    (p : Premises «the continuous model» «\sigma» «F» «n» «DEG» «\nu» «\rho» «l.\bar{m}» «\omega» «the folds line nets» «n_{f}» «what a body feels» «\sum\hat{d}» «S» «what is taken» «what is made» «\rho_{\infty}» «\lambda» «what a body puts into the medium» «\bar{m}_{x}» «l.DEG» «\beta» «A» «\bar{R}» «\delta n_{f}» «r» «D» «\alpha» «b») (u : Unchecked «the continuous model» «\sigma» «F» «n» «DEG» «\nu» «\rho» «l.\bar{m}» «\omega» «the folds line nets» «n_{f}» «what a body feels» «\sum\hat{d}» «S» «what is taken» «what is made» «\rho_{\infty}» «\lambda» «what a body puts into the medium» «\bar{m}_{x}» «l.DEG» «\beta» «A» «\bar{R}» «\delta n_{f}» «r» «D» «\alpha» «b») (w : Defined «the continuous model» «\sigma» «F» «n» «DEG» «\nu» «\rho» «l.\bar{m}» «\omega» «the folds line nets» «n_{f}» «what a body feels» «\sum\hat{d}» «S» «what is taken» «what is made» «\rho_{\infty}» «\lambda» «what a body puts into the medium» «\bar{m}_{x}» «l.DEG» «\beta» «A» «\bar{R}» «\delta n_{f}» «r» «D» «\alpha» «b») :
    «what a body puts into the medium» = ((Fn "l.choose" («\bar{m}_{x}» * «l.DEG» * (((-1 : ℝ) * «\beta») + (1 : ℝ)))) * «\omega» * «A» * («\sigma»)⁻¹ * («F»)⁻¹ * («\rho»)⁻¹ * (((-1 : ℝ) * ((((-1 : ℝ) * «\sigma» * «F» * «\rho») + (1 : ℝ)) ^ «\bar{R}»)) + (1 : ℝ))) := by
  have h15 := p.«the inference 'a body's own cells thin one another': what a body puts into the medium»
  have h8 := check_8 «the continuous model» «\sigma» «F» «n» «DEG» «\nu» «\rho» «l.\bar{m}» «\omega» «the folds line nets» «n_{f}» «what a body feels» «\sum\hat{d}» «S» «what is taken» «what is made» «\rho_{\infty}» «\lambda» «what a body puts into the medium» «\bar{m}_{x}» «l.DEG» «\beta» «A» «\bar{R}» «\delta n_{f}» «r» «D» «\alpha» «b» p u w
  have h16 := p.«read off the continuous model: \omega»
  have h13 := p.«read off the continuous model: \sigma»
  have h14 := u.unchecked_gravity_bending_14
  have w0 := w.ne_0
  have w1 := w.ne_1
  have w2 := w.ne_2
  have w3 := w.ne_3
  have w4 := w.ne_4
  have p0 := w.pos_0
  have r0 := fun (y : ℝ) => Real.rpow_neg (le_of_lt w.pos_0) y
  have q0 := fun (y : ℝ) => (Real.rpow_pos_of_pos w.pos_0 y).ne'
  have p1 := w.pos_1
  have r1 := fun (y : ℝ) => Real.rpow_neg (le_of_lt w.pos_1) y
  have q1 := fun (y : ℝ) => (Real.rpow_pos_of_pos w.pos_1 y).ne'
  have p2 := w.pos_2
  have r2 := fun (y : ℝ) => Real.rpow_neg (le_of_lt w.pos_2) y
  have q2 := fun (y : ℝ) => (Real.rpow_pos_of_pos w.pos_2 y).ne'
  have p3 := w.pos_3
  have r3 := fun (y : ℝ) => Real.rpow_neg (le_of_lt w.pos_3) y
  have q3 := fun (y : ℝ) => (Real.rpow_pos_of_pos w.pos_3 y).ne'
  have p4 := w.pos_4
  have r4 := fun (y : ℝ) => Real.rpow_neg (le_of_lt w.pos_4) y
  have q4 := fun (y : ℝ) => (Real.rpow_pos_of_pos w.pos_4 y).ne'
  subst_vars
  try simp only [neg_one_mul, r0, r1, r2, r3, r4] at *
  check_algebra

/-- the answer (the answer): \alpha = \frac{4·l.choose\paren{\bar{m}_{x·l.DEG·\paren{1 - \beta}}}·A·\paren{1 - \paren{1 - \frac{\rho}{2}}^{\bar{R}}}·b^{-\paren{D - 2}}}{\rho} - CHECKED: claim 11 with the settled numbers put in, with \omega = 1, \sigma = 1, F = \frac{1}{2} put in -/
theorem answer («the continuous model» «\sigma» «F» «n» «DEG» «\nu» «\rho» «l.\bar{m}» «\omega» «the folds line nets» «n_{f}» «what a body feels» «\sum\hat{d}» «S» «what is taken» «what is made» «\rho_{\infty}» «\lambda» «what a body puts into the medium» «\bar{m}_{x}» «l.DEG» «\beta» «A» «\bar{R}» «\delta n_{f}» «r» «D» «\alpha» «b» : ℝ)
    (p : Premises «the continuous model» «\sigma» «F» «n» «DEG» «\nu» «\rho» «l.\bar{m}» «\omega» «the folds line nets» «n_{f}» «what a body feels» «\sum\hat{d}» «S» «what is taken» «what is made» «\rho_{\infty}» «\lambda» «what a body puts into the medium» «\bar{m}_{x}» «l.DEG» «\beta» «A» «\bar{R}» «\delta n_{f}» «r» «D» «\alpha» «b») (u : Unchecked «the continuous model» «\sigma» «F» «n» «DEG» «\nu» «\rho» «l.\bar{m}» «\omega» «the folds line nets» «n_{f}» «what a body feels» «\sum\hat{d}» «S» «what is taken» «what is made» «\rho_{\infty}» «\lambda» «what a body puts into the medium» «\bar{m}_{x}» «l.DEG» «\beta» «A» «\bar{R}» «\delta n_{f}» «r» «D» «\alpha» «b») (w : Defined «the continuous model» «\sigma» «F» «n» «DEG» «\nu» «\rho» «l.\bar{m}» «\omega» «the folds line nets» «n_{f}» «what a body feels» «\sum\hat{d}» «S» «what is taken» «what is made» «\rho_{\infty}» «\lambda» «what a body puts into the medium» «\bar{m}_{x}» «l.DEG» «\beta» «A» «\bar{R}» «\delta n_{f}» «r» «D» «\alpha» «b») :
    «\alpha» = ((4 : ℝ) * (Fn "l.choose" («\bar{m}_{x}» * «l.DEG» * (((-1 : ℝ) * «\beta») + (1 : ℝ)))) * «A» * («\rho»)⁻¹ * (((-1 : ℝ) * (((((-5 : ℝ) / 10) * «\rho») + (1 : ℝ)) ^ «\bar{R}»)) + (1 : ℝ)) * («b» ^ ((-1 : ℝ) * («D» + (-2 : ℝ))))) := by
  have h11 := u.unchecked_gravity_bending_11
  have h16 := p.«read off the continuous model: \omega»
  have h13 := p.«read off the continuous model: \sigma»
  have h14 := u.unchecked_gravity_bending_14
  have w0 := w.ne_0
  have w1 := w.ne_1
  have w2 := w.ne_2
  have w3 := w.ne_3
  have w4 := w.ne_4
  have p0 := w.pos_0
  have r0 := fun (y : ℝ) => Real.rpow_neg (le_of_lt w.pos_0) y
  have q0 := fun (y : ℝ) => (Real.rpow_pos_of_pos w.pos_0 y).ne'
  have p1 := w.pos_1
  have r1 := fun (y : ℝ) => Real.rpow_neg (le_of_lt w.pos_1) y
  have q1 := fun (y : ℝ) => (Real.rpow_pos_of_pos w.pos_1 y).ne'
  have p2 := w.pos_2
  have r2 := fun (y : ℝ) => Real.rpow_neg (le_of_lt w.pos_2) y
  have q2 := fun (y : ℝ) => (Real.rpow_pos_of_pos w.pos_2 y).ne'
  have p3 := w.pos_3
  have r3 := fun (y : ℝ) => Real.rpow_neg (le_of_lt w.pos_3) y
  have q3 := fun (y : ℝ) => (Real.rpow_pos_of_pos w.pos_3 y).ne'
  have p4 := w.pos_4
  have r4 := fun (y : ℝ) => Real.rpow_neg (le_of_lt w.pos_4) y
  have q4 := fun (y : ℝ) => (Real.rpow_pos_of_pos w.pos_4 y).ne'
  subst_vars
  try simp only [neg_one_mul, r0, r1, r2, r3, r4] at *
  check_algebra



end OrbitMines.Physics.Proofs.G.«gravity.bending»
