-- GENERATED by `npx ray gen` from implementation/physics.ray and implementation/gen - do not edit
import OrbitMines.Physics.Proofs.Basic
set_option linter.unusedVariables false
set_option linter.unusedSimpArgs false
set_option linter.unusedTactic false
set_option maxHeartbeats 4000000
open OrbitMines.Physics.Proofs

/-!
# gravity.coincidence (G)

the scale a rotation curve turns over at and the rate the world expands at are both rates of the one vacuum. What is their ratio - and which lattice puts it where it is measured?

Lean checked 8 of its 24 steps; 13 are premises read off the program and 3 are not checked. And the answer is CHECKED (claim 24 with the settled numbers put in, with \omega = 1, \sigma = 1, F = \frac{1}{2}, \nu = 1, \bar{n} = 0 put in).

- step 3 (the rate the empty vacuum expands at), NOT checked: the inference 'the rate the empty vacuum expands at' (Inferences.ray) was run again with the lines it cites standing as their names, to read the relation it applies off its code: it concluded nothing for this line (it looks inside a value, or a guard went the other way); and with every line of the store standing as its name: it concluded nothing for this line (it looks inside a value, or a guard went the other way). So there is no relation to check the line against, and it is stated as the prover wrote it
- step 9 (where the making pays for the taking), NOT checked: the inference 'where the making pays for the taking' (Inferences.ray) was run again with the lines it cites standing as their names, to read the relation it applies off its code: its relation holds a root in the name the lines it cites are written in, and they are put in under the root by name - which substitution in a prover does not do; and with every line of the store standing as its name: its relation holds a root in the name the lines it cites are written in, and they are put in under the root by name - which substitution in a prover does not do. So there is no relation to check the line against, and it is stated as the prover wrote it
- step 10 (one over the rate it is removed at), checked: the inference's relation (claim 25, read off its code) with the lines it stands on put in - what is taken = \sigma·F·\rho^{2}, with \sigma = 1, F = \frac{1}{2} put in - is this line, by algebra
- step 11 (a body's own cells thin one another), checked: the inference's relation (claim 28, read off its code) with the lines it stands on put in - \lambda = \frac{1}{\sigma·F·\rho}, with \omega = 1, \sigma = 1, F = \frac{1}{2} put in - is this line, by algebra
- step 12 (what a place has swallowed, where the folding pays for the handing back), NOT checked: the inference 'what a place has swallowed, where the folding pays for the handing back' (Inferences.ray) was run again with the lines it cites standing as their names, to read the relation it applies off its code: it concluded nothing for this line (it looks inside a value, or a guard went the other way); and with every line of the store standing as its name: it concluded nothing for this line (it looks inside a value, or a guard went the other way). So there is no relation to check the line against, and it is stated as the prover wrote it
- step 14 (how fast a carrier goes, which is the share of its step that was straight), checked: the inference's relation (claim 30, read off its code) with the lines it stands on put in - n_{f} = \frac{l.choose\paren{\bar{m}_{x·l.DEG·\paren{1 - \beta}}}·\omega·A·\paren{1 - \paren{1 - \sigma·F·\rho}^{\bar{R}}}·r^{-\paren{D - 2}}}{\sigma·F·\rho} - \frac{\sigma·F·\rho^{2}}{\nu·\rho - \nu}; \bar{c} = 1, with \omega = 1, \sigma = 1, F = \frac{1}{2}, \nu = 1 put in - is this line, by algebra
- step 15 (the phase between the two pulses, which the body's own acceleration keeps from cancelling), checked: the inference's relation (claim 32, read off its code) with the lines it stands on put in - H_{\Lambda} = \frac{2·\sigma·F·\paren{1 - \rho}·\rho^{2}}{D}; v = \frac{\omega}{n_{f} + 1}, with \omega = 1, \sigma = 1, F = \frac{1}{2} put in - is this line, by algebra
- step 18 (the room the line does not supply, which the waiting has to make), checked: the inference's relation (claim 33, read off its code) with the lines it stands on put in - what the waiting makes = \sigma·\paren{1 - \omega}·\rho, with \sigma = 1, \omega = 1 put in - is this line, by algebra
- step 22 (the rate the whole of it expands at), checked: the inference's relation (claim 34, read off its code) with the lines it stands on put in - the space line nets = \nu·n_{f}·\paren{1 - \rho} + \sigma·\paren{1 - \omega}·\rho - \sigma·F·\rho^{2}; the world's matter grows = 2·\sigma·F·\bar{n}^{2}, with \sigma = 1, F = \frac{1}{2}, \nu = 1, \omega = 1, \bar{n} = 0 put in - is this line, by algebra
- step 23 (the acceleration the expansion builds), checked: the inference's relation (claim 35, read off its code) with the lines it stands on put in - H = \frac{\paren{\nu·n_{f}·\paren{1 - \rho} + \sigma·\paren{1 - \omega}·\rho + 2·\sigma·F·\bar{n}^{2} + 2·\sigma·F·\paren{1 - \rho}·\rho^{2} - \sigma·F·\rho^{2}}}{D}; \bar{c} = 1, with \sigma = 1, F = \frac{1}{2}, \nu = 1, \omega = 1, \bar{n} = 0 put in - is this line, by algebra
- step 24 (the scale against the expansion), checked: the inference's relation (claim 36, read off its code) with the lines it stands on put in - a_{0} = \frac{2·\omega·\sigma·F·\paren{1 - \rho}·\rho^{2}}{\paren{n_{f} + 1}·D}; cH = \frac{\paren{\nu·n_{f}·\paren{1 - \rho} + \sigma·\paren{1 - \omega}·\rho + 2·\sigma·F·\bar{n}^{2} + 2·\sigma·F·\paren{1 - \rho}·\rho^{2} - \sigma·F·\rho^{2}}}{D}, with \omega = 1, \sigma = 1, F = \frac{1}{2}, \nu = 1, \bar{n} = 0 put in - is this line, by algebra
- settled number 27 (isotropy leaves no mean heading), NOT checked: the inference 'isotropy leaves no mean heading' reached it from what the store held in its own code (Inferences.ray, Prove.ray): the relation it applies to them is not recorded with the step, so there is nothing to check the line against - it is stated as the prover wrote it
- answer (the answer), checked: claim 24 with the settled numbers put in, with \omega = 1, \sigma = 1, F = \frac{1}{2}, \nu = 1, \bar{n} = 0 put in
-/

namespace OrbitMines.Physics.Proofs.G.«gravity.coincidence»

/-- What the prover takes from the rules: the premises, read off the program BY DESIGN - a rule's own body, the
continuous model the rules were read into, the lattice, a count. None is believed or measured; each is already in the
theory's .ray. -/
structure Premises («the continuous model» «\sigma» «F» «n» «DEG» «\nu» «\rho» «l.\bar{m}» «\omega» «\varepsilon» «H_{\Lambda}» «D» «the folds line nets» «n_{f}» «what a body feels» «\sum\hat{d}» «S» «what is taken» «what is made» «\rho_{\infty}» «\lambda» «what a body puts into the medium» «\bar{m}_{x}» «l.DEG» «\beta» «A» «\bar{R}» «r» «\bar{c}» «v» «a_{0}» «the space line nets» «what the waiting makes» «the rate space is made» «what bodies' rays grow where they meet» «\bar{n}» «the world's matter grows» «H» «cH» «\frac{a_{0}}{cH}» : ℝ) : Prop where
  /-- step 1 (the reading): the continuous model = DEG·\nu·\paren{1 - \rho} + l.\bar{m}·\omega - 2·\sigma·F·n^{2} - the rules read as a line (Reading.ray): the root every derivation passes through -/
  «the reading: the continuous model» : «the continuous model» = (((-1 : ℝ) * (2 : ℝ) * «\sigma» * «F» * («n» ^ 2)) + («DEG» * «\nu» * ((1 : ℝ) + ((-1 : ℝ) * «\rho»))) + ((1 : ℝ) * «l.\bar{m}» * «\omega»))
  /-- step 2 (read off the continuous model): \varepsilon = 2·\sigma·F·\paren{1 - \rho}·\rho^{2} - read off the continuous model - a term of the line the rules were read into, or how the line is made -/
  «read off the continuous model: \varepsilon» : «\varepsilon» = ((2 : ℝ) * «\sigma» * «F» * (((-1 : ℝ) * «\rho») + (1 : ℝ)) * («\rho» ^ 2))
  /-- step 4 (read off the continuous model): the folds line nets = \sigma·F·\rho^{2} - \nu·n_{f}·\paren{1 - \rho} - read off the continuous model - a term of the line the rules were read into, or how the line is made -/
  «read off the continuous model: the folds line nets» : «the folds line nets» = ((«\sigma» * «F» * («\rho» ^ 2)) + ((-1 : ℝ) * «\nu» * «n_{f}» * (((-1 : ℝ) * «\rho») + (1 : ℝ))))
  /-- step 5 (EMISSION): what a body feels = \sum\hat{d} - the rule EMISSION, read off its own body -/
  «EMISSION: what a body feels» : «what a body feels» = «\sum\hat{d}»
  /-- step 6 (read off the continuous model): S = 0 - read off the continuous model - a term of the line the rules were read into, or how the line is made -/
  «read off the continuous model: S» : «S» = (0 : ℝ)
  /-- step 7 (read off the continuous model): what is taken = \sigma·F·\rho^{2} - read off the continuous model - a term of the line the rules were read into, or how the line is made -/
  «read off the continuous model: what is taken» : «what is taken» = («\sigma» * «F» * («\rho» ^ 2))
  /-- step 8 (read off the continuous model): what is made = \nu·\paren{1 - \rho} - read off the continuous model - a term of the line the rules were read into, or how the line is made -/
  «read off the continuous model: what is made» : «what is made» = («\nu» * (((-1 : ℝ) * «\rho») + (1 : ℝ)))
  /-- step 13 (read off the continuous model): \bar{c} = 1 - read off the continuous model - a term of the line the rules were read into, or how the line is made -/
  «read off the continuous model: \bar{c}» : «\bar{c}» = (1 : ℝ)
  /-- step 16 (read off the continuous model): the space line nets = \nu·n_{f}·\paren{1 - \rho} + \sigma·\paren{1 - \omega}·\rho - \sigma·F·\rho^{2} - read off the continuous model - a term of the line the rules were read into, or how the line is made -/
  «read off the continuous model: the space line nets» : «the space line nets» = (((-1 : ℝ) * «\sigma» * «F» * («\rho» ^ 2)) + («\nu» * «n_{f}» * (((-1 : ℝ) * «\rho») + (1 : ℝ))) + («\sigma» * (((-1 : ℝ) * «\omega») + (1 : ℝ)) * «\rho»))
  /-- step 17 (read off the continuous model): what the waiting makes = \sigma·\paren{1 - \omega}·\rho - read off the continuous model - a term of the line the rules were read into, or how the line is made -/
  «read off the continuous model: what the waiting makes» : «what the waiting makes» = («\sigma» * (((-1 : ℝ) * «\omega») + (1 : ℝ)) * «\rho»)
  /-- step 19 (read off the continuous model): what bodies' rays grow where they meet = 2 - read off the continuous model - a term of the line the rules were read into, or how the line is made -/
  «read off the continuous model: what bodies' rays grow where they meet» : «what bodies' rays grow where they meet» = (2 : ℝ)
  /-- step 20 (read off the continuous model): \bar{n} = 0 - read off the continuous model - a term of the line the rules were read into, or how the line is made -/
  «read off the continuous model: \bar{n}» : «\bar{n}» = (0 : ℝ)
  /-- step 21 (ANNIHILATION): the world's matter grows = 2·\sigma·F·\bar{n}^{2} - the rule ANNIHILATION, read off its own body -/
  «ANNIHILATION: the world's matter grows» : «the world's matter grows» = ((2 : ℝ) * «\sigma» * «F» * («\bar{n}» ^ 2))
  /-- the relation its inference applies (the inference 'one over the rate it is removed at'): \lambda = \frac{\rho}{what is taken} - read off its own code (Inferences.ray, or the method of Prove.ray that builds the equation's chain): run on the store as it stood when step 10 arrived, with the lines it stands on as their names, it concludes this - the relation it applies, taken from the program as every premise is -/
  «the inference 'one over the rate it is removed at': \lambda» : «\lambda» = ((«what is taken»)⁻¹ * «\rho»)
  /-- a settled number (read off the continuous model): \sigma = 1 - read off the continuous model - a term of the line the rules were read into, or how the line is made -/
  «read off the continuous model: \sigma» : «\sigma» = (1 : ℝ)
  /-- the relation its inference applies (the inference 'a body's own cells thin one another'): what a body puts into the medium = l.choose\paren{\bar{m}_{x·l.DEG·\paren{1 - \beta}}}·\omega·A·\lambda·\paren{1 - \paren{1 - \frac{1}{\lambda}}^{\bar{R}}} - read off its own code (Inferences.ray, or the method of Prove.ray that builds the equation's chain): run on the store as it stood when step 11 arrived, with the lines it stands on as their names, it concludes this - the relation it applies, taken from the program as every premise is -/
  «the inference 'a body's own cells thin one another': what a body puts into the medium» : «what a body puts into the medium» = ((Fn "l.choose" («\bar{m}_{x}» * «l.DEG» * (((-1 : ℝ) * «\beta») + (1 : ℝ)))) * «\omega» * «A» * «\lambda» * (((-1 : ℝ) * ((((-1 : ℝ) * («\lambda»)⁻¹) + (1 : ℝ)) ^ «\bar{R}»)) + (1 : ℝ)))
  /-- a settled number (read off the continuous model): \omega = 1 - read off the continuous model - a term of the line the rules were read into, or how the line is made -/
  «read off the continuous model: \omega» : «\omega» = (1 : ℝ)
  /-- the relation its inference applies (the inference 'how fast a carrier goes, which is the share of its step that was straight'): v = \frac{\bar{c}·\omega}{n_{f} + 1} - read off its own code (Inferences.ray, or the method of Prove.ray that builds the equation's chain): run on the store as it stood when step 14 arrived, with the lines it stands on as their names, it concludes this - the relation it applies, taken from the program as every premise is -/
  «the inference 'how fast a carrier goes, which is the share of its step that was straight': v» : «v» = («\bar{c}» * «\omega» * ((«n_{f}» + (1 : ℝ)))⁻¹)
  /-- a settled number (read off the continuous model): \nu = 1 - read off the continuous model - a term of the line the rules were read into, or how the line is made -/
  «read off the continuous model: \nu» : «\nu» = (1 : ℝ)
  /-- the relation its inference applies (the inference 'the phase between the two pulses, which the body's own acceleration keeps from cancelling'): a_{0} = v·H_{\Lambda} - read off its own code (Inferences.ray, or the method of Prove.ray that builds the equation's chain): run on the store as it stood when step 15 arrived, with the lines it stands on as their names, it concludes this - the relation it applies, taken from the program as every premise is -/
  «the inference 'the phase between the two pulses, which the body's own acceleration keeps from cancelling': a_{0}» : «a_{0}» = («v» * «H_{\Lambda}»)
  /-- the relation its inference applies (the inference 'the room the line does not supply, which the waiting has to make'): the rate space is made = what the waiting makes - read off its own code (Inferences.ray, or the method of Prove.ray that builds the equation's chain): run on the store as it stood when step 18 arrived, with the lines it stands on as their names, it concludes this - the relation it applies, taken from the program as every premise is -/
  «the inference 'the room the line does not supply, which the waiting has to make': the rate space is made» : «the rate space is made» = «what the waiting makes»
  /-- the relation its inference applies (the inference 'the rate the whole of it expands at'): H = \frac{\paren{the space line nets + the world's matter grows + 2·\sigma·F·\paren{1 - \rho}·\rho^{2}}}{D} - read off its own code (Inferences.ray, or the method of Prove.ray that builds the equation's chain): run on the store as it stood when step 22 arrived, with the lines it stands on as their names, it concludes this - the relation it applies, taken from the program as every premise is -/
  «the inference 'the rate the whole of it expands at': H» : «H» = ((«the space line nets» + «the world's matter grows» + ((2 : ℝ) * «\sigma» * «F» * (((-1 : ℝ) * «\rho») + (1 : ℝ)) * («\rho» ^ 2))) * («D»)⁻¹)
  /-- the relation its inference applies (the inference 'the acceleration the expansion builds'): cH = \bar{c}·H - read off its own code (Inferences.ray, or the method of Prove.ray that builds the equation's chain): run on the store as it stood when step 23 arrived, with the lines it stands on as their names, it concludes this - the relation it applies, taken from the program as every premise is -/
  «the inference 'the acceleration the expansion builds': cH» : «cH» = («\bar{c}» * «H»)
  /-- the relation its inference applies (the inference 'the scale against the expansion'): \frac{a_{0}}{cH} = \frac{a_{0}}{cH} - read off its own code (Inferences.ray, or the method of Prove.ray that builds the equation's chain): run on the store as it stood when step 24 arrived, with the lines it stands on as their names, it concludes this - the relation it applies, taken from the program as every premise is -/
  «the inference 'the scale against the expansion': \frac{a_{0}}{cH}» : «\frac{a_{0}}{cH}» = («a_{0}» * («cH»)⁻¹)

/-- The steps Lean does not check, each with the reason. They are hypotheses of every theorem below - stated, never proven. -/
structure Unchecked («the continuous model» «\sigma» «F» «n» «DEG» «\nu» «\rho» «l.\bar{m}» «\omega» «\varepsilon» «H_{\Lambda}» «D» «the folds line nets» «n_{f}» «what a body feels» «\sum\hat{d}» «S» «what is taken» «what is made» «\rho_{\infty}» «\lambda» «what a body puts into the medium» «\bar{m}_{x}» «l.DEG» «\beta» «A» «\bar{R}» «r» «\bar{c}» «v» «a_{0}» «the space line nets» «what the waiting makes» «the rate space is made» «what bodies' rays grow where they meet» «\bar{n}» «the world's matter grows» «H» «cH» «\frac{a_{0}}{cH}» : ℝ) : Prop where
  /-- step 3 (the rate the empty vacuum expands at): H_{\Lambda} = \frac{2·\sigma·F·\paren{1 - \rho}·\rho^{2}}{D} - NOT CHECKED: the inference 'the rate the empty vacuum expands at' (Inferences.ray) was run again with the lines it cites standing as their names, to read the relation it applies off its code: it concluded nothing for this line (it looks inside a value, or a guard went the other way); and with every line of the store standing as its name: it concluded nothing for this line (it looks inside a value, or a guard went the other way). So there is no relation to check the line against, and it is stated as the prover wrote it -/
  unchecked_gravity_coincidence_3 : «H_{\Lambda}» = ((2 : ℝ) * «\sigma» * «F» * (((-1 : ℝ) * «\rho») + (1 : ℝ)) * («\rho» ^ 2) * («D»)⁻¹)
  /-- step 9 (where the making pays for the taking): \rho_{\infty} = \text{the } \rho \text{ where } DEG·\paren{1 - \rho} - 2·F·\rho^{2} = 0 - NOT CHECKED: the inference 'where the making pays for the taking' (Inferences.ray) was run again with the lines it cites standing as their names, to read the relation it applies off its code: its relation holds a root in the name the lines it cites are written in, and they are put in under the root by name - which substitution in a prover does not do; and with every line of the store standing as its name: its relation holds a root in the name the lines it cites are written in, and they are put in under the root by name - which substitution in a prover does not do. So there is no relation to check the line against, and it is stated as the prover wrote it -/
  unchecked_gravity_coincidence_9 : «\rho_{\infty}» = (RootOf (fun («\rho» : ℝ) => ((«DEG» * (((-1 : ℝ) * «\rho») + (1 : ℝ))) + ((-2 : ℝ) * «F» * («\rho» ^ 2)))))
  /-- step 12 (what a place has swallowed, where the folding pays for the handing back): n_{f} = \frac{l.choose\paren{\bar{m}_{x·l.DEG·\paren{1 - \beta}}}·\omega·A·\paren{1 - \paren{1 - \sigma·F·\rho}^{\bar{R}}}·r^{-\paren{D - 2}}}{\sigma·F·\rho} - \frac{\sigma·F·\rho^{2}}{\nu·\rho - \nu} - NOT CHECKED: the inference 'what a place has swallowed, where the folding pays for the handing back' (Inferences.ray) was run again with the lines it cites standing as their names, to read the relation it applies off its code: it concluded nothing for this line (it looks inside a value, or a guard went the other way); and with every line of the store standing as its name: it concluded nothing for this line (it looks inside a value, or a guard went the other way). So there is no relation to check the line against, and it is stated as the prover wrote it -/
  unchecked_gravity_coincidence_12 : «n_{f}» = (((-1 : ℝ) * «\sigma» * «F» * («\rho» ^ 2) * (((«\nu» * «\rho») + ((-1 : ℝ) * «\nu»)))⁻¹) + ((Fn "l.choose" («\bar{m}_{x}» * «l.DEG» * (((-1 : ℝ) * «\beta») + (1 : ℝ)))) * «\omega» * «A» * («\sigma»)⁻¹ * («F»)⁻¹ * («\rho»)⁻¹ * (((-1 : ℝ) * ((((-1 : ℝ) * «\sigma» * «F» * «\rho») + (1 : ℝ)) ^ «\bar{R}»)) + (1 : ℝ)) * («r» ^ ((-1 : ℝ) * («D» + (-2 : ℝ))))))
  /-- a settled number (isotropy leaves no mean heading): F = \frac{1}{2} - NOT CHECKED: the inference 'isotropy leaves no mean heading' reached it from what the store held in its own code (Inferences.ray, Prove.ray): the relation it applies to them is not recorded with the step, so there is nothing to check the line against - it is stated as the prover wrote it -/
  unchecked_gravity_coincidence_27 : «F» = ((1 : ℝ) * ((2 : ℝ))⁻¹)

/-- Where the lines are defined: what the prover divides by. Its algebra cancels across these, so they are taken to be nonzero. -/
structure Defined («the continuous model» «\sigma» «F» «n» «DEG» «\nu» «\rho» «l.\bar{m}» «\omega» «\varepsilon» «H_{\Lambda}» «D» «the folds line nets» «n_{f}» «what a body feels» «\sum\hat{d}» «S» «what is taken» «what is made» «\rho_{\infty}» «\lambda» «what a body puts into the medium» «\bar{m}_{x}» «l.DEG» «\beta» «A» «\bar{R}» «r» «\bar{c}» «v» «a_{0}» «the space line nets» «what the waiting makes» «the rate space is made» «what bodies' rays grow where they meet» «\bar{n}» «the world's matter grows» «H» «cH» «\frac{a_{0}}{cH}» : ℝ) : Prop where
  /-- D is not nought -/
  ne_0 : «D» ≠ 0
  /-- \sigma is not nought -/
  ne_1 : «\sigma» ≠ 0
  /-- F is not nought -/
  ne_2 : «F» ≠ 0
  /-- \rho is not nought -/
  ne_3 : «\rho» ≠ 0
  /-- \nu·\rho - \nu is not nought -/
  ne_4 : ((«\nu» * «\rho») + ((-1 : ℝ) * «\nu»)) ≠ 0
  /-- n_{f} + 1 is not nought -/
  ne_5 : («n_{f}» + (1 : ℝ)) ≠ 0
  /-- \nu·n_{f}·\paren{1 - \rho} + \sigma·\paren{1 - \omega}·\rho + 2·\sigma·F·\bar{n}^{2} + 2·\sigma·F·\paren{1 - \rho}·\rho^{2} - \sigma·F·\rho^{2} is not nought -/
  ne_6 : (((-1 : ℝ) * «\sigma» * «F» * («\rho» ^ 2)) + («\nu» * «n_{f}» * (((-1 : ℝ) * «\rho») + (1 : ℝ))) + («\sigma» * (((-1 : ℝ) * «\omega») + (1 : ℝ)) * «\rho») + ((2 : ℝ) * «\sigma» * «F» * («\bar{n}» ^ 2)) + ((2 : ℝ) * «\sigma» * «F» * (((-1 : ℝ) * «\rho») + (1 : ℝ)) * («\rho» ^ 2))) ≠ 0
  /-- what is taken is not nought -/
  ne_7 : «what is taken» ≠ 0
  /-- \lambda is not nought -/
  ne_8 : «\lambda» ≠ 0
  /-- cH is not nought -/
  ne_9 : «cH» ≠ 0
  /-- n_{f}·\paren{1 - \rho} + \paren{1 - \rho}·\rho^{2} - \frac{\rho^{2}}{2} is not nought -/
  ne_10 : ((((-5 : ℝ) / 10) * («\rho» ^ 2)) + («n_{f}» * (((-1 : ℝ) * «\rho») + (1 : ℝ))) + ((((-1 : ℝ) * «\rho») + (1 : ℝ)) * («\rho» ^ 2))) ≠ 0
  /-- 1 - \sigma·F·\rho is positive: it is raised to a real power -/
  pos_0 : 0 < (((-1 : ℝ) * «\sigma» * «F» * «\rho») + (1 : ℝ))
  /-- r is positive: it is raised to a real power -/
  pos_1 : 0 < «r»
  /-- 1 - \frac{1}{\lambda} is positive: it is raised to a real power -/
  pos_2 : 0 < (((-1 : ℝ) * («\lambda»)⁻¹) + (1 : ℝ))

/-- step 10 (one over the rate it is removed at): \lambda = \frac{1}{\sigma·F·\rho} - CHECKED: the inference's relation (claim 25, read off its code) with the lines it stands on put in - what is taken = \sigma·F·\rho^{2}, with \sigma = 1, F = \frac{1}{2} put in - is this line, by algebra -/
theorem check_10 («the continuous model» «\sigma» «F» «n» «DEG» «\nu» «\rho» «l.\bar{m}» «\omega» «\varepsilon» «H_{\Lambda}» «D» «the folds line nets» «n_{f}» «what a body feels» «\sum\hat{d}» «S» «what is taken» «what is made» «\rho_{\infty}» «\lambda» «what a body puts into the medium» «\bar{m}_{x}» «l.DEG» «\beta» «A» «\bar{R}» «r» «\bar{c}» «v» «a_{0}» «the space line nets» «what the waiting makes» «the rate space is made» «what bodies' rays grow where they meet» «\bar{n}» «the world's matter grows» «H» «cH» «\frac{a_{0}}{cH}» : ℝ)
    (p : Premises «the continuous model» «\sigma» «F» «n» «DEG» «\nu» «\rho» «l.\bar{m}» «\omega» «\varepsilon» «H_{\Lambda}» «D» «the folds line nets» «n_{f}» «what a body feels» «\sum\hat{d}» «S» «what is taken» «what is made» «\rho_{\infty}» «\lambda» «what a body puts into the medium» «\bar{m}_{x}» «l.DEG» «\beta» «A» «\bar{R}» «r» «\bar{c}» «v» «a_{0}» «the space line nets» «what the waiting makes» «the rate space is made» «what bodies' rays grow where they meet» «\bar{n}» «the world's matter grows» «H» «cH» «\frac{a_{0}}{cH}») (u : Unchecked «the continuous model» «\sigma» «F» «n» «DEG» «\nu» «\rho» «l.\bar{m}» «\omega» «\varepsilon» «H_{\Lambda}» «D» «the folds line nets» «n_{f}» «what a body feels» «\sum\hat{d}» «S» «what is taken» «what is made» «\rho_{\infty}» «\lambda» «what a body puts into the medium» «\bar{m}_{x}» «l.DEG» «\beta» «A» «\bar{R}» «r» «\bar{c}» «v» «a_{0}» «the space line nets» «what the waiting makes» «the rate space is made» «what bodies' rays grow where they meet» «\bar{n}» «the world's matter grows» «H» «cH» «\frac{a_{0}}{cH}») (w : Defined «the continuous model» «\sigma» «F» «n» «DEG» «\nu» «\rho» «l.\bar{m}» «\omega» «\varepsilon» «H_{\Lambda}» «D» «the folds line nets» «n_{f}» «what a body feels» «\sum\hat{d}» «S» «what is taken» «what is made» «\rho_{\infty}» «\lambda» «what a body puts into the medium» «\bar{m}_{x}» «l.DEG» «\beta» «A» «\bar{R}» «r» «\bar{c}» «v» «a_{0}» «the space line nets» «what the waiting makes» «the rate space is made» «what bodies' rays grow where they meet» «\bar{n}» «the world's matter grows» «H» «cH» «\frac{a_{0}}{cH}») :
    «\lambda» = ((«\sigma»)⁻¹ * («F»)⁻¹ * («\rho»)⁻¹) := by
  have h25 := p.«the inference 'one over the rate it is removed at': \lambda»
  have h7 := p.«read off the continuous model: what is taken»
  have h26 := p.«read off the continuous model: \sigma»
  have h27 := u.unchecked_gravity_coincidence_27
  have w0 := w.ne_0
  have w1 := w.ne_1
  have w2 := w.ne_2
  have w3 := w.ne_3
  have w4 := w.ne_4
  have w5 := w.ne_5
  have w6 := w.ne_6
  have w7 := w.ne_7
  have w8 := w.ne_8
  have w9 := w.ne_9
  have w10 := w.ne_10
  have p0 := w.pos_0
  have r0 := fun (y : ℝ) => Real.rpow_neg (le_of_lt w.pos_0) y
  have q0 := fun (y : ℝ) => (Real.rpow_pos_of_pos w.pos_0 y).ne'
  have p1 := w.pos_1
  have r1 := fun (y : ℝ) => Real.rpow_neg (le_of_lt w.pos_1) y
  have q1 := fun (y : ℝ) => (Real.rpow_pos_of_pos w.pos_1 y).ne'
  have p2 := w.pos_2
  have r2 := fun (y : ℝ) => Real.rpow_neg (le_of_lt w.pos_2) y
  have q2 := fun (y : ℝ) => (Real.rpow_pos_of_pos w.pos_2 y).ne'
  subst_vars
  try simp only [neg_one_mul, r0, r1, r2] at *
  check_algebra

/-- step 11 (a body's own cells thin one another): what a body puts into the medium = \frac{l.choose\paren{\bar{m}_{x·l.DEG·\paren{1 - \beta}}}·\omega·A·\paren{1 - \paren{1 - \sigma·F·\rho}^{\bar{R}}}}{\sigma·F·\rho} - CHECKED: the inference's relation (claim 28, read off its code) with the lines it stands on put in - \lambda = \frac{1}{\sigma·F·\rho}, with \omega = 1, \sigma = 1, F = \frac{1}{2} put in - is this line, by algebra -/
theorem check_11 («the continuous model» «\sigma» «F» «n» «DEG» «\nu» «\rho» «l.\bar{m}» «\omega» «\varepsilon» «H_{\Lambda}» «D» «the folds line nets» «n_{f}» «what a body feels» «\sum\hat{d}» «S» «what is taken» «what is made» «\rho_{\infty}» «\lambda» «what a body puts into the medium» «\bar{m}_{x}» «l.DEG» «\beta» «A» «\bar{R}» «r» «\bar{c}» «v» «a_{0}» «the space line nets» «what the waiting makes» «the rate space is made» «what bodies' rays grow where they meet» «\bar{n}» «the world's matter grows» «H» «cH» «\frac{a_{0}}{cH}» : ℝ)
    (p : Premises «the continuous model» «\sigma» «F» «n» «DEG» «\nu» «\rho» «l.\bar{m}» «\omega» «\varepsilon» «H_{\Lambda}» «D» «the folds line nets» «n_{f}» «what a body feels» «\sum\hat{d}» «S» «what is taken» «what is made» «\rho_{\infty}» «\lambda» «what a body puts into the medium» «\bar{m}_{x}» «l.DEG» «\beta» «A» «\bar{R}» «r» «\bar{c}» «v» «a_{0}» «the space line nets» «what the waiting makes» «the rate space is made» «what bodies' rays grow where they meet» «\bar{n}» «the world's matter grows» «H» «cH» «\frac{a_{0}}{cH}») (u : Unchecked «the continuous model» «\sigma» «F» «n» «DEG» «\nu» «\rho» «l.\bar{m}» «\omega» «\varepsilon» «H_{\Lambda}» «D» «the folds line nets» «n_{f}» «what a body feels» «\sum\hat{d}» «S» «what is taken» «what is made» «\rho_{\infty}» «\lambda» «what a body puts into the medium» «\bar{m}_{x}» «l.DEG» «\beta» «A» «\bar{R}» «r» «\bar{c}» «v» «a_{0}» «the space line nets» «what the waiting makes» «the rate space is made» «what bodies' rays grow where they meet» «\bar{n}» «the world's matter grows» «H» «cH» «\frac{a_{0}}{cH}») (w : Defined «the continuous model» «\sigma» «F» «n» «DEG» «\nu» «\rho» «l.\bar{m}» «\omega» «\varepsilon» «H_{\Lambda}» «D» «the folds line nets» «n_{f}» «what a body feels» «\sum\hat{d}» «S» «what is taken» «what is made» «\rho_{\infty}» «\lambda» «what a body puts into the medium» «\bar{m}_{x}» «l.DEG» «\beta» «A» «\bar{R}» «r» «\bar{c}» «v» «a_{0}» «the space line nets» «what the waiting makes» «the rate space is made» «what bodies' rays grow where they meet» «\bar{n}» «the world's matter grows» «H» «cH» «\frac{a_{0}}{cH}») :
    «what a body puts into the medium» = ((Fn "l.choose" («\bar{m}_{x}» * «l.DEG» * (((-1 : ℝ) * «\beta») + (1 : ℝ)))) * «\omega» * «A» * («\sigma»)⁻¹ * («F»)⁻¹ * («\rho»)⁻¹ * (((-1 : ℝ) * ((((-1 : ℝ) * «\sigma» * «F» * «\rho») + (1 : ℝ)) ^ «\bar{R}»)) + (1 : ℝ))) := by
  have h28 := p.«the inference 'a body's own cells thin one another': what a body puts into the medium»
  have h10 := check_10 «the continuous model» «\sigma» «F» «n» «DEG» «\nu» «\rho» «l.\bar{m}» «\omega» «\varepsilon» «H_{\Lambda}» «D» «the folds line nets» «n_{f}» «what a body feels» «\sum\hat{d}» «S» «what is taken» «what is made» «\rho_{\infty}» «\lambda» «what a body puts into the medium» «\bar{m}_{x}» «l.DEG» «\beta» «A» «\bar{R}» «r» «\bar{c}» «v» «a_{0}» «the space line nets» «what the waiting makes» «the rate space is made» «what bodies' rays grow where they meet» «\bar{n}» «the world's matter grows» «H» «cH» «\frac{a_{0}}{cH}» p u w
  have h29 := p.«read off the continuous model: \omega»
  have h26 := p.«read off the continuous model: \sigma»
  have h27 := u.unchecked_gravity_coincidence_27
  have w0 := w.ne_0
  have w1 := w.ne_1
  have w2 := w.ne_2
  have w3 := w.ne_3
  have w4 := w.ne_4
  have w5 := w.ne_5
  have w6 := w.ne_6
  have w7 := w.ne_7
  have w8 := w.ne_8
  have w9 := w.ne_9
  have w10 := w.ne_10
  have p0 := w.pos_0
  have r0 := fun (y : ℝ) => Real.rpow_neg (le_of_lt w.pos_0) y
  have q0 := fun (y : ℝ) => (Real.rpow_pos_of_pos w.pos_0 y).ne'
  have p1 := w.pos_1
  have r1 := fun (y : ℝ) => Real.rpow_neg (le_of_lt w.pos_1) y
  have q1 := fun (y : ℝ) => (Real.rpow_pos_of_pos w.pos_1 y).ne'
  have p2 := w.pos_2
  have r2 := fun (y : ℝ) => Real.rpow_neg (le_of_lt w.pos_2) y
  have q2 := fun (y : ℝ) => (Real.rpow_pos_of_pos w.pos_2 y).ne'
  subst_vars
  try simp only [neg_one_mul, r0, r1, r2] at *
  check_algebra

/-- step 14 (how fast a carrier goes, which is the share of its step that was straight): v = \frac{\omega}{n_{f} + 1} - CHECKED: the inference's relation (claim 30, read off its code) with the lines it stands on put in - n_{f} = \frac{l.choose\paren{\bar{m}_{x·l.DEG·\paren{1 - \beta}}}·\omega·A·\paren{1 - \paren{1 - \sigma·F·\rho}^{\bar{R}}}·r^{-\paren{D - 2}}}{\sigma·F·\rho} - \frac{\sigma·F·\rho^{2}}{\nu·\rho - \nu}; \bar{c} = 1, with \omega = 1, \sigma = 1, F = \frac{1}{2}, \nu = 1 put in - is this line, by algebra -/
theorem check_14 («the continuous model» «\sigma» «F» «n» «DEG» «\nu» «\rho» «l.\bar{m}» «\omega» «\varepsilon» «H_{\Lambda}» «D» «the folds line nets» «n_{f}» «what a body feels» «\sum\hat{d}» «S» «what is taken» «what is made» «\rho_{\infty}» «\lambda» «what a body puts into the medium» «\bar{m}_{x}» «l.DEG» «\beta» «A» «\bar{R}» «r» «\bar{c}» «v» «a_{0}» «the space line nets» «what the waiting makes» «the rate space is made» «what bodies' rays grow where they meet» «\bar{n}» «the world's matter grows» «H» «cH» «\frac{a_{0}}{cH}» : ℝ)
    (p : Premises «the continuous model» «\sigma» «F» «n» «DEG» «\nu» «\rho» «l.\bar{m}» «\omega» «\varepsilon» «H_{\Lambda}» «D» «the folds line nets» «n_{f}» «what a body feels» «\sum\hat{d}» «S» «what is taken» «what is made» «\rho_{\infty}» «\lambda» «what a body puts into the medium» «\bar{m}_{x}» «l.DEG» «\beta» «A» «\bar{R}» «r» «\bar{c}» «v» «a_{0}» «the space line nets» «what the waiting makes» «the rate space is made» «what bodies' rays grow where they meet» «\bar{n}» «the world's matter grows» «H» «cH» «\frac{a_{0}}{cH}») (u : Unchecked «the continuous model» «\sigma» «F» «n» «DEG» «\nu» «\rho» «l.\bar{m}» «\omega» «\varepsilon» «H_{\Lambda}» «D» «the folds line nets» «n_{f}» «what a body feels» «\sum\hat{d}» «S» «what is taken» «what is made» «\rho_{\infty}» «\lambda» «what a body puts into the medium» «\bar{m}_{x}» «l.DEG» «\beta» «A» «\bar{R}» «r» «\bar{c}» «v» «a_{0}» «the space line nets» «what the waiting makes» «the rate space is made» «what bodies' rays grow where they meet» «\bar{n}» «the world's matter grows» «H» «cH» «\frac{a_{0}}{cH}») (w : Defined «the continuous model» «\sigma» «F» «n» «DEG» «\nu» «\rho» «l.\bar{m}» «\omega» «\varepsilon» «H_{\Lambda}» «D» «the folds line nets» «n_{f}» «what a body feels» «\sum\hat{d}» «S» «what is taken» «what is made» «\rho_{\infty}» «\lambda» «what a body puts into the medium» «\bar{m}_{x}» «l.DEG» «\beta» «A» «\bar{R}» «r» «\bar{c}» «v» «a_{0}» «the space line nets» «what the waiting makes» «the rate space is made» «what bodies' rays grow where they meet» «\bar{n}» «the world's matter grows» «H» «cH» «\frac{a_{0}}{cH}») :
    «v» = («\omega» * ((«n_{f}» + (1 : ℝ)))⁻¹) := by
  have h30 := p.«the inference 'how fast a carrier goes, which is the share of its step that was straight': v»
  have h12 := u.unchecked_gravity_coincidence_12
  have h13 := p.«read off the continuous model: \bar{c}»
  have h29 := p.«read off the continuous model: \omega»
  have h26 := p.«read off the continuous model: \sigma»
  have h27 := u.unchecked_gravity_coincidence_27
  have h31 := p.«read off the continuous model: \nu»
  have w0 := w.ne_0
  have w1 := w.ne_1
  have w2 := w.ne_2
  have w3 := w.ne_3
  have w4 := w.ne_4
  have w5 := w.ne_5
  have w6 := w.ne_6
  have w7 := w.ne_7
  have w8 := w.ne_8
  have w9 := w.ne_9
  have w10 := w.ne_10
  have p0 := w.pos_0
  have r0 := fun (y : ℝ) => Real.rpow_neg (le_of_lt w.pos_0) y
  have q0 := fun (y : ℝ) => (Real.rpow_pos_of_pos w.pos_0 y).ne'
  have p1 := w.pos_1
  have r1 := fun (y : ℝ) => Real.rpow_neg (le_of_lt w.pos_1) y
  have q1 := fun (y : ℝ) => (Real.rpow_pos_of_pos w.pos_1 y).ne'
  have p2 := w.pos_2
  have r2 := fun (y : ℝ) => Real.rpow_neg (le_of_lt w.pos_2) y
  have q2 := fun (y : ℝ) => (Real.rpow_pos_of_pos w.pos_2 y).ne'
  subst_vars
  try simp only [neg_one_mul, r0, r1, r2] at *
  check_algebra

/-- step 15 (the phase between the two pulses, which the body's own acceleration keeps from cancelling): a_{0} = \frac{2·\omega·\sigma·F·\paren{1 - \rho}·\rho^{2}}{\paren{n_{f} + 1}·D} - CHECKED: the inference's relation (claim 32, read off its code) with the lines it stands on put in - H_{\Lambda} = \frac{2·\sigma·F·\paren{1 - \rho}·\rho^{2}}{D}; v = \frac{\omega}{n_{f} + 1}, with \omega = 1, \sigma = 1, F = \frac{1}{2} put in - is this line, by algebra -/
theorem check_15 («the continuous model» «\sigma» «F» «n» «DEG» «\nu» «\rho» «l.\bar{m}» «\omega» «\varepsilon» «H_{\Lambda}» «D» «the folds line nets» «n_{f}» «what a body feels» «\sum\hat{d}» «S» «what is taken» «what is made» «\rho_{\infty}» «\lambda» «what a body puts into the medium» «\bar{m}_{x}» «l.DEG» «\beta» «A» «\bar{R}» «r» «\bar{c}» «v» «a_{0}» «the space line nets» «what the waiting makes» «the rate space is made» «what bodies' rays grow where they meet» «\bar{n}» «the world's matter grows» «H» «cH» «\frac{a_{0}}{cH}» : ℝ)
    (p : Premises «the continuous model» «\sigma» «F» «n» «DEG» «\nu» «\rho» «l.\bar{m}» «\omega» «\varepsilon» «H_{\Lambda}» «D» «the folds line nets» «n_{f}» «what a body feels» «\sum\hat{d}» «S» «what is taken» «what is made» «\rho_{\infty}» «\lambda» «what a body puts into the medium» «\bar{m}_{x}» «l.DEG» «\beta» «A» «\bar{R}» «r» «\bar{c}» «v» «a_{0}» «the space line nets» «what the waiting makes» «the rate space is made» «what bodies' rays grow where they meet» «\bar{n}» «the world's matter grows» «H» «cH» «\frac{a_{0}}{cH}») (u : Unchecked «the continuous model» «\sigma» «F» «n» «DEG» «\nu» «\rho» «l.\bar{m}» «\omega» «\varepsilon» «H_{\Lambda}» «D» «the folds line nets» «n_{f}» «what a body feels» «\sum\hat{d}» «S» «what is taken» «what is made» «\rho_{\infty}» «\lambda» «what a body puts into the medium» «\bar{m}_{x}» «l.DEG» «\beta» «A» «\bar{R}» «r» «\bar{c}» «v» «a_{0}» «the space line nets» «what the waiting makes» «the rate space is made» «what bodies' rays grow where they meet» «\bar{n}» «the world's matter grows» «H» «cH» «\frac{a_{0}}{cH}») (w : Defined «the continuous model» «\sigma» «F» «n» «DEG» «\nu» «\rho» «l.\bar{m}» «\omega» «\varepsilon» «H_{\Lambda}» «D» «the folds line nets» «n_{f}» «what a body feels» «\sum\hat{d}» «S» «what is taken» «what is made» «\rho_{\infty}» «\lambda» «what a body puts into the medium» «\bar{m}_{x}» «l.DEG» «\beta» «A» «\bar{R}» «r» «\bar{c}» «v» «a_{0}» «the space line nets» «what the waiting makes» «the rate space is made» «what bodies' rays grow where they meet» «\bar{n}» «the world's matter grows» «H» «cH» «\frac{a_{0}}{cH}») :
    «a_{0}» = ((2 : ℝ) * «\omega» * ((«n_{f}» + (1 : ℝ)))⁻¹ * «\sigma» * «F» * (((-1 : ℝ) * «\rho») + (1 : ℝ)) * («\rho» ^ 2) * («D»)⁻¹) := by
  have h32 := p.«the inference 'the phase between the two pulses, which the body's own acceleration keeps from cancelling': a_{0}»
  have h3 := u.unchecked_gravity_coincidence_3
  have h14 := check_14 «the continuous model» «\sigma» «F» «n» «DEG» «\nu» «\rho» «l.\bar{m}» «\omega» «\varepsilon» «H_{\Lambda}» «D» «the folds line nets» «n_{f}» «what a body feels» «\sum\hat{d}» «S» «what is taken» «what is made» «\rho_{\infty}» «\lambda» «what a body puts into the medium» «\bar{m}_{x}» «l.DEG» «\beta» «A» «\bar{R}» «r» «\bar{c}» «v» «a_{0}» «the space line nets» «what the waiting makes» «the rate space is made» «what bodies' rays grow where they meet» «\bar{n}» «the world's matter grows» «H» «cH» «\frac{a_{0}}{cH}» p u w
  have h29 := p.«read off the continuous model: \omega»
  have h26 := p.«read off the continuous model: \sigma»
  have h27 := u.unchecked_gravity_coincidence_27
  have w0 := w.ne_0
  have w1 := w.ne_1
  have w2 := w.ne_2
  have w3 := w.ne_3
  have w4 := w.ne_4
  have w5 := w.ne_5
  have w6 := w.ne_6
  have w7 := w.ne_7
  have w8 := w.ne_8
  have w9 := w.ne_9
  have w10 := w.ne_10
  have p0 := w.pos_0
  have r0 := fun (y : ℝ) => Real.rpow_neg (le_of_lt w.pos_0) y
  have q0 := fun (y : ℝ) => (Real.rpow_pos_of_pos w.pos_0 y).ne'
  have p1 := w.pos_1
  have r1 := fun (y : ℝ) => Real.rpow_neg (le_of_lt w.pos_1) y
  have q1 := fun (y : ℝ) => (Real.rpow_pos_of_pos w.pos_1 y).ne'
  have p2 := w.pos_2
  have r2 := fun (y : ℝ) => Real.rpow_neg (le_of_lt w.pos_2) y
  have q2 := fun (y : ℝ) => (Real.rpow_pos_of_pos w.pos_2 y).ne'
  subst_vars
  try simp only [neg_one_mul, r0, r1, r2] at *
  check_algebra

/-- step 18 (the room the line does not supply, which the waiting has to make): the rate space is made = \sigma·\paren{1 - \omega}·\rho - CHECKED: the inference's relation (claim 33, read off its code) with the lines it stands on put in - what the waiting makes = \sigma·\paren{1 - \omega}·\rho, with \sigma = 1, \omega = 1 put in - is this line, by algebra -/
theorem check_18 («the continuous model» «\sigma» «F» «n» «DEG» «\nu» «\rho» «l.\bar{m}» «\omega» «\varepsilon» «H_{\Lambda}» «D» «the folds line nets» «n_{f}» «what a body feels» «\sum\hat{d}» «S» «what is taken» «what is made» «\rho_{\infty}» «\lambda» «what a body puts into the medium» «\bar{m}_{x}» «l.DEG» «\beta» «A» «\bar{R}» «r» «\bar{c}» «v» «a_{0}» «the space line nets» «what the waiting makes» «the rate space is made» «what bodies' rays grow where they meet» «\bar{n}» «the world's matter grows» «H» «cH» «\frac{a_{0}}{cH}» : ℝ)
    (p : Premises «the continuous model» «\sigma» «F» «n» «DEG» «\nu» «\rho» «l.\bar{m}» «\omega» «\varepsilon» «H_{\Lambda}» «D» «the folds line nets» «n_{f}» «what a body feels» «\sum\hat{d}» «S» «what is taken» «what is made» «\rho_{\infty}» «\lambda» «what a body puts into the medium» «\bar{m}_{x}» «l.DEG» «\beta» «A» «\bar{R}» «r» «\bar{c}» «v» «a_{0}» «the space line nets» «what the waiting makes» «the rate space is made» «what bodies' rays grow where they meet» «\bar{n}» «the world's matter grows» «H» «cH» «\frac{a_{0}}{cH}») (u : Unchecked «the continuous model» «\sigma» «F» «n» «DEG» «\nu» «\rho» «l.\bar{m}» «\omega» «\varepsilon» «H_{\Lambda}» «D» «the folds line nets» «n_{f}» «what a body feels» «\sum\hat{d}» «S» «what is taken» «what is made» «\rho_{\infty}» «\lambda» «what a body puts into the medium» «\bar{m}_{x}» «l.DEG» «\beta» «A» «\bar{R}» «r» «\bar{c}» «v» «a_{0}» «the space line nets» «what the waiting makes» «the rate space is made» «what bodies' rays grow where they meet» «\bar{n}» «the world's matter grows» «H» «cH» «\frac{a_{0}}{cH}») (w : Defined «the continuous model» «\sigma» «F» «n» «DEG» «\nu» «\rho» «l.\bar{m}» «\omega» «\varepsilon» «H_{\Lambda}» «D» «the folds line nets» «n_{f}» «what a body feels» «\sum\hat{d}» «S» «what is taken» «what is made» «\rho_{\infty}» «\lambda» «what a body puts into the medium» «\bar{m}_{x}» «l.DEG» «\beta» «A» «\bar{R}» «r» «\bar{c}» «v» «a_{0}» «the space line nets» «what the waiting makes» «the rate space is made» «what bodies' rays grow where they meet» «\bar{n}» «the world's matter grows» «H» «cH» «\frac{a_{0}}{cH}») :
    «the rate space is made» = («\sigma» * (((-1 : ℝ) * «\omega») + (1 : ℝ)) * «\rho») := by
  have h33 := p.«the inference 'the room the line does not supply, which the waiting has to make': the rate space is made»
  have h17 := p.«read off the continuous model: what the waiting makes»
  have h26 := p.«read off the continuous model: \sigma»
  have h29 := p.«read off the continuous model: \omega»
  have w0 := w.ne_0
  have w1 := w.ne_1
  have w2 := w.ne_2
  have w3 := w.ne_3
  have w4 := w.ne_4
  have w5 := w.ne_5
  have w6 := w.ne_6
  have w7 := w.ne_7
  have w8 := w.ne_8
  have w9 := w.ne_9
  have w10 := w.ne_10
  have p0 := w.pos_0
  have r0 := fun (y : ℝ) => Real.rpow_neg (le_of_lt w.pos_0) y
  have q0 := fun (y : ℝ) => (Real.rpow_pos_of_pos w.pos_0 y).ne'
  have p1 := w.pos_1
  have r1 := fun (y : ℝ) => Real.rpow_neg (le_of_lt w.pos_1) y
  have q1 := fun (y : ℝ) => (Real.rpow_pos_of_pos w.pos_1 y).ne'
  have p2 := w.pos_2
  have r2 := fun (y : ℝ) => Real.rpow_neg (le_of_lt w.pos_2) y
  have q2 := fun (y : ℝ) => (Real.rpow_pos_of_pos w.pos_2 y).ne'
  subst_vars
  try simp only [neg_one_mul, r0, r1, r2] at *
  check_algebra

/-- step 22 (the rate the whole of it expands at): H = \frac{\paren{\nu·n_{f}·\paren{1 - \rho} + \sigma·\paren{1 - \omega}·\rho + 2·\sigma·F·\bar{n}^{2} + 2·\sigma·F·\paren{1 - \rho}·\rho^{2} - \sigma·F·\rho^{2}}}{D} - CHECKED: the inference's relation (claim 34, read off its code) with the lines it stands on put in - the space line nets = \nu·n_{f}·\paren{1 - \rho} + \sigma·\paren{1 - \omega}·\rho - \sigma·F·\rho^{2}; the world's matter grows = 2·\sigma·F·\bar{n}^{2}, with \sigma = 1, F = \frac{1}{2}, \nu = 1, \omega = 1, \bar{n} = 0 put in - is this line, by algebra -/
theorem check_22 («the continuous model» «\sigma» «F» «n» «DEG» «\nu» «\rho» «l.\bar{m}» «\omega» «\varepsilon» «H_{\Lambda}» «D» «the folds line nets» «n_{f}» «what a body feels» «\sum\hat{d}» «S» «what is taken» «what is made» «\rho_{\infty}» «\lambda» «what a body puts into the medium» «\bar{m}_{x}» «l.DEG» «\beta» «A» «\bar{R}» «r» «\bar{c}» «v» «a_{0}» «the space line nets» «what the waiting makes» «the rate space is made» «what bodies' rays grow where they meet» «\bar{n}» «the world's matter grows» «H» «cH» «\frac{a_{0}}{cH}» : ℝ)
    (p : Premises «the continuous model» «\sigma» «F» «n» «DEG» «\nu» «\rho» «l.\bar{m}» «\omega» «\varepsilon» «H_{\Lambda}» «D» «the folds line nets» «n_{f}» «what a body feels» «\sum\hat{d}» «S» «what is taken» «what is made» «\rho_{\infty}» «\lambda» «what a body puts into the medium» «\bar{m}_{x}» «l.DEG» «\beta» «A» «\bar{R}» «r» «\bar{c}» «v» «a_{0}» «the space line nets» «what the waiting makes» «the rate space is made» «what bodies' rays grow where they meet» «\bar{n}» «the world's matter grows» «H» «cH» «\frac{a_{0}}{cH}») (u : Unchecked «the continuous model» «\sigma» «F» «n» «DEG» «\nu» «\rho» «l.\bar{m}» «\omega» «\varepsilon» «H_{\Lambda}» «D» «the folds line nets» «n_{f}» «what a body feels» «\sum\hat{d}» «S» «what is taken» «what is made» «\rho_{\infty}» «\lambda» «what a body puts into the medium» «\bar{m}_{x}» «l.DEG» «\beta» «A» «\bar{R}» «r» «\bar{c}» «v» «a_{0}» «the space line nets» «what the waiting makes» «the rate space is made» «what bodies' rays grow where they meet» «\bar{n}» «the world's matter grows» «H» «cH» «\frac{a_{0}}{cH}») (w : Defined «the continuous model» «\sigma» «F» «n» «DEG» «\nu» «\rho» «l.\bar{m}» «\omega» «\varepsilon» «H_{\Lambda}» «D» «the folds line nets» «n_{f}» «what a body feels» «\sum\hat{d}» «S» «what is taken» «what is made» «\rho_{\infty}» «\lambda» «what a body puts into the medium» «\bar{m}_{x}» «l.DEG» «\beta» «A» «\bar{R}» «r» «\bar{c}» «v» «a_{0}» «the space line nets» «what the waiting makes» «the rate space is made» «what bodies' rays grow where they meet» «\bar{n}» «the world's matter grows» «H» «cH» «\frac{a_{0}}{cH}») :
    «H» = ((((-1 : ℝ) * «\sigma» * «F» * («\rho» ^ 2)) + («\nu» * «n_{f}» * (((-1 : ℝ) * «\rho») + (1 : ℝ))) + («\sigma» * (((-1 : ℝ) * «\omega») + (1 : ℝ)) * «\rho») + ((2 : ℝ) * «\sigma» * «F» * («\bar{n}» ^ 2)) + ((2 : ℝ) * «\sigma» * «F» * (((-1 : ℝ) * «\rho») + (1 : ℝ)) * («\rho» ^ 2))) * («D»)⁻¹) := by
  have h34 := p.«the inference 'the rate the whole of it expands at': H»
  have h16 := p.«read off the continuous model: the space line nets»
  have h21 := p.«ANNIHILATION: the world's matter grows»
  have h26 := p.«read off the continuous model: \sigma»
  have h27 := u.unchecked_gravity_coincidence_27
  have h31 := p.«read off the continuous model: \nu»
  have h29 := p.«read off the continuous model: \omega»
  have h20 := p.«read off the continuous model: \bar{n}»
  have w0 := w.ne_0
  have w1 := w.ne_1
  have w2 := w.ne_2
  have w3 := w.ne_3
  have w4 := w.ne_4
  have w5 := w.ne_5
  have w6 := w.ne_6
  have w7 := w.ne_7
  have w8 := w.ne_8
  have w9 := w.ne_9
  have w10 := w.ne_10
  have p0 := w.pos_0
  have r0 := fun (y : ℝ) => Real.rpow_neg (le_of_lt w.pos_0) y
  have q0 := fun (y : ℝ) => (Real.rpow_pos_of_pos w.pos_0 y).ne'
  have p1 := w.pos_1
  have r1 := fun (y : ℝ) => Real.rpow_neg (le_of_lt w.pos_1) y
  have q1 := fun (y : ℝ) => (Real.rpow_pos_of_pos w.pos_1 y).ne'
  have p2 := w.pos_2
  have r2 := fun (y : ℝ) => Real.rpow_neg (le_of_lt w.pos_2) y
  have q2 := fun (y : ℝ) => (Real.rpow_pos_of_pos w.pos_2 y).ne'
  subst_vars
  try simp only [neg_one_mul, r0, r1, r2] at *
  check_algebra

/-- step 23 (the acceleration the expansion builds): cH = \frac{\paren{\nu·n_{f}·\paren{1 - \rho} + \sigma·\paren{1 - \omega}·\rho + 2·\sigma·F·\bar{n}^{2} + 2·\sigma·F·\paren{1 - \rho}·\rho^{2} - \sigma·F·\rho^{2}}}{D} - CHECKED: the inference's relation (claim 35, read off its code) with the lines it stands on put in - H = \frac{\paren{\nu·n_{f}·\paren{1 - \rho} + \sigma·\paren{1 - \omega}·\rho + 2·\sigma·F·\bar{n}^{2} + 2·\sigma·F·\paren{1 - \rho}·\rho^{2} - \sigma·F·\rho^{2}}}{D}; \bar{c} = 1, with \sigma = 1, F = \frac{1}{2}, \nu = 1, \omega = 1, \bar{n} = 0 put in - is this line, by algebra -/
theorem check_23 («the continuous model» «\sigma» «F» «n» «DEG» «\nu» «\rho» «l.\bar{m}» «\omega» «\varepsilon» «H_{\Lambda}» «D» «the folds line nets» «n_{f}» «what a body feels» «\sum\hat{d}» «S» «what is taken» «what is made» «\rho_{\infty}» «\lambda» «what a body puts into the medium» «\bar{m}_{x}» «l.DEG» «\beta» «A» «\bar{R}» «r» «\bar{c}» «v» «a_{0}» «the space line nets» «what the waiting makes» «the rate space is made» «what bodies' rays grow where they meet» «\bar{n}» «the world's matter grows» «H» «cH» «\frac{a_{0}}{cH}» : ℝ)
    (p : Premises «the continuous model» «\sigma» «F» «n» «DEG» «\nu» «\rho» «l.\bar{m}» «\omega» «\varepsilon» «H_{\Lambda}» «D» «the folds line nets» «n_{f}» «what a body feels» «\sum\hat{d}» «S» «what is taken» «what is made» «\rho_{\infty}» «\lambda» «what a body puts into the medium» «\bar{m}_{x}» «l.DEG» «\beta» «A» «\bar{R}» «r» «\bar{c}» «v» «a_{0}» «the space line nets» «what the waiting makes» «the rate space is made» «what bodies' rays grow where they meet» «\bar{n}» «the world's matter grows» «H» «cH» «\frac{a_{0}}{cH}») (u : Unchecked «the continuous model» «\sigma» «F» «n» «DEG» «\nu» «\rho» «l.\bar{m}» «\omega» «\varepsilon» «H_{\Lambda}» «D» «the folds line nets» «n_{f}» «what a body feels» «\sum\hat{d}» «S» «what is taken» «what is made» «\rho_{\infty}» «\lambda» «what a body puts into the medium» «\bar{m}_{x}» «l.DEG» «\beta» «A» «\bar{R}» «r» «\bar{c}» «v» «a_{0}» «the space line nets» «what the waiting makes» «the rate space is made» «what bodies' rays grow where they meet» «\bar{n}» «the world's matter grows» «H» «cH» «\frac{a_{0}}{cH}») (w : Defined «the continuous model» «\sigma» «F» «n» «DEG» «\nu» «\rho» «l.\bar{m}» «\omega» «\varepsilon» «H_{\Lambda}» «D» «the folds line nets» «n_{f}» «what a body feels» «\sum\hat{d}» «S» «what is taken» «what is made» «\rho_{\infty}» «\lambda» «what a body puts into the medium» «\bar{m}_{x}» «l.DEG» «\beta» «A» «\bar{R}» «r» «\bar{c}» «v» «a_{0}» «the space line nets» «what the waiting makes» «the rate space is made» «what bodies' rays grow where they meet» «\bar{n}» «the world's matter grows» «H» «cH» «\frac{a_{0}}{cH}») :
    «cH» = ((((-1 : ℝ) * «\sigma» * «F» * («\rho» ^ 2)) + («\nu» * «n_{f}» * (((-1 : ℝ) * «\rho») + (1 : ℝ))) + («\sigma» * (((-1 : ℝ) * «\omega») + (1 : ℝ)) * «\rho») + ((2 : ℝ) * «\sigma» * «F» * («\bar{n}» ^ 2)) + ((2 : ℝ) * «\sigma» * «F» * (((-1 : ℝ) * «\rho») + (1 : ℝ)) * («\rho» ^ 2))) * («D»)⁻¹) := by
  have h35 := p.«the inference 'the acceleration the expansion builds': cH»
  have h22 := check_22 «the continuous model» «\sigma» «F» «n» «DEG» «\nu» «\rho» «l.\bar{m}» «\omega» «\varepsilon» «H_{\Lambda}» «D» «the folds line nets» «n_{f}» «what a body feels» «\sum\hat{d}» «S» «what is taken» «what is made» «\rho_{\infty}» «\lambda» «what a body puts into the medium» «\bar{m}_{x}» «l.DEG» «\beta» «A» «\bar{R}» «r» «\bar{c}» «v» «a_{0}» «the space line nets» «what the waiting makes» «the rate space is made» «what bodies' rays grow where they meet» «\bar{n}» «the world's matter grows» «H» «cH» «\frac{a_{0}}{cH}» p u w
  have h13 := p.«read off the continuous model: \bar{c}»
  have h26 := p.«read off the continuous model: \sigma»
  have h27 := u.unchecked_gravity_coincidence_27
  have h31 := p.«read off the continuous model: \nu»
  have h29 := p.«read off the continuous model: \omega»
  have h20 := p.«read off the continuous model: \bar{n}»
  have w0 := w.ne_0
  have w1 := w.ne_1
  have w2 := w.ne_2
  have w3 := w.ne_3
  have w4 := w.ne_4
  have w5 := w.ne_5
  have w6 := w.ne_6
  have w7 := w.ne_7
  have w8 := w.ne_8
  have w9 := w.ne_9
  have w10 := w.ne_10
  have p0 := w.pos_0
  have r0 := fun (y : ℝ) => Real.rpow_neg (le_of_lt w.pos_0) y
  have q0 := fun (y : ℝ) => (Real.rpow_pos_of_pos w.pos_0 y).ne'
  have p1 := w.pos_1
  have r1 := fun (y : ℝ) => Real.rpow_neg (le_of_lt w.pos_1) y
  have q1 := fun (y : ℝ) => (Real.rpow_pos_of_pos w.pos_1 y).ne'
  have p2 := w.pos_2
  have r2 := fun (y : ℝ) => Real.rpow_neg (le_of_lt w.pos_2) y
  have q2 := fun (y : ℝ) => (Real.rpow_pos_of_pos w.pos_2 y).ne'
  subst_vars
  try simp only [neg_one_mul, r0, r1, r2] at *
  check_algebra

/-- step 24 (the scale against the expansion): \frac{a_{0}}{cH} = \frac{2·\omega·\sigma·F·\paren{1 - \rho}·\rho^{2}}{\paren{n_{f} + 1}·\paren{\nu·n_{f}·\paren{1 - \rho} + \sigma·\paren{1 - \omega}·\rho + 2·\sigma·F·\bar{n}^{2} + 2·\sigma·F·\paren{1 - \rho}·\rho^{2} - \sigma·F·\rho^{2}}} - CHECKED: the inference's relation (claim 36, read off its code) with the lines it stands on put in - a_{0} = \frac{2·\omega·\sigma·F·\paren{1 - \rho}·\rho^{2}}{\paren{n_{f} + 1}·D}; cH = \frac{\paren{\nu·n_{f}·\paren{1 - \rho} + \sigma·\paren{1 - \omega}·\rho + 2·\sigma·F·\bar{n}^{2} + 2·\sigma·F·\paren{1 - \rho}·\rho^{2} - \sigma·F·\rho^{2}}}{D}, with \omega = 1, \sigma = 1, F = \frac{1}{2}, \nu = 1, \bar{n} = 0 put in - is this line, by algebra -/
theorem check_24 («the continuous model» «\sigma» «F» «n» «DEG» «\nu» «\rho» «l.\bar{m}» «\omega» «\varepsilon» «H_{\Lambda}» «D» «the folds line nets» «n_{f}» «what a body feels» «\sum\hat{d}» «S» «what is taken» «what is made» «\rho_{\infty}» «\lambda» «what a body puts into the medium» «\bar{m}_{x}» «l.DEG» «\beta» «A» «\bar{R}» «r» «\bar{c}» «v» «a_{0}» «the space line nets» «what the waiting makes» «the rate space is made» «what bodies' rays grow where they meet» «\bar{n}» «the world's matter grows» «H» «cH» «\frac{a_{0}}{cH}» : ℝ)
    (p : Premises «the continuous model» «\sigma» «F» «n» «DEG» «\nu» «\rho» «l.\bar{m}» «\omega» «\varepsilon» «H_{\Lambda}» «D» «the folds line nets» «n_{f}» «what a body feels» «\sum\hat{d}» «S» «what is taken» «what is made» «\rho_{\infty}» «\lambda» «what a body puts into the medium» «\bar{m}_{x}» «l.DEG» «\beta» «A» «\bar{R}» «r» «\bar{c}» «v» «a_{0}» «the space line nets» «what the waiting makes» «the rate space is made» «what bodies' rays grow where they meet» «\bar{n}» «the world's matter grows» «H» «cH» «\frac{a_{0}}{cH}») (u : Unchecked «the continuous model» «\sigma» «F» «n» «DEG» «\nu» «\rho» «l.\bar{m}» «\omega» «\varepsilon» «H_{\Lambda}» «D» «the folds line nets» «n_{f}» «what a body feels» «\sum\hat{d}» «S» «what is taken» «what is made» «\rho_{\infty}» «\lambda» «what a body puts into the medium» «\bar{m}_{x}» «l.DEG» «\beta» «A» «\bar{R}» «r» «\bar{c}» «v» «a_{0}» «the space line nets» «what the waiting makes» «the rate space is made» «what bodies' rays grow where they meet» «\bar{n}» «the world's matter grows» «H» «cH» «\frac{a_{0}}{cH}») (w : Defined «the continuous model» «\sigma» «F» «n» «DEG» «\nu» «\rho» «l.\bar{m}» «\omega» «\varepsilon» «H_{\Lambda}» «D» «the folds line nets» «n_{f}» «what a body feels» «\sum\hat{d}» «S» «what is taken» «what is made» «\rho_{\infty}» «\lambda» «what a body puts into the medium» «\bar{m}_{x}» «l.DEG» «\beta» «A» «\bar{R}» «r» «\bar{c}» «v» «a_{0}» «the space line nets» «what the waiting makes» «the rate space is made» «what bodies' rays grow where they meet» «\bar{n}» «the world's matter grows» «H» «cH» «\frac{a_{0}}{cH}») :
    «\frac{a_{0}}{cH}» = ((2 : ℝ) * «\omega» * ((«n_{f}» + (1 : ℝ)))⁻¹ * «\sigma» * «F» * (((-1 : ℝ) * «\rho») + (1 : ℝ)) * («\rho» ^ 2) * ((((-1 : ℝ) * «\sigma» * «F» * («\rho» ^ 2)) + («\nu» * «n_{f}» * (((-1 : ℝ) * «\rho») + (1 : ℝ))) + («\sigma» * (((-1 : ℝ) * «\omega») + (1 : ℝ)) * «\rho») + ((2 : ℝ) * «\sigma» * «F» * («\bar{n}» ^ 2)) + ((2 : ℝ) * «\sigma» * «F» * (((-1 : ℝ) * «\rho») + (1 : ℝ)) * («\rho» ^ 2))))⁻¹) := by
  have h36 := p.«the inference 'the scale against the expansion': \frac{a_{0}}{cH}»
  have h15 := check_15 «the continuous model» «\sigma» «F» «n» «DEG» «\nu» «\rho» «l.\bar{m}» «\omega» «\varepsilon» «H_{\Lambda}» «D» «the folds line nets» «n_{f}» «what a body feels» «\sum\hat{d}» «S» «what is taken» «what is made» «\rho_{\infty}» «\lambda» «what a body puts into the medium» «\bar{m}_{x}» «l.DEG» «\beta» «A» «\bar{R}» «r» «\bar{c}» «v» «a_{0}» «the space line nets» «what the waiting makes» «the rate space is made» «what bodies' rays grow where they meet» «\bar{n}» «the world's matter grows» «H» «cH» «\frac{a_{0}}{cH}» p u w
  have h23 := check_23 «the continuous model» «\sigma» «F» «n» «DEG» «\nu» «\rho» «l.\bar{m}» «\omega» «\varepsilon» «H_{\Lambda}» «D» «the folds line nets» «n_{f}» «what a body feels» «\sum\hat{d}» «S» «what is taken» «what is made» «\rho_{\infty}» «\lambda» «what a body puts into the medium» «\bar{m}_{x}» «l.DEG» «\beta» «A» «\bar{R}» «r» «\bar{c}» «v» «a_{0}» «the space line nets» «what the waiting makes» «the rate space is made» «what bodies' rays grow where they meet» «\bar{n}» «the world's matter grows» «H» «cH» «\frac{a_{0}}{cH}» p u w
  have h29 := p.«read off the continuous model: \omega»
  have h26 := p.«read off the continuous model: \sigma»
  have h27 := u.unchecked_gravity_coincidence_27
  have h31 := p.«read off the continuous model: \nu»
  have h20 := p.«read off the continuous model: \bar{n}»
  have w0 := w.ne_0
  have w1 := w.ne_1
  have w2 := w.ne_2
  have w3 := w.ne_3
  have w4 := w.ne_4
  have w5 := w.ne_5
  have w6 := w.ne_6
  have w7 := w.ne_7
  have w8 := w.ne_8
  have w9 := w.ne_9
  have w10 := w.ne_10
  have p0 := w.pos_0
  have r0 := fun (y : ℝ) => Real.rpow_neg (le_of_lt w.pos_0) y
  have q0 := fun (y : ℝ) => (Real.rpow_pos_of_pos w.pos_0 y).ne'
  have p1 := w.pos_1
  have r1 := fun (y : ℝ) => Real.rpow_neg (le_of_lt w.pos_1) y
  have q1 := fun (y : ℝ) => (Real.rpow_pos_of_pos w.pos_1 y).ne'
  have p2 := w.pos_2
  have r2 := fun (y : ℝ) => Real.rpow_neg (le_of_lt w.pos_2) y
  have q2 := fun (y : ℝ) => (Real.rpow_pos_of_pos w.pos_2 y).ne'
  subst_vars
  try simp only [neg_one_mul, r0, r1, r2] at *
  check_algebra

/-- the answer (the answer): \frac{a_{0}}{cH} = \frac{\paren{1 - \rho}·\rho^{2}}{\paren{n_{f} + 1}·\paren{n_{f}·\paren{1 - \rho} + \paren{1 - \rho}·\rho^{2} - \frac{\rho^{2}}{2}}} - CHECKED: claim 24 with the settled numbers put in, with \omega = 1, \sigma = 1, F = \frac{1}{2}, \nu = 1, \bar{n} = 0 put in -/
theorem answer («the continuous model» «\sigma» «F» «n» «DEG» «\nu» «\rho» «l.\bar{m}» «\omega» «\varepsilon» «H_{\Lambda}» «D» «the folds line nets» «n_{f}» «what a body feels» «\sum\hat{d}» «S» «what is taken» «what is made» «\rho_{\infty}» «\lambda» «what a body puts into the medium» «\bar{m}_{x}» «l.DEG» «\beta» «A» «\bar{R}» «r» «\bar{c}» «v» «a_{0}» «the space line nets» «what the waiting makes» «the rate space is made» «what bodies' rays grow where they meet» «\bar{n}» «the world's matter grows» «H» «cH» «\frac{a_{0}}{cH}» : ℝ)
    (p : Premises «the continuous model» «\sigma» «F» «n» «DEG» «\nu» «\rho» «l.\bar{m}» «\omega» «\varepsilon» «H_{\Lambda}» «D» «the folds line nets» «n_{f}» «what a body feels» «\sum\hat{d}» «S» «what is taken» «what is made» «\rho_{\infty}» «\lambda» «what a body puts into the medium» «\bar{m}_{x}» «l.DEG» «\beta» «A» «\bar{R}» «r» «\bar{c}» «v» «a_{0}» «the space line nets» «what the waiting makes» «the rate space is made» «what bodies' rays grow where they meet» «\bar{n}» «the world's matter grows» «H» «cH» «\frac{a_{0}}{cH}») (u : Unchecked «the continuous model» «\sigma» «F» «n» «DEG» «\nu» «\rho» «l.\bar{m}» «\omega» «\varepsilon» «H_{\Lambda}» «D» «the folds line nets» «n_{f}» «what a body feels» «\sum\hat{d}» «S» «what is taken» «what is made» «\rho_{\infty}» «\lambda» «what a body puts into the medium» «\bar{m}_{x}» «l.DEG» «\beta» «A» «\bar{R}» «r» «\bar{c}» «v» «a_{0}» «the space line nets» «what the waiting makes» «the rate space is made» «what bodies' rays grow where they meet» «\bar{n}» «the world's matter grows» «H» «cH» «\frac{a_{0}}{cH}») (w : Defined «the continuous model» «\sigma» «F» «n» «DEG» «\nu» «\rho» «l.\bar{m}» «\omega» «\varepsilon» «H_{\Lambda}» «D» «the folds line nets» «n_{f}» «what a body feels» «\sum\hat{d}» «S» «what is taken» «what is made» «\rho_{\infty}» «\lambda» «what a body puts into the medium» «\bar{m}_{x}» «l.DEG» «\beta» «A» «\bar{R}» «r» «\bar{c}» «v» «a_{0}» «the space line nets» «what the waiting makes» «the rate space is made» «what bodies' rays grow where they meet» «\bar{n}» «the world's matter grows» «H» «cH» «\frac{a_{0}}{cH}») :
    «\frac{a_{0}}{cH}» = (((«n_{f}» + (1 : ℝ)))⁻¹ * (((-1 : ℝ) * «\rho») + (1 : ℝ)) * («\rho» ^ 2) * (((((-5 : ℝ) / 10) * («\rho» ^ 2)) + («n_{f}» * (((-1 : ℝ) * «\rho») + (1 : ℝ))) + ((((-1 : ℝ) * «\rho») + (1 : ℝ)) * («\rho» ^ 2))))⁻¹) := by
  have h24 := check_24 «the continuous model» «\sigma» «F» «n» «DEG» «\nu» «\rho» «l.\bar{m}» «\omega» «\varepsilon» «H_{\Lambda}» «D» «the folds line nets» «n_{f}» «what a body feels» «\sum\hat{d}» «S» «what is taken» «what is made» «\rho_{\infty}» «\lambda» «what a body puts into the medium» «\bar{m}_{x}» «l.DEG» «\beta» «A» «\bar{R}» «r» «\bar{c}» «v» «a_{0}» «the space line nets» «what the waiting makes» «the rate space is made» «what bodies' rays grow where they meet» «\bar{n}» «the world's matter grows» «H» «cH» «\frac{a_{0}}{cH}» p u w
  have h29 := p.«read off the continuous model: \omega»
  have h26 := p.«read off the continuous model: \sigma»
  have h27 := u.unchecked_gravity_coincidence_27
  have h31 := p.«read off the continuous model: \nu»
  have h20 := p.«read off the continuous model: \bar{n}»
  have w0 := w.ne_0
  have w1 := w.ne_1
  have w2 := w.ne_2
  have w3 := w.ne_3
  have w4 := w.ne_4
  have w5 := w.ne_5
  have w6 := w.ne_6
  have w7 := w.ne_7
  have w8 := w.ne_8
  have w9 := w.ne_9
  have w10 := w.ne_10
  have p0 := w.pos_0
  have r0 := fun (y : ℝ) => Real.rpow_neg (le_of_lt w.pos_0) y
  have q0 := fun (y : ℝ) => (Real.rpow_pos_of_pos w.pos_0 y).ne'
  have p1 := w.pos_1
  have r1 := fun (y : ℝ) => Real.rpow_neg (le_of_lt w.pos_1) y
  have q1 := fun (y : ℝ) => (Real.rpow_pos_of_pos w.pos_1 y).ne'
  have p2 := w.pos_2
  have r2 := fun (y : ℝ) => Real.rpow_neg (le_of_lt w.pos_2) y
  have q2 := fun (y : ℝ) => (Real.rpow_pos_of_pos w.pos_2 y).ne'
  subst_vars
  try simp only [neg_one_mul, r0, r1, r2] at *
  check_algebra



end OrbitMines.Physics.Proofs.G.«gravity.coincidence»
