-- GENERATED by `npx ray gen` from implementation/physics.ray and implementation/gen - do not edit
import OrbitMines.Physics.Proofs.Basic
set_option linter.unusedVariables false
set_option linter.unusedSimpArgs false
set_option linter.unusedTactic false
set_option maxHeartbeats 4000000
open OrbitMines.Physics.Proofs

/-!
# vacuum.settled (G)

and where the vacuum has settled, so that the near-field terms do not matter - what is left of the line?

Lean checked 0 of its 2 steps; 1 are premises read off the program and 1 are not checked. And the answer is CHECKED (it names \Delta_{\hat{d}}\rho_{l} + a·\nabla S_{l} \aside{at} \rho_{\infty} again (claim 2), and its value is the earlier one's by algebra).

- step 2 (the vacuum settled), NOT checked: the inference 'the vacuum settled' reached it from what the store held in its own code (Inferences.ray, Prove.ray): the relation it applies to them is not recorded with the step, so there is nothing to check the line against - it is stated as the prover wrote it
- answer (the answer), checked: it names \Delta_{\hat{d}}\rho_{l} + a·\nabla S_{l} \aside{at} \rho_{\infty} again (claim 2), and its value is the earlier one's by algebra
-/

namespace OrbitMines.Physics.Proofs.G.«vacuum.settled»

/-- What the prover takes from the rules: the premises, read off the program BY DESIGN - a rule's own body, the
continuous model the rules were read into, the lattice, a count. None is believed or measured; each is already in the
theory's .ray. -/
structure Premises («the continuous model» «\sigma» «F» «n» «DEG» «\nu» «\rho» «l.\bar{m}» «\omega» «\Delta_{\hat{d}}\rho_{l} + a·\nabla S_{l} \aside{at} \rho_{\infty}» : ℝ) : Prop where
  /-- step 1 (the reading): the continuous model = DEG·\nu·\paren{1 - \rho} + l.\bar{m}·\omega - 2·\sigma·F·n^{2} - the rules read as a line (Reading.ray): the root every derivation passes through -/
  «the reading: the continuous model» : «the continuous model» = (((-1 : ℝ) * (2 : ℝ) * «\sigma» * «F» * («n» ^ 2)) + («DEG» * «\nu» * ((1 : ℝ) + ((-1 : ℝ) * «\rho»))) + ((1 : ℝ) * «l.\bar{m}» * «\omega»))

/-- The steps Lean does not check, each with the reason. They are hypotheses of every theorem below - stated, never proven. -/
structure Unchecked («the continuous model» «\sigma» «F» «n» «DEG» «\nu» «\rho» «l.\bar{m}» «\omega» «\Delta_{\hat{d}}\rho_{l} + a·\nabla S_{l} \aside{at} \rho_{\infty}» : ℝ) : Prop where
  /-- step 2 (the vacuum settled): \Delta_{\hat{d}}\rho_{l} + a·\nabla S_{l} \aside{at} \rho_{\infty} = l.\bar{m} - NOT CHECKED: the inference 'the vacuum settled' reached it from what the store held in its own code (Inferences.ray, Prove.ray): the relation it applies to them is not recorded with the step, so there is nothing to check the line against - it is stated as the prover wrote it -/
  unchecked_vacuum_settled_2 : «\Delta_{\hat{d}}\rho_{l} + a·\nabla S_{l} \aside{at} \rho_{\infty}» = «l.\bar{m}»

/-- Where the lines are defined: what the prover divides by. Its algebra cancels across these, so they are taken to be nonzero. -/
structure Defined («the continuous model» «\sigma» «F» «n» «DEG» «\nu» «\rho» «l.\bar{m}» «\omega» «\Delta_{\hat{d}}\rho_{l} + a·\nabla S_{l} \aside{at} \rho_{\infty}» : ℝ) : Prop

/-- the answer (the answer): \Delta_{\hat{d}}\rho_{l} + a·\nabla S_{l} \aside{at} \rho_{\infty} = l.\bar{m} - CHECKED: it names \Delta_{\hat{d}}\rho_{l} + a·\nabla S_{l} \aside{at} \rho_{\infty} again (claim 2), and its value is the earlier one's by algebra -/
theorem answer («the continuous model» «\sigma» «F» «n» «DEG» «\nu» «\rho» «l.\bar{m}» «\omega» «\Delta_{\hat{d}}\rho_{l} + a·\nabla S_{l} \aside{at} \rho_{\infty}» : ℝ)
    (p : Premises «the continuous model» «\sigma» «F» «n» «DEG» «\nu» «\rho» «l.\bar{m}» «\omega» «\Delta_{\hat{d}}\rho_{l} + a·\nabla S_{l} \aside{at} \rho_{\infty}») (u : Unchecked «the continuous model» «\sigma» «F» «n» «DEG» «\nu» «\rho» «l.\bar{m}» «\omega» «\Delta_{\hat{d}}\rho_{l} + a·\nabla S_{l} \aside{at} \rho_{\infty}») (w : Defined «the continuous model» «\sigma» «F» «n» «DEG» «\nu» «\rho» «l.\bar{m}» «\omega» «\Delta_{\hat{d}}\rho_{l} + a·\nabla S_{l} \aside{at} \rho_{\infty}») :
    «\Delta_{\hat{d}}\rho_{l} + a·\nabla S_{l} \aside{at} \rho_{\infty}» = «l.\bar{m}» := by
  have h2 := u.unchecked_vacuum_settled_2
  check_algebra



end OrbitMines.Physics.Proofs.G.«vacuum.settled»
