-- GENERATED by `npx ray gen` from implementation/physics.ray and implementation/gen - do not edit
import OrbitMines.Physics.Proofs.Basic
set_option linter.unusedVariables false
set_option linter.unusedSimpArgs false
set_option linter.unusedTactic false
set_option maxHeartbeats 4000000
open OrbitMines.Physics.Proofs

/-!
# vacuum.occupancy (G)

the vacuum makes and takes at once. Left alone, where does it settle - and is that a number the rules fix, or one somebody chose?

Lean checked 0 of its 4 steps; 3 are premises read off the program and 1 are not checked. And the answer is CHECKED (claim 4 with the settled numbers put in, with F = \frac{1}{2} put in).

- step 4 (where the making pays for the taking), NOT checked: the inference 'where the making pays for the taking' (Inferences.ray) was run again with the lines it cites standing as their names, to read the relation it applies off its code: its relation holds a root in the name the lines it cites are written in, and they are put in under the root by name - which substitution in a prover does not do; and with every line of the store standing as its name: its relation holds a root in the name the lines it cites are written in, and they are put in under the root by name - which substitution in a prover does not do. So there is no relation to check the line against, and it is stated as the prover wrote it
- settled number 5 (isotropy leaves no mean heading), NOT checked: the inference 'isotropy leaves no mean heading' reached it from what the store held in its own code (Inferences.ray, Prove.ray): the relation it applies to them is not recorded with the step, so there is nothing to check the line against - it is stated as the prover wrote it
- answer (the answer), checked: claim 4 with the settled numbers put in, with F = \frac{1}{2} put in
-/

namespace OrbitMines.Physics.Proofs.G.«vacuum.occupancy»

/-- What the prover takes from the rules: the premises, read off the program BY DESIGN - a rule's own body, the
continuous model the rules were read into, the lattice, a count. None is believed or measured; each is already in the
theory's .ray. -/
structure Premises («the continuous model» «\sigma» «F» «n» «DEG» «\nu» «\rho» «l.\bar{m}» «\omega» «what is made» «what is taken» «\rho_{\infty}» : ℝ) : Prop where
  /-- step 1 (the reading): the continuous model = DEG·\nu·\paren{1 - \rho} + l.\bar{m}·\omega - 2·\sigma·F·n^{2} - the rules read as a line (Reading.ray): the root every derivation passes through -/
  «the reading: the continuous model» : «the continuous model» = (((-1 : ℝ) * (2 : ℝ) * «\sigma» * «F» * («n» ^ 2)) + («DEG» * «\nu» * ((1 : ℝ) + ((-1 : ℝ) * «\rho»))) + ((1 : ℝ) * «l.\bar{m}» * «\omega»))
  /-- step 2 (read off the continuous model): what is made = \nu·\paren{1 - \rho} - read off the continuous model - a term of the line the rules were read into, or how the line is made -/
  «read off the continuous model: what is made» : «what is made» = («\nu» * (((-1 : ℝ) * «\rho») + (1 : ℝ)))
  /-- step 3 (read off the continuous model): what is taken = \sigma·F·\rho^{2} - read off the continuous model - a term of the line the rules were read into, or how the line is made -/
  «read off the continuous model: what is taken» : «what is taken» = («\sigma» * «F» * («\rho» ^ 2))

/-- The steps Lean does not check, each with the reason. They are hypotheses of every theorem below - stated, never proven. -/
structure Unchecked («the continuous model» «\sigma» «F» «n» «DEG» «\nu» «\rho» «l.\bar{m}» «\omega» «what is made» «what is taken» «\rho_{\infty}» : ℝ) : Prop where
  /-- step 4 (where the making pays for the taking): \rho_{\infty} = \text{the } \rho \text{ where } DEG·\paren{1 - \rho} - 2·F·\rho^{2} = 0 - NOT CHECKED: the inference 'where the making pays for the taking' (Inferences.ray) was run again with the lines it cites standing as their names, to read the relation it applies off its code: its relation holds a root in the name the lines it cites are written in, and they are put in under the root by name - which substitution in a prover does not do; and with every line of the store standing as its name: its relation holds a root in the name the lines it cites are written in, and they are put in under the root by name - which substitution in a prover does not do. So there is no relation to check the line against, and it is stated as the prover wrote it -/
  unchecked_vacuum_occupancy_4 : «\rho_{\infty}» = (RootOf (fun («\rho» : ℝ) => ((«DEG» * (((-1 : ℝ) * «\rho») + (1 : ℝ))) + ((-2 : ℝ) * «F» * («\rho» ^ 2)))))
  /-- a settled number (isotropy leaves no mean heading): F = \frac{1}{2} - NOT CHECKED: the inference 'isotropy leaves no mean heading' reached it from what the store held in its own code (Inferences.ray, Prove.ray): the relation it applies to them is not recorded with the step, so there is nothing to check the line against - it is stated as the prover wrote it -/
  unchecked_vacuum_occupancy_5 : «F» = ((1 : ℝ) * ((2 : ℝ))⁻¹)

/-- Where the lines are defined: what the prover divides by. Its algebra cancels across these, so they are taken to be nonzero. -/
structure Defined («the continuous model» «\sigma» «F» «n» «DEG» «\nu» «\rho» «l.\bar{m}» «\omega» «what is made» «what is taken» «\rho_{\infty}» : ℝ) : Prop

/-- the answer (the answer): \rho_{\infty} = \text{the } \rho \text{ where } DEG·\paren{1 - \rho} - \rho^{2} = 0 - CHECKED: claim 4 with the settled numbers put in, with F = \frac{1}{2} put in -/
theorem answer («the continuous model» «\sigma» «F» «n» «DEG» «\nu» «\rho» «l.\bar{m}» «\omega» «what is made» «what is taken» «\rho_{\infty}» : ℝ)
    (p : Premises «the continuous model» «\sigma» «F» «n» «DEG» «\nu» «\rho» «l.\bar{m}» «\omega» «what is made» «what is taken» «\rho_{\infty}») (u : Unchecked «the continuous model» «\sigma» «F» «n» «DEG» «\nu» «\rho» «l.\bar{m}» «\omega» «what is made» «what is taken» «\rho_{\infty}») (w : Defined «the continuous model» «\sigma» «F» «n» «DEG» «\nu» «\rho» «l.\bar{m}» «\omega» «what is made» «what is taken» «\rho_{\infty}») :
    «\rho_{\infty}» = (RootOf (fun («\rho» : ℝ) => ((«DEG» * (((-1 : ℝ) * «\rho») + (1 : ℝ))) + ((-1 : ℝ) * («\rho» ^ 2))))) := by
  have h4 := u.unchecked_vacuum_occupancy_4
  have h5 := u.unchecked_vacuum_occupancy_5
  check_algebra



end OrbitMines.Physics.Proofs.G.«vacuum.occupancy»
