# GENERATED by `npx ray gen` from implementation/physics.ray - do not edit
#
# THE RUNTIME the emitted classes stand on (OrbitMinesPhysics): what a Ray class is in Julia, and what the
# recognised classes (N, String, Array, boolean) and the operators of Ray are.
#
# A Ray class is Julia's own: an abstract type carries the inheritance (`AbstractHole <: AbstractSource`), a
# mutable struct is the class (`Hole <: AbstractHole`), a field is a struct field read through a function of the
# same name (`mass(h)`, its default made on first read), and every member is a function dispatched on the abstract
# type - multiple dispatch finds the nearest class, as Ray's chain does. `@class` (below) lays a class out; the
# Ray-facing functions and operators are in `Rt.Ops`. Numbers are Float64, lists Vector{Any} (`List`).
module Rt

export @class, @theory, @field, @static_field, @rule, @theorem, @members, @dynamic_names, @j_str,
  AbstractNode, Node, Many, List, Unset, UNSET, HOME, truthy, items, getat, setat!, rng, filled, fail, str,
  tonumber, from_codepoints, isray, hasmember, collapse, dyn, fmt_number, held, restore!

# --- text as the emitter writes it -----------------------------------------------------------------------
# Every text of Ray is written `j"..."`: a string macro sees its text raw, so a `$` in it is only a `$`. The
# emitter escapes `\`, `"`, newlines and tabs; the raw reading has already undone the escapes before a quote
# (and at the end), and every other escape is undone here, once, when the file is read.
function unray(s::AbstractString)
  cs = collect(s)
  out = IOBuffer()
  i, n = 1, length(cs)
  while i <= n
    c = cs[i]
    if c != '\\'
      print(out, c); i += 1; continue
    end
    j = i
    while j <= n && cs[j] == '\\'; j += 1; end
    run = j - i
    if j > n || cs[j] == '"'
      for _ in 1:run; print(out, '\\'); end
      i = j; continue
    end
    for _ in 1:(run ÷ 2); print(out, '\\'); end
    if isodd(run)
      e = cs[j]
      if e == 'n'; print(out, '\n'); j += 1
      elseif e == 't'; print(out, '\t'); j += 1
      elseif e == 'r'; print(out, '\r'); j += 1
      elseif e == 'b'; print(out, '\b'); j += 1
      elseif e == 'f'; print(out, '\f'); j += 1
      elseif e == 'u' && j + 4 <= n; print(out, Char(parse(UInt32, String(cs[j+1:j+4]); base = 16))); j += 5
      else print(out, e); j += 1
      end
    end
    i = j
  end
  String(take!(out))
end
macro j_str(s) unray(s) end

# --- what every Ray object is ----------------------------------------------------------------------------
"""the root of every Ray class; the `{}` of Ray (`Node`) is the one that is only its slots"""
abstract type AbstractNode end
"""a field whose default has not been made yet (it is made on first read, as Ray makes it)"""
struct Unset end
const UNSET = Unset()
"""a new object, before its fields are set"""
struct Blank end
const BLANK = Blank()
const List = Base.Vector{Any}

"""`{}`: a map from names to values - Ray's dynamic members, and nothing else"""
mutable struct Node <: AbstractNode
  slots::Union{Nothing,Dict{Symbol,Any}}
end
function Node(; kw...)
  n = Node(Dict{Symbol,Any}())
  for (k, v) in kw; getfield(n, :slots)[k] = tonum(v); end
  n
end

"""a superposition: members apply elementwise, equal things collapse"""
struct Many
  items::List
end
Many(xs::AbstractVector) = Many(List(xs))

"""the module the classes are emitted into: where a member named at run time (`x[name]`) is found"""
const HOME = Ref{Module}(@__MODULE__)

# --- what `@class` records while the package is read, and what it registers when it runs ---------------------
const FIELDS = Dict{Symbol,Vector{Tuple{Symbol,Any,Bool}}}(:Node => Tuple{Symbol,Any,Bool}[])   # a class's fields, parents first
const CLASSNAMES = Set{Symbol}()                     # every Ray class read so far
const DECLARED = Set{Symbol}()                       # every member name that has its fallback
const STATICS = Dict{Tuple{Type,Symbol},Base.RefValue{Any}}()
const ZEROARG = Dict{Type,Set{Symbol}}()           # the members a class reads without arguments (fields, getters)
const THEORIES = Any[]

tonum(@nospecialize(x)) = x isa Bool ? x : x isa Real ? Float64(x) : x isa AbstractVector && !(x isa List) ? Any[tonum(y) for y in x] : x

"""a value into a field of this type: whole numbers are Float64, as every number of Ray is"""
fit(::Type{T}, @nospecialize(v)) where {T} = v isa Integer && !(v isa Bool) ? Float64(v) : v

"""`Class(x: 1, ...)`: positional values fill the fields in the order they are declared, named ones by name"""
function construct!(o::AbstractNode, names::Tuple, args::Tuple, kw)
  for (i, v) in enumerate(args)
    i <= length(names) || break
    setproperty!(o, names[i], v)
  end
  for (k, v) in kw
    setproperty!(o, k, v)
  end
  o
end

# a field typed as Ray types it: a number, a truth, a text or a list; any other value is Any
function fieldtype_of(t)
  base = t === :Float64 ? :Float64 : t === :Bool ? :Bool : t === :String ? :String : t === :List ? :($List) : nothing
  base === nothing ? :Any : :(Union{$Unset,Nothing,$base})
end
isstatic_sig(a) = a isa Expr && a.head === :(::) && length(a.args) == 2 && a.args[2] isa Expr && a.args[2].head === :curly && a.args[2].args[1] === :Type
function replace_sym(e, from::Symbol, to)
  e === from && return to
  e isa Expr || return e
  Expr(e.head, (replace_sym(a, from, to) for a in e.args)...)
end
defname(e) = e isa Expr && e.head === :function && e.args[1] isa Expr && e.args[1].head === :call ? e.args[1].args[1] : nothing
defargs(e) = e.args[1].args[2:end]
ismacro(e, m::Symbol) = e isa Expr && e.head === :macrocall && e.args[1] === m
macroargs(e) = filter(a -> !(a isa LineNumberNode), e.args[2:end])
function fallback(n::Symbol)
  x, a = gensym("x"), gensym("a")
  :($n($x, $a...) = $Rt.dyn($n, $(QuoteNode(n)), $x, $(a)...))
end

"""
    @class Name <: Parent begin ... end

A Ray class: an abstract type under the parent's (`AbstractName <: AbstractParent`), a mutable struct holding the
fields of the class and of every parent, a function per field (its default made on first read), and every member
written in the body - `function f(self::__class__, ...)` - dispatched on the abstract type, so a subclass takes
what it does not redefine. `self::Type{<:__class__}` is a static. A member no class of a value has is found by
name (`Rt.dyn`): in a `Node`, in the slots Ray set on an object, or elementwise on a `Many`.
"""
macro class(head, body) esc(expand_class(head, body, false)) end
"""`@theory G <: Theory begin ... end`: a class whose one object is the theory (`G`), its rules and theorems in order"""
macro theory(head, body) esc(expand_class(head, body, true)) end
"""the names read off `Node`s (a term of the equation): a function each, found by name in the node"""
macro members(names...)
  out = Expr(:toplevel)
  for n in names
    n in DECLARED && continue
    push!(DECLARED, n)
    push!(out.args, fallback(n))
  end
  esc(out)
end
"""
    @dynamic_names expr

`expr`, where every member it reads that no class declares (the symbols of a reading: `s.ω`, set by name as
`s["ω"] = 1`) is found by name: a function each, whose one method is the by-name fallback.
"""
macro dynamic_names(e)
  found = Symbol[]
  walk(x) = x isa Expr ? (x.head === :call && Base.length(x.args) >= 2 && x.args[1] isa Symbol && Base.isidentifier(x.args[1]) &&
    !isdefined(__module__, x.args[1]) && !(x.args[1] in found) && push!(found, x.args[1]); foreach(walk, x.args)) : nothing
  walk(e)
  out = Expr(:toplevel)
  for n in found
    __module__ === HOME[] && push!(DECLARED, n)
    push!(out.args, fallback(n))
  end
  push!(out.args, e)
  esc(out)
end
macro field(e) error("@field stands in a @class body") end
macro static_field(e) error("@static_field stands in a @class body") end
macro rule(a...) error("@rule stands in a @theory body") end
macro theorem(a...) error("@theorem stands in a @theory body") end

function expand_class(head, body::Expr, theory::Bool)
  name, parent = head isa Expr && head.head === :(<:) ? (head.args[1], head.args[2]) : (head, :Node)
  abs = Symbol("Abstract", name)
  pabs = parent === :Node ? :($AbstractNode) : Symbol("Abstract", parent)
  T = theory ? Symbol(name, "Theory") : name
  own = Tuple{Symbol,Any,Bool,Any}[]
  statics = Tuple{Symbol,Any}[]
  rules, theorems, defs = Any[], Any[], Any[]
  for st in body.args
    if ismacro(st, Symbol("@field"))
      a = macroargs(st)[1]
      d, hasd = nothing, false
      if a isa Expr && a.head === :(=); d, hasd, a = a.args[2], true, a.args[1]; end
      f, t = a isa Expr && a.head === :(::) ? (a.args[1], a.args[2]) : (a, :Any)
      t isa Symbol || (t = :Any)
      push!(own, (f, t, hasd, d))
    elseif ismacro(st, Symbol("@static_field"))
      a = macroargs(st)[1]
      a isa Expr && a.head === :(=) ? push!(statics, (a.args[1], a.args[2])) : push!(statics, (a, nothing))
    elseif ismacro(st, Symbol("@rule"))
      push!(rules, macroargs(st))
    elseif ismacro(st, Symbol("@theorem"))
      push!(theorems, macroargs(st)[1])
    elseif !(st isa LineNumberNode)
      push!(defs, st)
    end
  end
  # a field declared twice is the last declaration; a field the class also writes a member for is that member's
  own = [o for (i, o) in enumerate(own) if !any(x -> x[1] === o[1], own[i+1:end])]
  written = Set(n for n in (defname(e) for e in defs) if n !== nothing)
  # the fields: the parent's, then this class's own (a field declared again keeps its place, with its new default)
  fields = copy(get(FIELDS, parent, Tuple{Symbol,Any,Bool}[]))
  for (f, t, hasd, _) in own
    i = findfirst(x -> x[1] === f, fields)
    entry = (f, i === nothing ? t : fields[i][2], hasd || (i !== nothing && fields[i][3]))
    i === nothing ? push!(fields, entry) : (fields[i] = entry)
  end
  FIELDS[name] = fields
  push!(CLASSNAMES, name)
  out = Expr(:toplevel)
  push!(out.args, :(abstract type $abs <: $pabs end))
  decls = [:($(f)::$(fieldtype_of(t))) for (f, t, _) in fields]
  inits = [hasd ? UNSET : nothing for (_, _, hasd) in fields]
  push!(out.args, quote
    mutable struct $T <: $abs
      $(decls...)
      slots::Union{Nothing,Dict{Symbol,Any}}
      $T(::$Blank) = new($(inits...), nothing)
    end
  end)
  names = Tuple(f for (f, _, _) in fields)
  push!(out.args, :($T(args...; kw...) = $construct!($T($BLANK), $names, args, kw)))
  push!(out.args, :(Base.show(io::IO, x::$T) = print(io, $str(x))))
  zero = Symbol[]
  defined = Set{Symbol}()
  # a field: read through its function, its default made on first read (`self` is the object)
  for (f, _, hasd, d) in own
    push!(zero, f); push!(defined, f)
    f in written && continue
    if hasd
      v = gensym("v")
      push!(out.args, quote
        function $f(self::$abs)
          $v = getfield(self, $(QuoteNode(f)))
          $v isa $Unset || return $v
          $v = $d
          setfield!(self, $(QuoteNode(f)), $fit(fieldtype(typeof(self), $(QuoteNode(f))), $v))
        end
      end)
    else
      push!(out.args, :($f(self::$abs) = getfield(self, $(QuoteNode(f)))))
    end
  end
  # a static: one value for the class, made on first read, read through the class or any of its objects
  for (s, d) in statics
    push!(zero, s); push!(defined, s)
    ref = Symbol("static#", name, "#", s)
    push!(out.args, :(const $ref = Base.RefValue{Any}($UNSET)))
    push!(out.args, :($STATICS[($abs, $(QuoteNode(s)))] = $ref))
    v = gensym("v")
    push!(out.args, :($s(self::Type{<:$abs}) = ($v = $ref[]; $v isa $Unset ? ($ref[] = let self = nothing; $d end) : $v)))
    s in instance_names(defs) || push!(out.args, :($s(self::$abs) = $s($T)))
  end
  instance = instance_names(defs)
  for e in defs
    e = replace_sym(replace_sym(e, :__class__, abs), :__type__, T)
    n = defname(e)
    if n !== nothing
      push!(defined, n)
      args = defargs(e)
      if length(args) == 1 && !isstatic_sig(args[1])
        # a member read without arguments (a getter): what Ray set on the object by that name comes first
        push!(zero, n)
        sl = gensym("slots")
        e.args[2] = quote
          let $sl = getfield(self, :slots)
            $sl === nothing || !haskey($sl, $(QuoteNode(n))) || return $sl[$(QuoteNode(n))]
          end
          $(e.args[2])
        end
      elseif !isempty(args) && isstatic_sig(args[1]) && !(n in instance)
        # a static, read through an object of the class too
        a = gensym("a")
        push!(out.args, :($n(self::$abs, $(a)...) = $n($T, $(a)...)))
        length(args) == 1 && push!(zero, n)
      end
    end
    push!(out.args, e)
  end
  for n in defined
    n in DECLARED && continue
    push!(DECLARED, n)
    push!(out.args, fallback(n))
  end
  push!(out.args, :($ZEROARG[$abs] = Set{Symbol}($(QuoteNode(zero)))))
  if theory
    # the theory's one object, its rules - each a Rule: its metadata and its body - and its theorems, in the order written
    rs = Any[r for (_, _, r) in rules]
    push!(out.args, :(const $name = $T()))
    push!(out.args, quote
      let self = $name
        self.rules = Any[$(rs...)]
        self.theorems = Any[$(theorems...)]
      end
      push!($THEORIES, $name)
    end)
  end
  out
end

function instance_names(defs)
  instance = Set{Symbol}()
  for e in defs
    n = defname(e)
    n === nothing && continue
    args = defargs(e)
    (isempty(args) || !isstatic_sig(args[1])) && push!(instance, n)
  end
  instance
end

# --- a member no class of the value has: found by name ---------------------------------------------------------
const OWN = Dict{Tuple{Any,DataType},Bool}()
"""whether `f` has a method of a class for this one argument (not only the by-name fallback)"""
function owns(f, @nospecialize(x))
  get!(OWN, (f, typeof(x))) do
    m = try which(f, Tuple{typeof(x)}) catch; nothing end
    m !== nothing && m.sig isa DataType && m.sig.parameters[2] !== Any
  end
end
function slots_of(x::AbstractNode)
  s = getfield(x, :slots)
  s === nothing ? nothing : s
end

"""
the fallback of every member: on a `Many` elementwise (equal results collapse), on a Node or an object the value Ray
set by that name (called, where it is a program and arguments are given), and a field holding a program called
with the arguments (`p.place(setup)`); an unknown member reads as nothing
"""
function dyn(f, name::Symbol, @nospecialize(x), a...)
  if x isa Many
    return collapse(Any[i === nothing ? nothing : f(i, a...) for i in x.items])
  elseif x === nothing
    error("no member $(name) on None")
  elseif x isa AbstractNode
    s = slots_of(x)
    if s !== nothing && haskey(s, name)
      v = s[name]
      return isempty(a) || !(v isa Function) ? v : v(a...)
    end
    if !isempty(a) && owns(f, x)
      v = f(x)
      v isa Function && return v(a...)
      return v
    end
    isempty(a) && return nothing
    error("no method $(name) on $(nameof(typeof(x)))")
  elseif x isa Type
    error("no static $(name) on $(x)")
  end
  error("no member $(name) on $(typeof(x))")
end

"""a member by the name Ray computes (`x[name]`): a member function the class has, else what was set by that name"""
function getmember(@nospecialize(x), s::Symbol)
  x isa Many && return collapse(Any[getmember(i, s) for i in x.items])
  f = isdefined(HOME[], s) ? getglobal(HOME[], s) : nothing
  if x isa AbstractNode
    sl = slots_of(x)
    sl !== nothing && haskey(sl, s) && return sl[s]
    f isa Function && owns(f, x) && return f(x)
    return nothing
  elseif x isa Type
    f isa Function && applicable(f, x) && return f(x)
    return nothing
  end
  f isa Function && applicable(f, x) ? f(x) : nothing
end

# the objects read as Julia reads a struct: `m.seed`, `m.local_rays = true`, `m.add(hole)`
function Base.getproperty(x::AbstractNode, s::Symbol)
  sl = getfield(x, :slots)
  sl !== nothing && haskey(sl, s) && return sl[s]
  f = isdefined(HOME[], s) ? getglobal(HOME[], s) : nothing
  f isa Function || return hasfield(typeof(x), s) ? getfield(x, s) : nothing
  for (k, names) in ZEROARG
    x isa k && s in names && return f(x)
  end
  hasfield(typeof(x), s) && return f(x)
  (a...) -> f(x, a...)
end
function Base.setproperty!(x::AbstractNode, s::Symbol, @nospecialize(v))
  if s !== :slots && hasfield(typeof(x), s)
    return setfield!(x, s, fit(fieldtype(typeof(x), s), v))
  end
  sl = getfield(x, :slots)
  sl === nothing && (sl = Dict{Symbol,Any}(); setfield!(x, :slots, sl))
  sl[s] = tonum(v)
end
function Base.setproperty!(x::Type{<:AbstractNode}, s::Symbol, @nospecialize(v))
  for (k, ref) in STATICS
    k[2] === s && x <: k[1] && return (ref[] = v)
  end
  error("no static $(s) on $(x)")
end
Base.propertynames(x::AbstractNode) = Tuple(f for f in fieldnames(typeof(x)) if f !== :slots)

"""whether an object has a member of this name, of its own or its class's"""
function hasmember(@nospecialize(x), s::Symbol)
  if x isa AbstractNode
    sl = slots_of(x)
    sl !== nothing && haskey(sl, s) && return true
  end
  f = isdefined(HOME[], s) ? getglobal(HOME[], s) : nothing
  f isa Function && owns(f, x)
end

"""what the classes and the theories hold, to be put back (`restore!`) after a run that must leave nothing behind"""
held() = (Dict(k => r[] for (k, r) in STATICS), Dict(t => Dict(f => getfield(t, f) for f in fieldnames(typeof(t))) for t in THEORIES))
function restore!(h)
  for (k, v) in h[1]; STATICS[k][] = v; end
  for (t, fs) in h[2], (f, v) in fs
    setfield!(t, f, f === :slots && v !== nothing ? copy(v) : v)
  end
  nothing
end

"""`x ==.instance_of T`: a class is its abstract type (a subclass is one), a recognised class Julia's own"""
isray(@nospecialize(x), T::Type) = T <: AbstractNode && isconcretetype(T) ? x isa supertype(T) : x isa T
isray(@nospecialize(x), t::AbstractNode) = x === t

# --- the values of Ray ---------------------------------------------------------------------------------------
truthy(x::Bool) = x
truthy(x::Float64) = x != 0.0
truthy(@nospecialize(x)) = !(x === nothing || x === false || (x isa Real && !(x isa Bool) && x == 0))
function num(@nospecialize(x))::Float64
  x isa Float64 && return x
  x === nothing && return 0.0
  x isa Bool && return x ? 1.0 : 0.0
  x isa Real && return Float64(x)
  NaN
end
arith(@nospecialize(a)) = a isa Float64 || a === nothing || a isa Real

"""a number as JavaScript writes it (the bootstrap's): whole numbers without a point, the shortest digits that read back"""
function fmt_number(d::Float64)
  isnan(d) && return "NaN"
  isinf(d) && return d > 0 ? "Infinity" : "-Infinity"
  d == 0 && return "0"
  if d == round(d) && abs(d) < 1e21
    return string(BigInt(d))
  end
  s = string(abs(d))
  e = 0
  if occursin('e', s)
    m, ex = split(s, 'e')
    e = parse(Int, ex)
  else
    m = s
  end
  ip, fp = occursin('.', m) ? split(m, '.') : (m, "")
  digits = ip * fp
  n = length(ip) + e
  lead = findfirst(c -> c != '0', digits)
  n -= lead - 1
  digits = rstrip(digits[lead:end], '0')
  k = length(digits)
  body = if k <= n <= 21
    digits * "0"^(n - k)
  elseif 0 < n <= 21
    digits[1:n] * "." * digits[n+1:end]
  elseif -6 < n <= 0
    "0." * "0"^(-n) * digits
  else
    x = n - 1
    (k == 1 ? digits : digits[1:1] * "." * digits[2:end]) * "e" * (x >= 0 ? "+" : "-") * string(abs(x))
  end
  d < 0 ? "-" * body : body
end

"""a value as text, as the bootstrap writes it"""
function str(@nospecialize(x))::String
  x === nothing && return "null"
  x isa String && return x
  x isa Float64 && return fmt_number(x)
  x isa Bool && return x ? "true" : "false"
  x isa Real && return fmt_number(Float64(x))
  x isa AbstractVector && return join((str(y) for y in x), ",")
  if x isa AbstractNode
    v = Ops.toString(x)
    return v === nothing ? String(nameof(typeof(x))) : str(v)
  end
  x isa Many && return join((str(y) for y in x.items), ",")
  x isa Type && return String(nameof(x))
  x isa AbstractString && return String(x)
  string(x)
end

function items(@nospecialize(xs))::List
  xs isa List && return copy(xs)
  xs isa Many && return copy(xs.items)
  xs isa AbstractVector && return Any[xs...]
  xs isa AbstractString && return Any[string(c) for c in xs]
  xs === nothing && return Any[]
  error("not a list: $(str(xs))")
end
index_int(@nospecialize(k)) = (v = num(k); isfinite(v) ? trunc(Int, clamp(v, -9.0e18, 9.0e18)) : typemin(Int) ÷ 2)

"""`x[k]`: Ray indexes from 0 (negative from the end); an object by a member's name"""
function getat(t::List, k::Float64)
  i = index_int(k)
  i < 0 && (i += length(t))
  0 <= i < length(t) ? (@inbounds t[i+1]) : nothing
end
function getat(@nospecialize(t), @nospecialize(k))
  t === nothing && return nothing
  if t isa AbstractVector
    i = index_int(k)
    i < 0 && (i += length(t))
    return 0 <= i < length(t) ? t[i+1] : nothing
  end
  if t isa AbstractString
    cs = collect(t)
    i = index_int(k)
    i < 0 && (i += length(cs))
    return 0 <= i < length(cs) ? string(cs[i+1]) : nothing
  end
  t isa Many && return collapse(Any[getat(x, k) for x in t.items])
  (t isa AbstractNode || t isa Type) && return getmember(t, Symbol(k isa AbstractString ? k : str(k)))
  nothing
end
function setat!(t::List, @nospecialize(k), @nospecialize(v))
  i = index_int(k)
  while length(t) <= i; push!(t, nothing); end
  t[i+1] = v
end
function setat!(@nospecialize(t), @nospecialize(k), @nospecialize(v))
  t isa Many && (for x in t.items; setat!(x, k, v); end; return v)
  s = Symbol(k isa AbstractString ? k : str(k))
  t isa Type ? setproperty!(t, s, v) : setproperty!(t, s, v)
  v
end
rng(@nospecialize(n)) = Any[Float64(i) for i in 0:(ceil(Int, num(n)) - 1)]
filled(@nospecialize(n), @nospecialize(v)) = Any[v for _ in 1:ceil(Int, num(n))]
fail(@nospecialize(says)) = error(str(says))
function tonumber(@nospecialize(s))
  t = strip(str(s))
  t == "Infinity" && return Inf
  t == "-Infinity" && return -Inf
  v = tryparse(Float64, t)
  v === nothing ? NaN : v
end
from_codepoints(@nospecialize(xs)) = String([Char(Int(num(c))) for c in items(xs)])
function collapse(xs::List)
  isempty(xs) && return Many(xs)
  f = xs[1]
  for i in xs
    (i === f || (i isa List && f isa List && Ops.:(==)(i, f))) || return Many(xs)
  end
  f
end
Base.show(io::IO, m::Many) = print(io, "Many(", length(m.items), ")")

# ================================================================================================================
# THE RAY-FACING FUNCTIONS: the operators of Ray, and the members Ray knows on a list, a text and a number. They are
# functions of their own (not Base's), so the package's classes extend them: a class with a `split` of its own
# (`Expr.split(e, name)`) adds a method, and `split(e, name)` finds it. Everything else goes to `dyn`.
# ================================================================================================================
module Ops

import ..Rt: Rt, List, Many, AbstractNode, truthy, num, arith, items, collapse, dyn, str, index_int, fmt_number
export +, -, *, /, %, ^, ==, !=, <, <=, >, >=, !,
  plus, minus, times, over, mod, pow, lt, le, gt, ge, equals, negated, toString,
  push, chars, pop, length, map, filter, for_, some, every, reduce, starts_with, ends_with, replace, split, trim,
  upper, lower, lines, quoted, contains, index_of, join, first, last, empty, take, drop, rest, concat, reverse, sum,
  most, sorted_by, each, sqrt, floor, abs, magnitude, cos, sin, round, ln, exp, atan2, blank

# every one of these is extended by a class that has a member of that name; what no class has goes to `dyn`
for n in (:plus, :minus, :times, :over, :mod, :pow, :lt, :le, :gt, :ge, :negated, :toString,
    :push, :chars, :pop, :length, :map, :filter, :for_, :some, :every, :reduce, :starts_with, :ends_with, :replace,
    :split, :trim, :upper, :lower, :lines, :quoted, :contains, :index_of, :join, :first, :last, :empty, :take, :drop,
    :rest, :concat, :reverse, :sum, :most, :sorted_by, :each, :sqrt, :floor, :abs, :magnitude, :cos, :sin, :round,
    :ln, :exp, :atan2, :blank)
  @eval $n(@nospecialize(x), a...) = dyn($n, $(QuoteNode(n)), x, a...)
end
toString(@nospecialize(x::AbstractNode)) = dyn(toString, :toString, x)
equals(@nospecialize(a), @nospecialize(b)) = a === b

# --- the operators -----------------------------------------------------------------------------------------------
+(a::Float64, b::Float64) = Base.:+(a, b)
+(a, b, c, xs...) = +(+(a, b), c, xs...)
*(a, b, c, xs...) = *(*(a, b), c, xs...)
-(a::Float64, b::Float64) = Base.:-(a, b)
*(a::Float64, b::Float64) = Base.:*(a, b)
-(a::Float64) = Base.:-(a)
<(a::Float64, b::Float64) = Base.:<(a, b)
<=(a::Float64, b::Float64) = Base.:<=(a, b)
>(a::Float64, b::Float64) = Base.:>(a, b)
>=(a::Float64, b::Float64) = Base.:>=(a, b)
==(a::Float64, b::Float64) = Base.:(==)(a, b)
function +(@nospecialize(a), @nospecialize(b))
  a isa AbstractString && return Base.:*(String(a), str(b))
  arith(a) ? Base.:+(num(a), num(b)) : plus(a, b)
end
-(@nospecialize(a), @nospecialize(b)) = arith(a) ? Base.:-(num(a), num(b)) : minus(a, b)
*(@nospecialize(a), @nospecialize(b)) = arith(a) ? Base.:*(num(a), num(b)) : times(a, b)
-(@nospecialize(a)) = arith(a) ? Base.:-(num(a)) : negated(a)
function /(@nospecialize(a), @nospecialize(b))
  arith(a) || return over(a, b)
  x, y = num(a), num(b)
  Base.:(==)(y, 0.0) && Base.:(==)(x, 0.0) ? 0.0 : Base.:/(x, y)
end
%(@nospecialize(a), @nospecialize(b)) = arith(a) ? Base.rem(num(a), num(b)) : mod(a, b)
pw(x::Float64, y::Float64) = Base.:<(x, 0) && !Base.isinteger(y) ? NaN : Base.:^(x, y)
^(@nospecialize(a), @nospecialize(b)) = arith(a) ? pw(num(a), num(b)) : pow(a, b)
<(@nospecialize(a), @nospecialize(b)) = arith(a) ? Base.:<(num(a), num(b)) : a isa AbstractString ? Base.:<(a, b) : lt(a, b)
<=(@nospecialize(a), @nospecialize(b)) = arith(a) ? Base.:<=(num(a), num(b)) : a isa AbstractString ? Base.:<=(a, b) : le(a, b)
>(@nospecialize(a), @nospecialize(b)) = arith(a) ? Base.:>(num(a), num(b)) : a isa AbstractString ? Base.:>(a, b) : gt(a, b)
>=(@nospecialize(a), @nospecialize(b)) = arith(a) ? Base.:>=(num(a), num(b)) : a isa AbstractString ? Base.:>=(a, b) : ge(a, b)
!(@nospecialize(a)) = Base.:!(truthy(a))
!=(@nospecialize(a), @nospecialize(b)) = Base.:!(a == b)
function ==(@nospecialize(a), @nospecialize(b))::Bool
  a === b && return true
  (a === nothing || b === nothing) && return false
  a isa Float64 && b isa Float64 && return Base.:(==)(a, b)
  if a isa Many
    for x in a.items; x == b || return false; end
    return true
  end
  (a isa Bool || b isa Bool) && return false
  a isa Real && b isa Real && return Base.:(==)(Float64(a), Float64(b))
  if a isa AbstractVector && b isa AbstractVector
    Base.:(==)(Base.length(a), Base.length(b)) || return false
    for i in Base.eachindex(a); a[i] == b[i] || return false; end
    return true
  end
  a isa AbstractString && return b isa AbstractString && Base.:(==)(a, b)
  a isa AbstractNode && return truthy(equals(a, b))
  false
end

# --- a member Ray knows on a list, a text or a number ------------------------------------------------------------
push(xs::List, x) = (Base.push!(xs, x); xs)
chars(s::AbstractString) = Any[Float64(UInt32(c)) for c in s]
pop(xs::List) = Base.isempty(xs) ? nothing : Base.pop!(xs)
length(xs::AbstractVector) = Float64(Base.length(xs))
length(s::AbstractString) = Float64(Base.length(s))
length(m::Many) = Float64(Base.length(m.items))
map(xs::Union{AbstractVector,AbstractString}, f) = Any[f(x) for x in items(xs)]
map(xs::Nothing, f) = Any[]
filter(xs::Union{AbstractVector,AbstractString,Nothing}, f) = Any[x for x in items(xs) if truthy(f(x))]
filter(xs::Many, f) = Many(Any[x for x in xs.items if truthy(f(x))])
function for_(xs::Union{AbstractVector,AbstractString,Many,Nothing}, f)
  for x in items(xs); f(x); end
  nothing
end
function some(xs::Union{AbstractVector,AbstractString,Many,Nothing}, f)
  for x in items(xs); truthy(f(x)) && return true; end
  false
end
function every(xs::Union{AbstractVector,AbstractString,Many,Nothing}, f)
  for x in items(xs); truthy(f(x)) || return false; end
  true
end
function reduce(xs::Union{AbstractVector,AbstractString,Many,Nothing}, z, f)
  acc = z
  for x in items(xs); acc = f(acc, x); end
  acc
end
starts_with(s::AbstractString, x) = Base.startswith(s, str(x))
ends_with(s::AbstractString, x) = Base.endswith(s, str(x))
function replace(s::AbstractString, x, y)
  a = str(x)
  Base.isempty(a) ? String(s) : Base.replace(s, a => str(y))
end
function split(s::AbstractString, x)
  sep = str(x)
  Base.isempty(sep) && return items(s)
  Any[String(p) for p in Base.split(s, sep; keepempty = true)]
end
trim(s::AbstractString) = String(Base.strip(s))
upper(s::AbstractString) = Base.uppercase(s)
lower(s::AbstractString) = Base.lowercase(s)
lines(s::AbstractString) = split(s, "\n")
function quoted(@nospecialize(x::Union{AbstractString,Real,Nothing,AbstractVector,Bool}))
  s = str(x)
  io = IOBuffer()
  Base.print(io, '"')
  for c in s
    if Base.:(==)(c, '"'); Base.print(io, "\\\"")
    elseif Base.:(==)(c, '\\'); Base.print(io, "\\\\")
    elseif Base.:(==)(c, '\n'); Base.print(io, "\\n")
    elseif Base.:(==)(c, '\r'); Base.print(io, "\\r")
    elseif Base.:(==)(c, '\t'); Base.print(io, "\\t")
    elseif Base.:<(c, ' '); Base.print(io, "\\u", Base.string(UInt32(c), base = 16, pad = 4))
    else Base.print(io, c)
    end
  end
  Base.print(io, '"')
  String(Base.take!(io))
end
contains(s::AbstractString, x) = Base.occursin(str(x), s)
function contains(xs::Union{AbstractVector,Many,Nothing}, x)
  for y in items(xs); y == x && return true; end
  false
end
function index_of(s::AbstractString, x)
  r = Base.findfirst(str(x), s)
  r === nothing && return nothing
  Float64(Base.length(s, 1, Base.prevind(s, Base.first(r))))
end
function index_of(xs::Union{AbstractVector,Many,Nothing}, x)
  l = items(xs)
  for i in Base.eachindex(l); l[i] == x && return Float64(Base.:-(i, 1)); end
  nothing
end
join(xs::Union{AbstractVector,Many,Nothing,AbstractString}, sep) = Base.join((str(x) for x in items(xs)), str(sep))
first(s::AbstractString) = Base.isempty(s) ? nothing : Base.string(Base.first(s))
first(xs::Union{AbstractVector,Many,Nothing}) = (l = items(xs); Base.isempty(l) ? nothing : l[1])
last(s::AbstractString) = Base.isempty(s) ? nothing : Base.string(Base.last(s))
last(xs::Union{AbstractVector,Many,Nothing}) = (l = items(xs); Base.isempty(l) ? nothing : l[end])
empty(xs::Union{AbstractVector,AbstractString,Many}) = Base.:(==)(length(xs), 0.0)
function take(xs::Union{AbstractVector,AbstractString,Many,Nothing}, c)
  n = index_int(c)
  if xs isa AbstractString
    return Base.:<=(n, 0) ? "" : String(Base.first(xs, n))
  end
  l = items(xs)
  l[1:Base.clamp(n, 0, Base.length(l))]
end
function drop(xs::Union{AbstractVector,AbstractString,Many,Nothing}, c)
  n = index_int(c)
  if xs isa AbstractString
    Base.:<=(n, 0) && return String(xs)
    i = Base.nextind(xs, 0, Base.:+(n, 1))
    return Base.:>(i, Base.ncodeunits(xs)) ? "" : String(xs[i:end])
  end
  l = items(xs)
  l[Base.:+(Base.clamp(n, 0, Base.length(l)), 1):end]
end
rest(xs::Union{AbstractVector,AbstractString,Many,Nothing}) = drop(xs, 1.0)
concat(s::AbstractString, y) = Base.:*(String(s), str(y))
concat(xs::Union{AbstractVector,Many,Nothing}, ys) = Base.vcat(items(xs), items(ys))
reverse(s::AbstractString) = Base.reverse(s)
reverse(xs::Union{AbstractVector,Many,Nothing}) = Base.reverse(items(xs))
function sum(xs::Union{AbstractVector,Many,Nothing})
  s = 0.0
  for x in items(xs); s = Base.:+(s, num(x)); end
  s
end
function most(xs::Union{AbstractVector,Many,Nothing}, key)
  best = nothing; at_ = -1; bk = -Inf; l = items(xs)
  for i in Base.eachindex(l)
    k = num(key(l[i]))
    if best === nothing || Base.:>(k, bk); best = l[i]; at_ = Base.:-(i, 1); bk = k; end
  end
  best === nothing ? nothing : Any[best, Float64(at_)]
end
function sorted_by(xs::Union{AbstractVector,Many,Nothing}, key)
  l = items(xs)
  ks = Float64[num(key(x)) for x in l]
  p = Base.sortperm(Base.eachindex(l); by = i -> ks[i], alg = Base.MergeSort)
  Any[l[i] for i in p]
end
each(xs::Union{AbstractVector,AbstractString,Many,Nothing}) = Many(items(xs))
sqrt(x::Union{Real,Nothing}) = (v = num(x); Base.:<(v, 0) ? NaN : Base.sqrt(v))
floor(x::Union{Real,Nothing}) = Base.floor(num(x))
abs(x::Union{Real,Nothing}) = Base.abs(num(x))
magnitude(x::Union{Real,Nothing}) = Base.abs(num(x))
cos(x::Union{Real,Nothing}) = (v = num(x); Base.isfinite(v) ? Base.cos(v) : NaN)
sin(x::Union{Real,Nothing}) = (v = num(x); Base.isfinite(v) ? Base.sin(v) : NaN)
round(x::Union{Real,Nothing}) = Base.floor(Base.:+(num(x), 0.5))
ln(x::Union{Real,Nothing}) = (v = num(x); Base.:<(v, 0) ? NaN : Base.log(v))
exp(x::Union{Real,Nothing}) = Base.exp(num(x))
atan2(x::Union{Real,Nothing}, y) = Base.atan(num(x), num(y))
pow(x::Union{Real,Nothing}, y) = pw(num(x), num(y))
blank(c::Union{Real,Nothing}) = (d = num(c); Base.:(==)(d, 32) || Base.:(==)(d, 9) || Base.:(==)(d, 10) || Base.:(==)(d, 13))
negated(x::Union{Real,Nothing}) = Base.:-(num(x))

end # module Ops

# a member named like one of the Ray-facing functions extends it: it has its fallback already
union!(DECLARED, (n for n in names(Ops) if n !== :Ops))

end # module Rt
