-- GENERATED by `npx ray gen` from implementation/physics.ray - do not edit
import OrbitMines.Physics.Globals
set_option linter.unusedVariables false
set_option autoImplicit false
set_option maxHeartbeats 0
set_option maxRecDepth 100000
namespace OrbitMines.Physics


namespace Rates
ray_impl_field "nu" : Float := do
  return ωnull
ray_impl_field "sigma" : Float := do
  return ωnull
ray_impl_field "F" : Float := do
  return ωnull
ray_impl_field "DEG" : Float := do
  return ωnull
ray_impl_field "D" : Float := do
  return ωnull
ray_impl_field "g" : Float := do
  return (0 : Float)
end Rates



end OrbitMines.Physics
