-- GENERATED by `npx ray gen` from implementation/physics.ray - do not edit
import OrbitMines.Physics.Globals
set_option linter.unusedVariables false
set_option autoImplicit false
set_option maxHeartbeats 0
set_option maxRecDepth 100000
namespace OrbitMines.Physics


namespace Orbit
ray_impl_field "N" : Float := do
  return ωnull
ray_impl_field "A" : Float := do
  return ωnull
ray_impl_field "K" : Float := do
  return ωnull
ray_impl_field "ticks" : Float := do
  return ωnull
ray_impl_field "mx" : Float := do
  return ωnull
ray_impl_field "ways" : Float := do
  return ωnull
ray_impl_field "R" : Float := do
  return ωnull
ray_impl_field "lo" : Float := do
  return ωnull
ray_impl_field "hi" : Float := do
  return ωnull
ray_impl_field "steps" : Float := do
  return ωnull
ray_impl_field "held_mx" : Float := do
  return ωnull
ray_impl_field "held_ways" : Float := do
  return ωnull
ray_impl_field "mode" : String := do
  return ("fall" : String)
ray_impl_field "burn" : Float := do
  return (0 : Float)
ray_impl_field "alone" : Bool := do
  return false
end Orbit



end OrbitMines.Physics
