-- GENERATED by `npx ray gen` from implementation/physics.ray - do not edit
import OrbitMines.Physics.Runtime
set_option linter.unusedVariables false
set_option maxHeartbeats 0
set_option maxRecDepth 100000
open Rt


namespace C_Still
def thisClass : String := "Still"
initialize defineClass thisClass "Painter"
initialize fieldNone thisClass "paints"
initialize method thisClass "frame" (fun self a1 => do
  let s_0 ← IO.mkRef (arg a1 0)
  let dt_0 ← IO.mkRef (arg a1 1)
  if true then return (← cm self "paints" #[(← s_0.get)])
  return Value.null)
end C_Still


