-- GENERATED by `npx ray gen` from implementation/physics.ray - do not edit
import OrbitMines.Physics.Runtime
set_option linter.unusedVariables false
set_option maxHeartbeats 0
set_option maxRecDepth 100000
open Rt


namespace C_Law
def thisClass : String := "Law"
initialize defineClass thisClass "Node"
initialize staticField thisClass "CACHE" (fun self => do
  return (← mk "Node" #[]))
initialize statik thisClass "law" (fun self a1 => do
  if truthy (← eqV (← gm (← gm (← K "Law") "CACHE") (← strv (Value.str ("law")))) Value.null) then
    (← smV (← gm (← K "Law") "CACHE") (← strv (Value.str ("law"))) (← cm (← K "Measured") "of" #[(Value.str ("law"))])) |> sink
    pure ()
  if truthy (← eqV (← gm (← gm (← K "Law") "CACHE") (← strv (Value.str ("law")))) Value.null) then
    (← inv fail #[(Value.str ("law is not on disk - run `npx ray measure` and try again"))]) |> sink
    pure ()
  if true then return (← gm (← gm (← K "Law") "CACHE") (← strv (Value.str ("law"))))
  return Value.null)
initialize statik thisClass "a0" (fun self a1 => do
  if true then return (← gm (← gm (← gm (← K "Law") "law") "header") (← strv (Value.str ("a0"))))
  return Value.null)
initialize statik thisClass "carries" (fun self a1 => do
  if true then return (← orElse (← gm (← gm (← gm (← K "Law") "law") "header") (← strv (Value.str ("carries")))) (do pure (Value.num 0)))
  return Value.null)
initialize statik thisClass "theory" (fun self a1 => do
  if true then return (← orElse (← gm (← gm (← gm (← K "Law") "law") "header") (← strv (Value.str ("theory")))) (do pure (Value.str ("G"))))
  return Value.null)
initialize statik thisClass "boost" (fun self a1 => do
  let gN_0 ← IO.mkRef (arg a1 0)
  let scale_0 ← IO.mkRef (arg a1 1)
  let A0_0 ← IO.mkRef Value.null
  A0_0.set ((← gm (← K "Law") "a0") : Value)
  let xs__0 ← IO.mkRef Value.null
  xs__0.set ((← gm (← gm (← gm (← K "Law") "law") "columns") (← strv (Value.str ("gN")))) : Value)
  let ys__0 ← IO.mkRef Value.null
  ys__0.set ((← gm (← gm (← gm (← K "Law") "law") "columns") (← strv (Value.str ("g")))) : Value)
  let want_0 ← IO.mkRef Value.null
  want_0.set ((← mulV ((← divV (← gN_0.get) (← scale_0.get))) (← A0_0.get)) : Value)
  let lo_0 ← IO.mkRef Value.null
  lo_0.set ((Value.num 0) : Value)
  let hi_0 ← IO.mkRef Value.null
  hi_0.set ((← subV (← gm (← gm (← K "Law") "law") "rows") (Value.num 1)) : Value)
  if truthy (← leV (← want_0.get) (← elemv (← xs__0.get) (Value.num 0))) then
    if true then return (← mulV ((← divV (← elemv (← ys__0.get) (Value.num 0)) (← A0_0.get))) (← scale_0.get))
    pure ()
  if truthy (← geV (← want_0.get) (← elemv (← xs__0.get) (← hi_0.get))) then
    if true then return (← mulV ((← divV (← elemv (← ys__0.get) (← hi_0.get)) (← A0_0.get))) (← scale_0.get))
    pure ()
  while truthy (← gtV (← subV (← hi_0.get) (← lo_0.get)) (Value.num 1)) do
    let mid_0 ← IO.mkRef Value.null
    mid_0.set ((← m_floor ((← divV ((← addV (← lo_0.get) (← hi_0.get))) (Value.num 2)))) : Value)
    if truthy (← leV (← elemv (← xs__0.get) (← mid_0.get)) (← want_0.get)) then
      (← wr lo_0 (← mid_0.get)) |> sink
      pure ()
    else
      (← wr hi_0 (← mid_0.get)) |> sink
      pure ()
    pure ()
  let t_0 ← IO.mkRef Value.null
  t_0.set ((← divV ((← subV (← m_ln (← want_0.get)) (← m_ln (← elemv (← xs__0.get) (← lo_0.get))))) ((← subV (← m_ln (← elemv (← xs__0.get) (← hi_0.get))) (← m_ln (← elemv (← xs__0.get) (← lo_0.get)))))) : Value)
  if true then return (← mulV ((← divV (← m_exp ((← addV (← m_ln (← elemv (← ys__0.get) (← lo_0.get))) (← mulV (← t_0.get) ((← subV (← m_ln (← elemv (← ys__0.get) (← hi_0.get))) (← m_ln (← elemv (← ys__0.get) (← lo_0.get))))))))) (← A0_0.get))) (← scale_0.get))
  return Value.null)
end C_Law


