-- GENERATED by `npx ray gen` from implementation/physics.ray - do not edit
import OrbitMines.Physics.Globals
set_option linter.unusedVariables false
set_option autoImplicit false
set_option maxHeartbeats 0
set_option maxRecDepth 100000
namespace OrbitMines.Physics


namespace Solve
ray_impl_static "settles" (R_0 : Rates) : Float := do
  let a_0 ← IO.mkRef (← ωmul (← ωget (← R_0.get) "sigma") (← ωget (← R_0.get) "F"))
  let b_0 ← IO.mkRef (← ωget (← R_0.get) "nu")
  let c_0 ← IO.mkRef (← ωneg (← ωget (← R_0.get) "nu"))
  if ωtruthy (← ωeqv (← a_0.get) (0 : Float)) then
    if true then return (1 : Float)
    pure ()
  if true then return (← ωdiv ((← ωadd (← ωneg (← b_0.get)) (← dot! ((← ωsub (← ωmul (← b_0.get) (← b_0.get)) (← ωmul (← ωmul (4 : Float) (← a_0.get)) (← c_0.get)))) rsqrt ()))) ((← ωmul (2 : Float) (← a_0.get))))
  return ωnull
ray_impl_static "root" (s_0 : object) (name_0 : String) (f_0 : Value) : Float := do
  let had_0 ← IO.mkRef (← ωelem (← s_0.get) (← name_0.get))
  let at__0 ← IO.mkRef ωnull
  at__0.set (fn! [(x : Float)] do
      (ωatSetter (← s_0.get) (← name_0.get)) x
      if true then return (← app! (← f_0.get) ((← s_0.get)))
      return ωnull)
  let lo_0 ← IO.mkRef (0 : Float)
  let hi_0 ← IO.mkRef (1 : Float)
  let flo_0 ← IO.mkRef (← app! (← at__0.get) ((← lo_0.get)))
  let fhi_0 ← IO.mkRef (← app! (← at__0.get) ((← hi_0.get)))
  if ωtruthy (← ωgt (← ωmul (← flo_0.get) (← fhi_0.get)) (0 : Float)) then
    (ωatSetter (← s_0.get) (← name_0.get)) (← had_0.get)
    if true then return (← ωtern (ωtruthy (← ωlt (← dot! (← flo_0.get) rabs ()) (← dot! (← fhi_0.get) rabs ()))) (do pure (← lo_0.get)) (do pure (← hi_0.get)))
    pure ()
  let i_0 ← IO.mkRef (0 : Float)
  while ωtruthy (← ωlt (← i_0.get) (60 : Float)) do
    let mid_0 ← IO.mkRef (← ωdiv ((← ωadd (← lo_0.get) (← hi_0.get))) (2 : Float))
    let fm_0 ← IO.mkRef (← app! (← at__0.get) ((← mid_0.get)))
    if ωtruthy (← ωle (← ωmul (← fm_0.get) (← flo_0.get)) (0 : Float)) then
      (← ωwr hi_0 (← mid_0.get)) |> ωsink
      pure ()
    else
      (← ωwr lo_0 (← mid_0.get)) |> ωsink
      (← ωwr flo_0 (← fm_0.get)) |> ωsink
      pure ()
    (← ωwr i_0 (← ωadd (← i_0.get) (1 : Float))) |> ωsink
    pure ()
  (ωatSetter (← s_0.get) (← name_0.get)) (← had_0.get)
  if true then return (← ωdiv ((← ωadd (← lo_0.get) (← hi_0.get))) (2 : Float))
  return ωnull
ray_impl_static "sweep" (R_0 : Rates) (geometry_0 : Geometry) (radius_0 : Float) (size_0 : Float := ωnull) (passes_0 : Float := ωnull) (tol_0 : Float := ωnull) : Grid := do
  if ωtruthy (ωisNull (← size_0.get)) then
    (← ωwr size_0 (41 : Float)) |> ωsink
    pure ()
  if ωtruthy (ωisNull (← passes_0.get)) then
    (← ωwr passes_0 (400 : Float)) |> ωsink
    pure ()
  if ωtruthy (ωisNull (← tol_0.get)) then
    (← ωwr tol_0 0.000000000001) |> ωsink
    pure ()
  let L_0 ← IO.mkRef (← size_0.get)
  let D_0 ← IO.mkRef (← ωget (← geometry_0.get) "D")
  let rho_0 ← IO.mkRef (← call! (← cls% Solve) "settles" ((← R_0.get)))
  let c_0 ← IO.mkRef (← ωdiv (← ωsub (← L_0.get) (1 : Float)) (2 : Float))
  let cells_0 ← IO.mkRef (← ωpow (← L_0.get) (← D_0.get))
  let stride_0 ← IO.mkRef (← dot! (← ωrrange (← D_0.get)) rmap ((fn! [i_2] do
    if true then return (← ωpow (← L_0.get) (← i_2.get))
    return ωnull)))
  let step_0 ← IO.mkRef (← dot! (← ωget (← geometry_0.get) "offsets") rmap ((fn! [v_2] do
    if true then return (← dot! (← ωget (← v_2.get) "components") rmap ((fn! [x_4] do
      if true then return (← dot! (← x_4.get) rround ())
      return ωnull)))
    return ωnull)))
  let M_0 ← IO.mkRef (← dot! (← step_0.get) rlength ())
  let shift_0 ← IO.mkRef (← dot! (← step_0.get) rmap ((fn! [v_2] do
    if true then return (← dot! (← dot! (← ωrrange (← D_0.get)) rmap ((fn! [i_4] do
      if true then return (← ωmul (← ωelem (← v_2.get) (← i_4.get)) (← ωelem (← stride_0.get) (← i_4.get)))
      return ωnull))) rsum ())
    return ωnull)))
  let opp_0 ← IO.mkRef (← dot! (← step_0.get) rmap ((fn! [v_2] do
    if true then return (← ωorElse (← dot! (← step_0.get) rindex_of ((← dot! (← v_2.get) rmap ((fn! [x_4] do
      if true then return (← ωsub (0 : Float) (← x_4.get))
      return ωnull))))) (do pure (← ωneg (1 : Float))))
    return ωnull)))
  let coord_0 ← IO.mkRef ωnull
  coord_0.set (fn! [(k : Float)] do
      if true then return (← dot! (← ωrrange (← D_0.get)) rmap ((fn! [i_2] do
        if true then return (← ωmodv (← dot! ((← ωdiv k (← ωelem (← stride_0.get) (← i_2.get)))) rfloor ()) (← L_0.get))
        return ωnull)))
      return ωnull)
  let is_matter_0 ← IO.mkRef (← dot! (← ωrrange (← cells_0.get)) rmap ((fn! [k_2] do
    let p_2 ← IO.mkRef (← app! (← coord_0.get) ((← k_2.get)))
    if true then return (← ωle (← dot! ((← dot! (← dot! (← ωrrange (← D_0.get)) rmap ((fn! [i_4] do
      if true then return (← ωpow ((← ωsub (← ωelem (← p_2.get) (← i_4.get)) (← c_0.get))) (2 : Float))
      return ωnull))) rsum ())) rsqrt ()) (← radius_0.get))
    return ωnull)))
  let n_0 ← IO.mkRef (← ωrfilled (← ωmul (← cells_0.get) (← M_0.get)) (← ωdiv (← rho_0.get) (← M_0.get)))
  let next_0 ← IO.mkRef (← ωrfilled (← ωmul (← cells_0.get) (← M_0.get)) (0 : Float))
  let s_0 ← IO.mkRef (← ωrfilled (← cells_0.get) (1 : Float))
  let settled_0 ← IO.mkRef false
  let done_0 ← IO.mkRef (0 : Float)
  while ωtruthy (← ωandV (← ωlt (← done_0.get) (← passes_0.get)) (do pure (ωnotV (← settled_0.get)))) do
    for i1 in [0:ωrangeN (← ωmul (← cells_0.get) (← M_0.get))] do
      let i_1 ← IO.mkRef (ωnatF i1)
      (ωatSetter (← next_0.get) (← i_1.get)) (0 : Float)
      pure ()
    Value.null |> ωsink
    let moved_0 ← IO.mkRef (0 : Float)
    for i1 in [0:ωrangeN (← cells_0.get)] do
      let k_1 ← IO.mkRef (ωnatF i1)
      let tot_1 ← IO.mkRef (← dot! (← dot! (← ωrrange (← M_0.get)) rmap ((fn! [d_3] do
        if true then return (← ωelem (← n_0.get) (← ωadd (← ωmul (← k_1.get) (← M_0.get)) (← d_3.get)))
        return ωnull))) rsum ())
      let made_1 ← IO.mkRef (← ωtern (ωtruthy (← ωelem (← is_matter_0.get) (← k_1.get))) (do pure (0 : Float)) (do pure (← ωmul (← ωget (← R_0.get) "nu") ((← ωtern (ωtruthy (← ωgt (← ωsub (1 : Float) (← tot_1.get)) (0 : Float))) (do pure (← ωsub (1 : Float) (← tot_1.get))) (do pure (0 : Float)))))))
      let sp_1 ← IO.mkRef (← ωdiv (1 : Float) (← ωelem (← s_0.get) (← k_1.get)))
      for i2 in [0:ωrangeN (← M_0.get)] do
        let d_2 ← IO.mkRef (ωnatF i2)
        let here_2 ← IO.mkRef (← ωelem (← n_0.get) (← ωadd (← ωmul (← k_1.get) (← M_0.get)) (← d_2.get)))
        let facing_2 ← IO.mkRef (← ωelem (← n_0.get) (← ωadd (← ωmul (← k_1.get) (← M_0.get)) ((← ωtern (ωtruthy (← ωlt (← ωelem (← opp_0.get) (← d_2.get)) (0 : Float))) (do pure (← d_2.get)) (do pure (← ωelem (← opp_0.get) (← d_2.get)))))))
        let killed_2 ← IO.mkRef (← ωmul (← ωmul (← ωmul (← ωmul (← ωget (← R_0.get) "sigma") ((← ωsub (1 : Float) (← ωget (← R_0.get) "g")))) (← here_2.get)) (← facing_2.get)) (← ωget (← R_0.get) "F"))
        let left_2 ← IO.mkRef (← ωsub (← ωsub (← ωadd (← here_2.get) (← ωdiv (← made_1.get) (← M_0.get))) (← killed_2.get)) ((← ωtern (ωtruthy (← ωelem (← is_matter_0.get) (← k_1.get))) (do pure (← here_2.get)) (do pure (0 : Float)))))
        (← ωwr left_2 (← ωtern (ωtruthy (← ωlt (← left_2.get) (0 : Float))) (do pure (0 : Float)) (do pure (← left_2.get)))) |> ωsink
        let p_2 ← IO.mkRef (← app! (← coord_0.get) ((← k_1.get)))
        let inside_2 ← IO.mkRef (← dot! (← ωrrange (← D_0.get)) revery ((fn! [i_4] do
          if true then return (← ωandV (← ωge (← ωadd (← ωelem (← p_2.get) (← i_4.get)) (← ωelem (← ωelem (← step_0.get) (← d_2.get)) (← i_4.get))) (0 : Float)) (do pure (← ωlt (← ωadd (← ωelem (← p_2.get) (← i_4.get)) (← ωelem (← ωelem (← step_0.get) (← d_2.get)) (← i_4.get))) (← L_0.get))))
          return ωnull)))
        if ωtruthy (← inside_2.get) then
          (ωatSetter (← next_0.get) (← ωadd (← ωmul ((← ωadd (← k_1.get) (← ωelem (← shift_0.get) (← d_2.get)))) (← M_0.get)) (← d_2.get))) (← ωadd (← ωelem (← next_0.get) (← ωadd (← ωmul ((← ωadd (← k_1.get) (← ωelem (← shift_0.get) (← d_2.get)))) (← M_0.get)) (← d_2.get))) (← ωmul (← left_2.get) (← sp_1.get)))
          (ωatSetter (← next_0.get) (← ωadd (← ωmul (← k_1.get) (← M_0.get)) (← d_2.get))) (← ωadd (← ωelem (← next_0.get) (← ωadd (← ωmul (← k_1.get) (← M_0.get)) (← d_2.get))) (← ωmul (← left_2.get) ((← ωsub (1 : Float) (← sp_1.get)))))
          pure ()
        pure ()
      Value.null |> ωsink
      pure ()
    Value.null |> ωsink
    for i1 in [0:ωrangeN (← ωmul (← cells_0.get) (← M_0.get))] do
      let i_1 ← IO.mkRef (ωnatF i1)
      let delta_1 ← IO.mkRef (← dot! ((← ωsub (← ωelem (← next_0.get) (← i_1.get)) (← ωelem (← n_0.get) (← i_1.get)))) rabs ())
      if ωtruthy (← ωgt (← delta_1.get) (← moved_0.get)) then
        (← ωwr moved_0 (← delta_1.get)) |> ωsink
        pure ()
      (ωatSetter (← n_0.get) (← i_1.get)) (← ωelem (← next_0.get) (← i_1.get))
      pure ()
    Value.null |> ωsink
    (← ωwr settled_0 (← ωlt (← moved_0.get) (← tol_0.get))) |> ωsink
    (← ωwr done_0 (← ωadd (← done_0.get) (1 : Float))) |> ωsink
    pure ()
  let dens_0 ← IO.mkRef (← dot! (← ωrrange (← cells_0.get)) rmap ((fn! [k_2] do
    if true then return (← dot! (← dot! (← ωrrange (← M_0.get)) rmap ((fn! [d_4] do
      if true then return (← ωelem (← n_0.get) (← ωadd (← ωmul (← k_2.get) (← M_0.get)) (← d_4.get)))
      return ωnull))) rsum ())
    return ωnull)))
  let imbalance_0 ← IO.mkRef (← dot! (← ωrrange (← cells_0.get)) rmap ((fn! [k_2] do
    let p_2 ← IO.mkRef (← app! (← coord_0.get) ((← k_2.get)))
    let f_2 ← IO.mkRef (← dot! (← ωrrange (← D_0.get)) rmap ((fn! [i_4] do
      if true then return (← dot! (← dot! (← ωrrange (← M_0.get)) rmap ((fn! [d_6] do
        if true then return (← ωmul (← ωelem (← n_0.get) (← ωadd (← ωmul (← k_2.get) (← M_0.get)) (← d_6.get))) (← ωelem (← ωelem (← step_0.get) (← d_6.get)) (← i_4.get)))
        return ωnull))) rsum ())
      return ωnull)))
    let r_2 ← IO.mkRef (← dot! (← ωrrange (← D_0.get)) rmap ((fn! [i_4] do
      if true then return (← ωsub (← c_0.get) (← ωelem (← p_2.get) (← i_4.get)))
      return ωnull)))
    let norm_2 ← IO.mkRef (← dot! ((← dot! (← dot! (← r_2.get) rmap ((fn! [x_4] do
      if true then return (← ωmul (← x_4.get) (← x_4.get))
      return ωnull))) rsum ())) rsqrt ())
    if true then return (← ωdiv ((← dot! (← dot! (← ωrrange (← D_0.get)) rmap ((fn! [i_4] do
      if true then return (← ωmul (← ωelem (← f_2.get) (← i_4.get)) (← ωelem (← r_2.get) (← i_4.get)))
      return ωnull))) rsum ())) ((← ωtern (ωtruthy (← ωgt (← norm_2.get) (0 : Float))) (do pure (← norm_2.get)) (do pure (1 : Float)))))
    return ωnull)))
  if true then return (← new! Grid («L» := (← L_0.get), «n» := (← dens_0.get), «s» := (← s_0.get), «rho» := (← rho_0.get), «passes» := (← done_0.get), «settled» := (← settled_0.get), «imbalance» := (← imbalance_0.get)))
  return ωnull
end Solve



end OrbitMines.Physics
