-- GENERATED by `npx ray gen` from implementation/physics.ray - do not edit
import OrbitMines.Physics.Globals
set_option linter.unusedVariables false
set_option autoImplicit false
set_option maxHeartbeats 0
set_option maxRecDepth 100000
namespace OrbitMines.Physics


namespace Around
ray_impl_field "geometry" : Geometry := do
  return ωnull
ray_impl_field "DEG" : Float := do
  return ωnull
end Around



end OrbitMines.Physics
