-- GENERATED by `npx ray gen` from implementation/physics.ray - do not edit
import OrbitMines.Physics.Runtime
set_option linter.unusedVariables false
set_option maxHeartbeats 0
set_option maxRecDepth 100000
open Rt


namespace C_FieldPainter
def thisClass : String := "FieldPainter"
initialize defineClass thisClass "Painter"
initialize fieldNone thisClass "p"
initialize fieldNone thisClass "played"
initialize field thisClass "at_frame" (fun self => do
  return (Value.num 0))
initialize field thisClass "accumulated" (fun self => do
  return (← filled (← mulV (← gm (← gm self "p") "box_side") (← gm (← gm self "p") "box_side")) (Value.num 0)))
initialize field thisClass "count" (fun self => do
  return (Value.num 0))
initialize field thisClass "trail" (fun self => do
  return (← m_map (← rng (← gm (← gm self "p") "bodies")) #[(mkFn (fun a2 => do
  let k_1 ← IO.mkRef (arg a2 0)
  if true then return (← lst #[])
  return Value.null))]))
initialize method thisClass "frame" (fun self a1 => do
  let s_0 ← IO.mkRef (arg a1 0)
  let dt_0 ← IO.mkRef (arg a1 1)
  let ch_0 ← IO.mkRef Value.null
  ch_0.set ((← tern (← eqV (← gm self "played") Value.null) (do pure (← mk "Node" #[])) (do pure (← cm (← gm self "played") "at" #[(← gm self "at_frame")]))) : Value)
  if truthy (← neV (← gm (← ch_0.get) (← strv (Value.str ("one")))) Value.null) then
    let gone_0 ← IO.mkRef Value.null
    gone_0.set ((← gm (← ch_0.get) (← strv (Value.str ("gone")))) : Value)
    for i1 in [0:rangeN (← lenOf (← gm self "accumulated"))] do
      let i_1 ← IO.mkRef (Value.num (natF i1))
      setAt (← gm self "accumulated") (← i_1.get) (← addV (← elemv (← gm self "accumulated") (← i_1.get)) (← elemv (← gone_0.get) (← i_1.get)))
      pure ()
    Value.null |> sink
    sm self "count" (← addV (← gm self "count") (Value.num 1))
    let marks_0 ← IO.mkRef Value.null
    marks_0.set ((← gm (← ch_0.get) (← strv (Value.str ("marks")))) : Value)
    for i1 in [0:rangeN (← gm (← gm self "p") "bodies")] do
      let k_1 ← IO.mkRef (Value.num (natF i1))
      (← m_push (← elemv (← gm self "trail") (← k_1.get)) #[(← elemv (← marks_0.get) (← mulV (← k_1.get) (Value.num 6)))]) |> sink
      (← m_push (← elemv (← gm self "trail") (← k_1.get)) #[(← elemv (← marks_0.get) (← addV (← mulV (← k_1.get) (Value.num 6)) (Value.num 1)))]) |> sink
      pure ()
    Value.null |> sink
    (← cm (← K "Panel") "paint" #[(← gm self "p"), (← s_0.get), (← ch_0.get), (← mulV (← gm self "at_frame") (← gm (← gm self "p") "TICKS")), (← gm self "accumulated"), (← gm self "count"), (← gm self "trail")]) |> sink
    pure ()
  sm self "at_frame" (← addV (← gm self "at_frame") (Value.num 1))
  return Value.null)
end C_FieldPainter


