-- GENERATED by `npx ray gen` from implementation/physics.ray - do not edit
import OrbitMines.Physics.Globals
set_option linter.unusedVariables false
set_option autoImplicit false
set_option maxHeartbeats 0
set_option maxRecDepth 100000
namespace OrbitMines.Physics


namespace Theory
ray_impl_field "name" : String := do
  return ωnull
ray_impl_field "rules" : (RList Rule) := do
  return (← ωlst #[])
ray_impl_field "visuals" : (RList Visual) := do
  return (← ωlst #[])
ray_impl_field "theorems" : (RList Theorem) := do
  return (← ωlst #[])
ray_impl_field "carried" : (RList String) := do
  return (← ωlst #[])
ray_impl_getter "lattice" : Geometry := do
  if true then return ωnull
  return ωnull
ray_impl_method "seed" (geometry_0 : Geometry) (N_0 : Float) (seed_0 : Float := ωnull) (bound_0 : Float := ωnull) (margin_0 : Float := ωnull) : World := do
  if ωtruthy (ωisNull (← seed_0.get)) then
    (← ωwr seed_0 (0 : Float)) |> ωsink
    pure ()
  if ωtruthy (ωisNull (← bound_0.get)) then
    (← ωwr bound_0 (250000 : Float)) |> ωsink
    pure ()
  if ωtruthy (ωisNull (← margin_0.get)) then
    (← ωwr margin_0 (0 : Float)) |> ωsink
    pure ()
  if true then return (← ωget (← new! World («theory» := self, «geometry» := (← geometry_0.get), «N» := (← N_0.get), «seed» := (← seed_0.get), «bound» := (← bound_0.get), «margin» := (← margin_0.get))) "laid")
  return ωnull
ray_impl_getter "equation" : Equation := do
  if true then return (← new! Equation («theory» := self))
  return ωnull
ray_impl_method "field" (N_0 : Float) (A_0 : Float := ωnull) (K_0 : Float := ωnull) (seed_0 : Float := ωnull) (DEG_0 : Float := ωnull) (tags_0 : Float := ωnull) : Field := do
  if ωtruthy (ωisNull (← A_0.get)) then
    (← ωwr A_0 (96 : Float)) |> ωsink
    pure ()
  if ωtruthy (ωisNull (← K_0.get)) then
    (← ωwr K_0 (4 : Float)) |> ωsink
    pure ()
  if ωtruthy (ωisNull (← seed_0.get)) then
    (← ωwr seed_0 (0 : Float)) |> ωsink
    pure ()
  if ωtruthy (ωisNull (← DEG_0.get)) then
    (← ωwr DEG_0 (8 : Float)) |> ωsink
    pure ()
  if ωtruthy (ωisNull (← tags_0.get)) then
    (← ωwr tags_0 (1 : Float)) |> ωsink
    pure ()
  if true then return (← new! Field («theory» := self, «N» := (← N_0.get), «A» := (← A_0.get), «K» := (← K_0.get), «seed» := (← seed_0.get), «tags» := (← tags_0.get), «DEG» := (← DEG_0.get)))
  return ωnull
ray_impl_method "medium" (N_0 : Float) (A_0 : Float := ωnull) (K_0 : Float := ωnull) (DEG_0 : Float := ωnull) (tags_0 : Float := ωnull) (D_0 : Float := ωnull) : Medium := do
  if ωtruthy (ωisNull (← A_0.get)) then
    (← ωwr A_0 (96 : Float)) |> ωsink
    pure ()
  if ωtruthy (ωisNull (← K_0.get)) then
    (← ωwr K_0 (3 : Float)) |> ωsink
    pure ()
  if ωtruthy (ωisNull (← DEG_0.get)) then
    (← ωwr DEG_0 ωnull) |> ωsink
    pure ()
  if ωtruthy (ωisNull (← tags_0.get)) then
    (← ωwr tags_0 (1 : Float)) |> ωsink
    pure ()
  if ωtruthy (ωisNull (← D_0.get)) then
    (← ωwr D_0 ωnull) |> ωsink
    pure ()
  if true then return (← new! Medium («theory» := self, «N» := (← N_0.get), «A» := (← A_0.get), «K» := (← K_0.get), «DEG» := (← ωorElse (← DEG_0.get) (do pure (← ωget (← ωget self "lattice") "DEG"))), «tags» := (← tags_0.get), «D» := (← ωorElse (← D_0.get) (do pure (← ωget (← ωget self "lattice") "D")))))
  return ωnull
ray_impl_getter "proved" : Proof := do
  if ωtruthy (ωisNull (← ωelem (← ωget (← cls% Prover) "PROOFS") (← ωget self "name"))) then
    (ωatSetter (← ωget (← cls% Prover) "PROOFS") (← ωget self "name")) (← ωget (← new! Prover («theory» := self)) "proof")
    pure ()
  if true then return (← ωelem (← ωget (← cls% Prover) "PROOFS") (← ωget self "name"))
  return ωnull
end Theory



end OrbitMines.Physics
