-- GENERATED by `npx ray gen` from implementation/physics.ray - do not edit
import OrbitMines.Physics.Globals
set_option linter.unusedVariables false
set_option autoImplicit false
set_option maxHeartbeats 0
set_option maxRecDepth 100000
namespace OrbitMines.Physics


namespace Budget
ray_impl_field "memory" : Float := do
  return (0 : Float)
ray_impl_field "binding" : Float := do
  return (0 : Float)
ray_impl_field "aim_ms" : Float := do
  return (15 : Float)
ray_impl_field "longest_ms" : Float := do
  return (250 : Float)
ray_impl_field "duty" : Float := do
  return 0.5
ray_impl_field "in_flight" : Float := do
  return (2 : Float)
ray_impl_field "host" : Float := do
  return (0 : Float)
ray_impl_field "compact" : Bool := do
  return false
end Budget



end OrbitMines.Physics
