-- GENERATED by `npx ray gen` from implementation/physics.ray - do not edit
import OrbitMines.Physics.Globals
set_option linter.unusedVariables false
set_option autoImplicit false
set_option maxHeartbeats 0
set_option maxRecDepth 100000
namespace OrbitMines.Physics


namespace Vertex
ray_impl_field "world" : World := do
  return ωnull
ray_impl_field "at" : Vector := do
  return ωnull
ray_impl_field "ordinal" : Float := do
  return (0 : Float)
ray_impl_field "rays" : (RList Ray) := do
  return (← ωlst #[])
ray_impl_getter "exits" : (RList Boundary) := do
  if true then return (← dot! (← ωget self "rays") rmap ((fn! [r_2] do
    if true then return (← ωget (← r_2.get) "terminal")
    return ωnull)))
  return ωnull
ray_impl_field "source" : Source := do
  return ωnull
ray_impl_field "density" : Float := do
  return (1 : Float)
ray_impl_field "destroyed" : Float := do
  return (0 : Float)
ray_impl_field "folds" : (RList Float) := do
  return (← dot! (← ωget self "rays") rmap ((fn! [__1] do
  if true then return (0 : Float)
  return ωnull)))
ray_impl_field "held" : (RList Vertex) := do
  return (← ωlst #[])
ray_impl_field "folded_into" : Vertex := do
  return ωnull
ray_impl_getter "alive" : Bool := do
  if true then return (ωisNull (← ωget self "folded_into"))
  return ωnull
ray_impl_getter "busy" : Bool := do
  if true then return (← ωorV (!ωisNull (← ωget self "source")) (do pure (← dot! (← ωget self "rays") rsome ((fn! [r_2] do
    if true then return (← ωget (← r_2.get) "active")
    return ωnull)))))
  return ωnull
ray_impl_getter "neutral" : Bool := do
  if true then return (ωnotV (← ωget self "busy"))
  return ωnull
ray_impl_getter "vacuum" : Bool := do
  if true then return (ωisNull (← ωget self "source"))
  return ωnull
ray_impl_method "emits" (d_0 : Float) : Bool := do
  if true then return (← ωandV (!ωisNull (← ωget self "source")) (do pure (← call! (← ωget self "source") "emits" ((← d_0.get)))))
  return ωnull
ray_impl_method "outward" (d_0 : Float) : Vertex := do
  let there_0 ← IO.mkRef (← ωgetOpt (← ωget (← ωget (← ωelem (← ωget self "rays") (← d_0.get)) "terminal") "across") "vertex")
  if ωtruthy (ωisNull (← there_0.get)) then
    if true then return ωnull
    pure ()
  if ωtruthy (← ωget (← there_0.get) "alive") then
    if true then return (← there_0.get)
    pure ()
  if true then return (← ωtern (ωtruthy (← ωeqv (← ωget (← there_0.get) "folded_into") self)) (do pure (← call! (← there_0.get) "outward" ((← d_0.get)))) (do pure (← ωget (← there_0.get) "folded_into")))
  return ωnull
ray_impl_method "drift" (d_0 : Float) : Vector := do
  if true then return (← ωtern (ωtruthy (ωisNull (← ωget self "folded_into"))) (do pure (← call! (← cls% Vector) "zero" ((← dot! (← ωget (← ωget self "at") "components") rlength ())))) (do pure (← ωsub (← ωget (← ωget self "folded_into") "at") (← ωget self "at"))))
  return ωnull
ray_impl_getter "sinks" : Vector := do
  if true then return (← ωtern (ωtruthy (ωisNull (← ωget self "folded_into"))) (do pure (← call! (← cls% Vector) "zero" ((← dot! (← ωget (← ωget self "at") "components") rlength ())))) (do pure (← ωsub (← ωget (← ωget self "folded_into") "at") (← ωget self "at"))))
  return ωnull
ray_impl_method "fold" (b_0 : Vertex) : Value := do
  if ωtruthy (← ωeqv (← b_0.get) self) then
    if true then return ωnull
    pure ()
  let d_0 ← IO.mkRef (← dot! (← ωget self "rays") rindex_of ((← dot! (← dot! (← ωget self "rays") rfilter ((fn! [r_2] do
    if true then return (← ωeqv (← call! self "outward" ((← ωget (← r_2.get) "exit"))) (← b_0.get))
    return ωnull))) rfirst ())))
  if ωtruthy (!ωisNull (← d_0.get)) then
    (ωatSetter (← ωget self "folds") (← d_0.get)) (← ωadd (← ωelem (← ωget self "folds") (← d_0.get)) (1 : Float))
    pure ()
  (← call! self "hold" ((← b_0.get))) |> ωsink
  (ωsetter (← ωget self "world") "folded") (← ωadd (← ωget (← ωget self "world") "folded") (1 : Float))
  return ωnull
ray_impl_method "hold" (b_0 : Vertex) : Value := do
  (ωsetter self "density") (← ωadd (← ωget self "density") (← ωget (← b_0.get) "density"))
  (ωsetter (← b_0.get) "folded_into") self
  (ωsetter (← ωget self "world") "living") (← dot! (← ωget (← ωget self "world") "living") rfilter ((fn! [x_2] do
    if true then return (← ωnev (← x_2.get) (← b_0.get))
    return ωnull)))
  if true then return (← dot! (← ωget self "held") rpush ((← b_0.get)))
  return ωnull
ray_impl_method "move_to" (position_0 : Vector) : Value := do
  (← ωget self "unjoin") |> ωsink
  (← call! self "put" ((← position_0.get))) |> ωsink
  if true then return (← ωget self "join")
  return ωnull
ray_impl_method "put" (position_0 : Vector) : Value := do
  (ωatSetter (← ωget (← ωget self "world") "positions_index") (← ωget (← ωget self "at") "key")) (← ωtern (ωtruthy (← ωeqv (← ωelem (← ωget (← ωget self "world") "positions_index") (← ωget (← ωget self "at") "key")) self)) (do pure ωnull) (do pure (← ωelem (← ωget (← ωget self "world") "positions_index") (← ωget (← ωget self "at") "key"))))
  (← call! (← ωget self "world") "relocate" (self, (← position_0.get))) |> ωsink
  (ωatSetter (← ωget (← ωget self "world") "positions_index") (← ωget (← position_0.get) "key")) self
  return ωnull
ray_impl_method "swap" (b_0 : Vertex) : Value := do
  let here_0 ← IO.mkRef (← ωget self "at")
  let there_0 ← IO.mkRef (← ωget (← b_0.get) "at")
  (← ωget self "unjoin") |> ωsink
  (← ωget (← b_0.get) "unjoin") |> ωsink
  (← call! self "put" ((← there_0.get))) |> ωsink
  (← call! (← b_0.get) "put" ((← here_0.get))) |> ωsink
  (← ωget self "join") |> ωsink
  if true then return (← ωget (← b_0.get) "join")
  return ωnull
ray_impl_getter "unjoin" : Value := do
  for e1 in (← ωitems (← ωget self "rays")) do
    let r_1 ← IO.mkRef e1
    let other_1 ← IO.mkRef (← ωget (← ωget (← r_1.get) "terminal") "across")
    if ωtruthy (!ωisNull (← other_1.get)) then
      (ωsetter (← other_1.get) "edge") (← new! Edge («initial» := (← other_1.get)))
      pure ()
    (ωsetter (← ωget (← r_1.get) "terminal") "edge") (← new! Edge («initial» := (← ωget (← r_1.get) "terminal")))
    pure ()
  Value.null |> ωsink
  return ωnull
ray_impl_getter "join" : Value := do
  let g_0 ← IO.mkRef (← ωget (← ωget self "world") "geometry")
  for i1 in [0:ωrangeN (← ωget (← g_0.get) "DEG")] do
    let d_1 ← IO.mkRef (ωnatF i1)
    let there_1 ← IO.mkRef (← call! (← ωget self "world") "at" ((← ωadd (← ωget self "at") (← ωelem (← ωget (← g_0.get) "offsets") (← d_1.get)))))
    if ωtruthy (← ωandV (!ωisNull (← there_1.get)) (do pure (← ωnev (← there_1.get) self))) then
      (← call! (← new! Edge ()) "link" ((← ωget (← ωelem (← ωget self "rays") (← d_1.get)) "terminal"), (← ωget (← ωelem (← ωget (← there_1.get) "rays") (← call! (← g_0.get) "opposite" ((← d_1.get)))) "terminal"))) |> ωsink
      pure ()
    pure ()
  Value.null |> ωsink
  return ωnull
ray_impl_getter "unfold" : Vertex := do
  for e1 in (← ωitems (← ωget self "rays")) do
    let r_1 ← IO.mkRef e1
    if ωtruthy (← ωgt (← ωelem (← ωget self "folds") (← ωget (← r_1.get) "exit")) (0 : Float)) then
      (ωatSetter (← ωget self "folds") (← ωget (← r_1.get) "exit")) (← ωsub (← ωelem (← ωget self "folds") (← ωget (← r_1.get) "exit")) (1 : Float))
      pure ()
    pure ()
  Value.null |> ωsink
  let back_0 ← IO.mkRef (← dot! (← ωget self "held") rlast ())
  if ωtruthy (← ωandV (!ωisNull (← back_0.get)) (do pure (!ωisNull (← call! (← ωget self "world") "at" ((← ωget (← back_0.get) "at")))))) then
    if true then return ωnull
    pure ()
  if ωtruthy (!ωisNull (← back_0.get)) then
    (ωsetter self "held") (← dot! (← ωget self "held") rtake ((← ωsub (← dot! (← ωget self "held") rlength ()) (1 : Float))))
    (ωsetter (← back_0.get) "folded_into") ωnull
    (← dot! (← ωget (← ωget self "world") "living") rpush ((← back_0.get))) |> ωsink
    if ωtruthy (← ωgt (← ωget self "density") (1 : Float)) then
      (ωsetter self "density") (← ωsub (← ωget self "density") (1 : Float))
      pure ()
    if true then return (← back_0.get)
    pure ()
  if ωtruthy (ωnotV (← ωget (← ωget self "world") "expands")) then
    if true then return ωnull
    pure ()
  for e1 in (← ωitems (← ωget self "rays")) do
    let r_1 ← IO.mkRef e1
    if ωtruthy (ωisNull (← call! self "outward" ((← ωget (← r_1.get) "exit")))) then
      let made_1 ← IO.mkRef (← call! (← ωget self "world") "make" (self, (← ωget (← r_1.get) "exit")))
      if ωtruthy (!ωisNull (← made_1.get)) then
        if true then return (← made_1.get)
        pure ()
      pure ()
    pure ()
  Value.null |> ωsink
  if true then return ωnull
  return ωnull
ray_impl_getter "CREATE" : Value := do
  (← ωget self "unfold") |> ωsink
  (← ωget (← dot! (← ωget self "rays") reach ()) "activate") |> ωsink
  (ωsetter (← ωget self "world") "created") (← ωadd (← ωget (← ωget self "world") "created") (1 : Float))
  return ωnull
end Vertex



end OrbitMines.Physics
