-- GENERATED by `npx ray gen` from implementation/physics.ray - do not edit
import OrbitMines.Physics.Runtime
set_option linter.unusedVariables false
set_option maxHeartbeats 0
set_option maxRecDepth 100000
open Rt


namespace C_Braced
def thisClass : String := "Braced"
initialize defineClass thisClass "Node"
initialize fieldNone thisClass "body"
initialize fieldNone thisClass "end"
end C_Braced


