-- GENERATED by `npx ray gen` from implementation/physics.ray - do not edit
import OrbitMines.Physics.Runtime
set_option linter.unusedVariables false
set_option maxHeartbeats 0
set_option maxRecDepth 100000
open Rt


namespace C_Bodies
def thisClass : String := "Bodies"
initialize defineClass thisClass "Node"
initialize statik thisClass "begin" (fun self a1 => do
  let holes_0 ← IO.mkRef (arg a1 0)
  for e1 in (← itemsv (← holes_0.get)) do
    let h_1 ← IO.mkRef e1
    sm (← h_1.get) "stepped" (Value.bool false)
    sm (← h_1.get) "moved_along" Value.null
    pure ()
  Value.null |> sink
  return Value.null)
initialize statik thisClass "radiate" (fun self a1 => do
  let of_0 ← IO.mkRef (arg a1 0)
  let rules_0 ← IO.mkRef (arg a1 1)
  let holes_0 ← IO.mkRef (arg a1 2)
  let about_0 ← IO.mkRef Value.null
  about_0.set ((← m_filter (← rules_0.get) #[(mkFn (fun a3 => do
    let r_2 ← IO.mkRef (arg a3 0)
    if true then return (← eqV (← gm (← r_2.get) "over") (Value.str ("Boundary")))
    return Value.null))]) : Value)
  for e1 in (← itemsv (← about_0.get)) do
    let rule_1 ← IO.mkRef e1
    for e2 in (← itemsv (← holes_0.get)) do
      let h_2 ← IO.mkRef e2
      for e3 in (← itemsv (← gm (← h_2.get) "cells")) do
        let cell_3 ← IO.mkRef e3
        let here_3 ← IO.mkRef Value.null
        here_3.set ((← mk "Cell" #[(Value.kw "of" (← of_0.get)), (Value.kw "index" (← gm (← cell_3.get) "index"))]) : Value)
        for i4 in [0:rangeN (← gm (← gm (← of_0.get) "geometry") "DEG")] do
          let a_4 ← IO.mkRef (Value.num (natF i4))
          let beam_4 ← IO.mkRef Value.null
          beam_4.set ((← mk "Beam" #[(Value.kw "vertex" (← here_3.get)), (Value.kw "exit" (← a_4.get)), (Value.kw "count" (← cm (← of_0.get) "was_at" #[(← a_4.get), (← gm (← cell_3.get) "index")]))]) : Value)
          sm (← beam_4.get) "recoil" (← gm (← h_2.get) "per_way")
          let port_4 ← IO.mkRef Value.null
          port_4.set ((← mk "Port" #[(Value.kw "vertex" (← here_3.get)), (Value.kw "ray" (← beam_4.get))]) : Value)
          if truthy (← orV (← eqV (← gm (← rule_1.get) "where") Value.null) (do pure (← cm (← rule_1.get) "where" #[(← port_4.get)]))) then
            (← cm (← rule_1.get) "apply" #[(← port_4.get)]) |> sink
            pure ()
          pure ()
        Value.null |> sink
        pure ()
      Value.null |> sink
      pure ()
    Value.null |> sink
    pure ()
  Value.null |> sink
  return Value.null)
initialize statik thisClass "enter" (fun self a1 => do
  let of_0 ← IO.mkRef (arg a1 0)
  let h_0 ← IO.mkRef (arg a1 1)
  let c_0 ← IO.mkRef (arg a1 2)
  sm (← h_0.get) "world" (← mk "Around" #[(Value.kw "geometry" (← gm (← of_0.get) "fine_geometry")), (Value.kw "DEG" (← gm (← of_0.get) "DEG"))])
  sm (← h_0.get) "momentum" (← mk "Vector" #[(Value.kw "components" (← lst #[(← gm (← h_0.get) "px"), (← gm (← h_0.get) "py")]))])
  sm (← h_0.get) "advance" (← cm (← K "Vector") "zero" #[(Value.num 2)])
  let stood_0 ← IO.mkRef Value.null
  stood_0.set ((← mk "Cell" #[(Value.kw "of" (← of_0.get)), (Value.kw "index" (← tern (← ltV (← c_0.get) (Value.num 0)) (do pure (Value.num 0)) (do pure (← c_0.get))))]) : Value)
  sm (← stood_0.get) "fine" (Value.bool true)
  sm (← h_0.get) "cells" (← tern (← ltV (← c_0.get) (Value.num 0)) (do pure (← lst #[])) (do pure (← lst #[(← stood_0.get)])))
  return Value.null)
initialize statik thisClass "transport" (fun self a1 => do
  let of_0 ← IO.mkRef (arg a1 0)
  let rules_0 ← IO.mkRef (arg a1 1)
  let holes_0 ← IO.mkRef (arg a1 2)
  let about_0 ← IO.mkRef Value.null
  about_0.set ((← m_filter (← rules_0.get) #[(mkFn (fun a3 => do
    let r_2 ← IO.mkRef (arg a3 0)
    if true then return (← eqV (← gm (← r_2.get) "over") (Value.str ("Source")))
    return Value.null))]) : Value)
  for e1 in (← itemsv (← about_0.get)) do
    let rule_1 ← IO.mkRef e1
    for e2 in (← itemsv (← holes_0.get)) do
      let h_2 ← IO.mkRef e2
      if truthy (← orV (← eqV (← gm (← rule_1.get) "where") Value.null) (do pure (← cm (← rule_1.get) "where" #[(← h_2.get)]))) then
        (← cm (← rule_1.get) "apply" #[(← h_2.get)]) |> sink
        pure ()
      if truthy (← gm (← h_2.get) "stepped") then
        sm (← h_2.get) "moved" (← addV (← gm (← h_2.get) "moved") (Value.num 1))
        let first__2 ← IO.mkRef Value.null
        first__2.set ((← elemv (← gm (← h_2.get) "cells") (Value.num 0)) : Value)
        sm (← h_2.get) "x" (← cm (← of_0.get) "column_of" #[(← gm (← first__2.get) "index")])
        sm (← h_2.get) "y" (← cm (← of_0.get) "row_of" #[(← gm (← first__2.get) "index")])
        pure ()
      pure ()
    Value.null |> sink
    pure ()
  Value.null |> sink
  return Value.null)
end C_Bodies


