-- GENERATED by `npx ray gen` from implementation/physics.ray - do not edit
import OrbitMines.Physics.Runtime
set_option linter.unusedVariables false
set_option maxHeartbeats 0
set_option maxRecDepth 100000
open Rt


namespace C_Around
def thisClass : String := "Around"
initialize defineClass thisClass "Node"
initialize fieldNone thisClass "geometry"
initialize fieldNone thisClass "DEG"
end C_Around


