-- GENERATED by `npx ray gen` from implementation/physics.ray - do not edit
import OrbitMines.Physics.Runtime
set_option linter.unusedVariables false
set_option maxHeartbeats 0
set_option maxRecDepth 100000
open Rt


namespace C_Solve
def thisClass : String := "Solve"
initialize defineClass thisClass "Node"
initialize statik thisClass "settles" (fun self a1 => do
  let R_0 ← IO.mkRef (arg a1 0)
  let a_0 ← IO.mkRef Value.null
  a_0.set ((← mulV (← gm (← R_0.get) "sigma") (← gm (← R_0.get) "F")) : Value)
  let b_0 ← IO.mkRef Value.null
  b_0.set ((← gm (← R_0.get) "nu") : Value)
  let c_0 ← IO.mkRef Value.null
  c_0.set ((← negV (← gm (← R_0.get) "nu")) : Value)
  if truthy (← eqV (← a_0.get) (Value.num 0)) then
    if true then return (Value.num 1)
    pure ()
  if true then return (← divV ((← addV (← negV (← b_0.get)) (← m_sqrt ((← subV (← mulV (← b_0.get) (← b_0.get)) (← mulV (← mulV (Value.num 4) (← a_0.get)) (← c_0.get))))))) ((← mulV (Value.num 2) (← a_0.get))))
  return Value.null)
initialize statik thisClass "root" (fun self a1 => do
  let s_0 ← IO.mkRef (arg a1 0)
  let name_0 ← IO.mkRef (arg a1 1)
  let f_0 ← IO.mkRef (arg a1 2)
  let had_0 ← IO.mkRef Value.null
  had_0.set ((← elemv (← s_0.get) (← name_0.get)) : Value)
  let at__0 ← IO.mkRef Value.null
  at__0.set ((mkFn (fun a2 => do
    let x_1 ← IO.mkRef (arg a2 0)
    setAt (← s_0.get) (← name_0.get) (← x_1.get)
    if true then return (← inv (← f_0.get) #[(← s_0.get)])
    return Value.null)) : Value)
  let lo_0 ← IO.mkRef Value.null
  lo_0.set ((Value.num 0) : Value)
  let hi_0 ← IO.mkRef Value.null
  hi_0.set ((Value.num 1) : Value)
  let flo_0 ← IO.mkRef Value.null
  flo_0.set ((← inv (← at__0.get) #[(← lo_0.get)]) : Value)
  let fhi_0 ← IO.mkRef Value.null
  fhi_0.set ((← inv (← at__0.get) #[(← hi_0.get)]) : Value)
  if truthy (← gtV (← mulV (← flo_0.get) (← fhi_0.get)) (Value.num 0)) then
    setAt (← s_0.get) (← name_0.get) (← had_0.get)
    if true then return (← tern (← ltV (← m_abs (← flo_0.get)) (← m_abs (← fhi_0.get))) (do pure (← lo_0.get)) (do pure (← hi_0.get)))
    pure ()
  let i_0 ← IO.mkRef Value.null
  i_0.set ((Value.num 0) : Value)
  while truthy (← ltV (← i_0.get) (Value.num 60)) do
    let mid_0 ← IO.mkRef Value.null
    mid_0.set ((← divV ((← addV (← lo_0.get) (← hi_0.get))) (Value.num 2)) : Value)
    let fm_0 ← IO.mkRef Value.null
    fm_0.set ((← inv (← at__0.get) #[(← mid_0.get)]) : Value)
    if truthy (← leV (← mulV (← fm_0.get) (← flo_0.get)) (Value.num 0)) then
      (← wr hi_0 (← mid_0.get)) |> sink
      pure ()
    else
      (← wr lo_0 (← mid_0.get)) |> sink
      (← wr flo_0 (← fm_0.get)) |> sink
      pure ()
    (← wr i_0 (← addV (← i_0.get) (Value.num 1))) |> sink
    pure ()
  setAt (← s_0.get) (← name_0.get) (← had_0.get)
  if true then return (← divV ((← addV (← lo_0.get) (← hi_0.get))) (Value.num 2))
  return Value.null)
initialize statik thisClass "sweep" (fun self a1 => do
  let R_0 ← IO.mkRef (arg a1 0)
  let geometry_0 ← IO.mkRef (arg a1 1)
  let radius_0 ← IO.mkRef (arg a1 2)
  let size_0 ← IO.mkRef (arg a1 3)
  let passes_0 ← IO.mkRef (arg a1 4)
  let tol_0 ← IO.mkRef (arg a1 5)
  if truthy (← eqV (← size_0.get) Value.null) then
    (← wr size_0 (Value.num 41)) |> sink
    pure ()
  if truthy (← eqV (← passes_0.get) Value.null) then
    (← wr passes_0 (Value.num 400)) |> sink
    pure ()
  if truthy (← eqV (← tol_0.get) Value.null) then
    (← wr tol_0 0.000000000001) |> sink
    pure ()
  let L_0 ← IO.mkRef Value.null
  L_0.set ((← size_0.get) : Value)
  let D_0 ← IO.mkRef Value.null
  D_0.set ((← gm (← geometry_0.get) "D") : Value)
  let rho_0 ← IO.mkRef Value.null
  rho_0.set ((← cm (← K "Solve") "settles" #[(← R_0.get)]) : Value)
  let c_0 ← IO.mkRef Value.null
  c_0.set ((← divV (← subV (← L_0.get) (Value.num 1)) (Value.num 2)) : Value)
  let cells_0 ← IO.mkRef Value.null
  cells_0.set ((← powV (← L_0.get) (← D_0.get)) : Value)
  let stride_0 ← IO.mkRef Value.null
  stride_0.set ((← m_map (← rng (← D_0.get)) #[(mkFn (fun a3 => do
    let i_2 ← IO.mkRef (arg a3 0)
    if true then return (← powV (← L_0.get) (← i_2.get))
    return Value.null))]) : Value)
  let step_0 ← IO.mkRef Value.null
  step_0.set ((← m_map (← gm (← geometry_0.get) "offsets") #[(mkFn (fun a3 => do
    let v_2 ← IO.mkRef (arg a3 0)
    if true then return (← m_map (← gm (← v_2.get) "components") #[(mkFn (fun a5 => do
      let x_4 ← IO.mkRef (arg a5 0)
      if true then return (← m_round (← x_4.get))
      return Value.null))])
    return Value.null))]) : Value)
  let M_0 ← IO.mkRef Value.null
  M_0.set ((← lenOf (← step_0.get)) : Value)
  let shift_0 ← IO.mkRef Value.null
  shift_0.set ((← m_map (← step_0.get) #[(mkFn (fun a3 => do
    let v_2 ← IO.mkRef (arg a3 0)
    if true then return (← m_sum (← m_map (← rng (← D_0.get)) #[(mkFn (fun a5 => do
      let i_4 ← IO.mkRef (arg a5 0)
      if true then return (← mulV (← elemv (← v_2.get) (← i_4.get)) (← elemv (← stride_0.get) (← i_4.get)))
      return Value.null))]))
    return Value.null))]) : Value)
  let opp_0 ← IO.mkRef Value.null
  opp_0.set ((← m_map (← step_0.get) #[(mkFn (fun a3 => do
    let v_2 ← IO.mkRef (arg a3 0)
    if true then return (← orElse (← m_index_of (← step_0.get) #[(← m_map (← v_2.get) #[(mkFn (fun a5 => do
      let x_4 ← IO.mkRef (arg a5 0)
      if true then return (← subV (Value.num 0) (← x_4.get))
      return Value.null))])]) (do pure (← negV (Value.num 1))))
    return Value.null))]) : Value)
  let coord_0 ← IO.mkRef Value.null
  coord_0.set ((mkFn (fun a2 => do
    let k_1 ← IO.mkRef (arg a2 0)
    if true then return (← m_map (← rng (← D_0.get)) #[(mkFn (fun a4 => do
      let i_3 ← IO.mkRef (arg a4 0)
      if true then return (← modV (← m_floor ((← divV (← k_1.get) (← elemv (← stride_0.get) (← i_3.get))))) (← L_0.get))
      return Value.null))])
    return Value.null)) : Value)
  let is_matter_0 ← IO.mkRef Value.null
  is_matter_0.set ((← m_map (← rng (← cells_0.get)) #[(mkFn (fun a3 => do
    let k_2 ← IO.mkRef (arg a3 0)
    let p_2 ← IO.mkRef Value.null
    p_2.set ((← inv (← coord_0.get) #[(← k_2.get)]) : Value)
    if true then return (← leV (← m_sqrt ((← m_sum (← m_map (← rng (← D_0.get)) #[(mkFn (fun a5 => do
      let i_4 ← IO.mkRef (arg a5 0)
      if true then return (← powV ((← subV (← elemv (← p_2.get) (← i_4.get)) (← c_0.get))) (Value.num 2))
      return Value.null))])))) (← radius_0.get))
    return Value.null))]) : Value)
  let n_0 ← IO.mkRef Value.null
  n_0.set ((← filled (← mulV (← cells_0.get) (← M_0.get)) (← divV (← rho_0.get) (← M_0.get))) : Value)
  let next_0 ← IO.mkRef Value.null
  next_0.set ((← filled (← mulV (← cells_0.get) (← M_0.get)) (Value.num 0)) : Value)
  let s_0 ← IO.mkRef Value.null
  s_0.set ((← filled (← cells_0.get) (Value.num 1)) : Value)
  let settled_0 ← IO.mkRef Value.null
  settled_0.set ((Value.bool false) : Value)
  let done_0 ← IO.mkRef Value.null
  done_0.set ((Value.num 0) : Value)
  while truthy (← andV (← ltV (← done_0.get) (← passes_0.get)) (do pure (← notV (← settled_0.get)))) do
    for i1 in [0:rangeN (← mulV (← cells_0.get) (← M_0.get))] do
      let i_1 ← IO.mkRef (Value.num (natF i1))
      setAt (← next_0.get) (← i_1.get) (Value.num 0)
      pure ()
    Value.null |> sink
    let moved_0 ← IO.mkRef Value.null
    moved_0.set ((Value.num 0) : Value)
    for i1 in [0:rangeN (← cells_0.get)] do
      let k_1 ← IO.mkRef (Value.num (natF i1))
      let tot_1 ← IO.mkRef Value.null
      tot_1.set ((← m_sum (← m_map (← rng (← M_0.get)) #[(mkFn (fun a4 => do
        let d_3 ← IO.mkRef (arg a4 0)
        if true then return (← elemv (← n_0.get) (← addV (← mulV (← k_1.get) (← M_0.get)) (← d_3.get)))
        return Value.null))])) : Value)
      let made_1 ← IO.mkRef Value.null
      made_1.set ((← tern (← elemv (← is_matter_0.get) (← k_1.get)) (do pure (Value.num 0)) (do pure (← mulV (← gm (← R_0.get) "nu") ((← tern (← gtV (← subV (Value.num 1) (← tot_1.get)) (Value.num 0)) (do pure (← subV (Value.num 1) (← tot_1.get))) (do pure (Value.num 0))))))) : Value)
      let sp_1 ← IO.mkRef Value.null
      sp_1.set ((← divV (Value.num 1) (← elemv (← s_0.get) (← k_1.get))) : Value)
      for i2 in [0:rangeN (← M_0.get)] do
        let d_2 ← IO.mkRef (Value.num (natF i2))
        let here_2 ← IO.mkRef Value.null
        here_2.set ((← elemv (← n_0.get) (← addV (← mulV (← k_1.get) (← M_0.get)) (← d_2.get))) : Value)
        let facing_2 ← IO.mkRef Value.null
        facing_2.set ((← elemv (← n_0.get) (← addV (← mulV (← k_1.get) (← M_0.get)) ((← tern (← ltV (← elemv (← opp_0.get) (← d_2.get)) (Value.num 0)) (do pure (← d_2.get)) (do pure (← elemv (← opp_0.get) (← d_2.get))))))) : Value)
        let killed_2 ← IO.mkRef Value.null
        killed_2.set ((← mulV (← mulV (← mulV (← mulV (← gm (← R_0.get) "sigma") ((← subV (Value.num 1) (← gm (← R_0.get) "g")))) (← here_2.get)) (← facing_2.get)) (← gm (← R_0.get) "F")) : Value)
        let left_2 ← IO.mkRef Value.null
        left_2.set ((← subV (← subV (← addV (← here_2.get) (← divV (← made_1.get) (← M_0.get))) (← killed_2.get)) ((← tern (← elemv (← is_matter_0.get) (← k_1.get)) (do pure (← here_2.get)) (do pure (Value.num 0))))) : Value)
        (← wr left_2 (← tern (← ltV (← left_2.get) (Value.num 0)) (do pure (Value.num 0)) (do pure (← left_2.get)))) |> sink
        let p_2 ← IO.mkRef Value.null
        p_2.set ((← inv (← coord_0.get) #[(← k_1.get)]) : Value)
        let inside_2 ← IO.mkRef Value.null
        inside_2.set ((← m_every (← rng (← D_0.get)) #[(mkFn (fun a5 => do
          let i_4 ← IO.mkRef (arg a5 0)
          if true then return (← andV (← geV (← addV (← elemv (← p_2.get) (← i_4.get)) (← elemv (← elemv (← step_0.get) (← d_2.get)) (← i_4.get))) (Value.num 0)) (do pure (← ltV (← addV (← elemv (← p_2.get) (← i_4.get)) (← elemv (← elemv (← step_0.get) (← d_2.get)) (← i_4.get))) (← L_0.get))))
          return Value.null))]) : Value)
        if truthy (← inside_2.get) then
          setAt (← next_0.get) (← addV (← mulV ((← addV (← k_1.get) (← elemv (← shift_0.get) (← d_2.get)))) (← M_0.get)) (← d_2.get)) (← addV (← elemv (← next_0.get) (← addV (← mulV ((← addV (← k_1.get) (← elemv (← shift_0.get) (← d_2.get)))) (← M_0.get)) (← d_2.get))) (← mulV (← left_2.get) (← sp_1.get)))
          setAt (← next_0.get) (← addV (← mulV (← k_1.get) (← M_0.get)) (← d_2.get)) (← addV (← elemv (← next_0.get) (← addV (← mulV (← k_1.get) (← M_0.get)) (← d_2.get))) (← mulV (← left_2.get) ((← subV (Value.num 1) (← sp_1.get)))))
          pure ()
        pure ()
      Value.null |> sink
      pure ()
    Value.null |> sink
    for i1 in [0:rangeN (← mulV (← cells_0.get) (← M_0.get))] do
      let i_1 ← IO.mkRef (Value.num (natF i1))
      let delta_1 ← IO.mkRef Value.null
      delta_1.set ((← m_abs ((← subV (← elemv (← next_0.get) (← i_1.get)) (← elemv (← n_0.get) (← i_1.get))))) : Value)
      if truthy (← gtV (← delta_1.get) (← moved_0.get)) then
        (← wr moved_0 (← delta_1.get)) |> sink
        pure ()
      setAt (← n_0.get) (← i_1.get) (← elemv (← next_0.get) (← i_1.get))
      pure ()
    Value.null |> sink
    (← wr settled_0 (← ltV (← moved_0.get) (← tol_0.get))) |> sink
    (← wr done_0 (← addV (← done_0.get) (Value.num 1))) |> sink
    pure ()
  let dens_0 ← IO.mkRef Value.null
  dens_0.set ((← m_map (← rng (← cells_0.get)) #[(mkFn (fun a3 => do
    let k_2 ← IO.mkRef (arg a3 0)
    if true then return (← m_sum (← m_map (← rng (← M_0.get)) #[(mkFn (fun a5 => do
      let d_4 ← IO.mkRef (arg a5 0)
      if true then return (← elemv (← n_0.get) (← addV (← mulV (← k_2.get) (← M_0.get)) (← d_4.get)))
      return Value.null))]))
    return Value.null))]) : Value)
  let imbalance_0 ← IO.mkRef Value.null
  imbalance_0.set ((← m_map (← rng (← cells_0.get)) #[(mkFn (fun a3 => do
    let k_2 ← IO.mkRef (arg a3 0)
    let p_2 ← IO.mkRef Value.null
    p_2.set ((← inv (← coord_0.get) #[(← k_2.get)]) : Value)
    let f_2 ← IO.mkRef Value.null
    f_2.set ((← m_map (← rng (← D_0.get)) #[(mkFn (fun a5 => do
      let i_4 ← IO.mkRef (arg a5 0)
      if true then return (← m_sum (← m_map (← rng (← M_0.get)) #[(mkFn (fun a7 => do
        let d_6 ← IO.mkRef (arg a7 0)
        if true then return (← mulV (← elemv (← n_0.get) (← addV (← mulV (← k_2.get) (← M_0.get)) (← d_6.get))) (← elemv (← elemv (← step_0.get) (← d_6.get)) (← i_4.get)))
        return Value.null))]))
      return Value.null))]) : Value)
    let r_2 ← IO.mkRef Value.null
    r_2.set ((← m_map (← rng (← D_0.get)) #[(mkFn (fun a5 => do
      let i_4 ← IO.mkRef (arg a5 0)
      if true then return (← subV (← c_0.get) (← elemv (← p_2.get) (← i_4.get)))
      return Value.null))]) : Value)
    let norm_2 ← IO.mkRef Value.null
    norm_2.set ((← m_sqrt ((← m_sum (← m_map (← r_2.get) #[(mkFn (fun a5 => do
      let x_4 ← IO.mkRef (arg a5 0)
      if true then return (← mulV (← x_4.get) (← x_4.get))
      return Value.null))])))) : Value)
    if true then return (← divV ((← m_sum (← m_map (← rng (← D_0.get)) #[(mkFn (fun a5 => do
      let i_4 ← IO.mkRef (arg a5 0)
      if true then return (← mulV (← elemv (← f_2.get) (← i_4.get)) (← elemv (← r_2.get) (← i_4.get)))
      return Value.null))]))) ((← tern (← gtV (← norm_2.get) (Value.num 0)) (do pure (← norm_2.get)) (do pure (Value.num 1)))))
    return Value.null))]) : Value)
  if true then return (← mk "Grid" #[(Value.kw "L" (← L_0.get)), (Value.kw "n" (← dens_0.get)), (Value.kw "s" (← s_0.get)), (Value.kw "rho" (← rho_0.get)), (Value.kw "passes" (← done_0.get)), (Value.kw "settled" (← settled_0.get)), (Value.kw "imbalance" (← imbalance_0.get))])
  return Value.null)
end C_Solve


