-- GENERATED by `npx ray gen` from implementation/physics.ray - do not edit
import OrbitMines.Physics.Runtime
set_option linter.unusedVariables false
set_option maxHeartbeats 0
set_option maxRecDepth 100000
open Rt


namespace C_Edge
def thisClass : String := "Edge"
initialize defineClass thisClass "Ray"
initialize field thisClass "initial" (fun self => do
  return Value.null)
initialize field thisClass "terminal" (fun self => do
  return Value.null)
initialize getter thisClass "value" (fun self a1 => do
  if true then return (← lst #[(← gm self "initial"), (← gm self "terminal")])
  return Value.null)
initialize getter thisClass "is_initial" (fun self a1 => do
  if true then return (← eqV (← gm self "initial") Value.null)
  return Value.null)
initialize getter thisClass "is_terminal" (fun self a1 => do
  if true then return (← eqV (← gm self "terminal") Value.null)
  return Value.null)
initialize method thisClass "link" (fun self a1 => do
  let a_0 ← IO.mkRef (arg a1 0)
  let b_0 ← IO.mkRef (arg a1 1)
  sm self "initial" (← a_0.get)
  sm self "terminal" (← b_0.get)
  sm (← a_0.get) "edge" self
  sm (← b_0.get) "edge" self
  if true then return self
  return Value.null)
initialize getter thisClass "active" (fun self a1 => do
  if true then return (← andV (← andV (← andV (← neV (← gm self "initial") Value.null) (do pure (← neV (← gm self "terminal") Value.null))) (do pure (← gm (← gm self "initial") "active"))) (do pure (← gm (← gm self "terminal") "active")))
  return Value.null)
initialize getter thisClass "ANNIHILATE" (fun self a1 => do
  (← gm (← gm (← gm self "initial") "ray") "deactivate") |> sink
  (← gm (← gm (← gm self "terminal") "ray") "deactivate") |> sink
  let here_0 ← IO.mkRef Value.null
  here_0.set ((← gm (← gm self "initial") "vertex") : Value)
  let there_0 ← IO.mkRef Value.null
  there_0.set ((← gm (← gm self "terminal") "vertex") : Value)
  sm (← gm (← here_0.get) "world") "annihilations" (← addV (← gm (← gm (← here_0.get) "world") "annihilations") (Value.num 1))
  sm (← here_0.get) "destroyed" (← addV (← gm (← here_0.get) "destroyed") 0.5)
  sm (← there_0.get) "destroyed" (← addV (← gm (← there_0.get) "destroyed") 0.5)
  let g_0 ← IO.mkRef Value.null
  g_0.set ((← gm (← gm (← here_0.get) "world") "geometry") : Value)
  let a_0 ← IO.mkRef Value.null
  a_0.set ((← gm (← gm self "initial") "ray") : Value)
  let b_0 ← IO.mkRef Value.null
  b_0.set ((← gm (← gm self "terminal") "ray") : Value)
  if !truthy (← gm (← elemv (← gm (← here_0.get) "rays") (← cm (← g_0.get) "opposite" #[(← gm (← a_0.get) "exit")])) "active") then
    (← cm (← gm (← here_0.get) "world") "grow" #[(← subV (← gm (← here_0.get) "at") (← elemv (← gm (← g_0.get) "offsets") (← gm (← a_0.get) "exit")))]) |> sink
    pure ()
  if !truthy (← gm (← elemv (← gm (← there_0.get) "rays") (← cm (← g_0.get) "opposite" #[(← gm (← b_0.get) "exit")])) "active") then
    (← cm (← gm (← there_0.get) "world") "grow" #[(← subV (← gm (← there_0.get) "at") (← elemv (← gm (← g_0.get) "offsets") (← gm (← b_0.get) "exit")))]) |> sink
    pure ()
  if true then return (← cm (← here_0.get) "fold" #[(← there_0.get)])
  return Value.null)
end C_Edge


