-- GENERATED by `npx ray gen` from implementation/physics.ray - do not edit
import OrbitMines.Physics.Runtime
set_option linter.unusedVariables false
set_option maxHeartbeats 0
set_option maxRecDepth 100000
open Rt


namespace C_Body
def thisClass : String := "Body"
initialize defineClass thisClass "Node"
initialize fieldNone thisClass "x"
initialize fieldNone thisClass "y"
initialize fieldNone thisClass "mx"
initialize fieldNone thisClass "ways"
initialize field thisClass "px" (fun self => do
  return (Value.num 0))
initialize field thisClass "py" (fun self => do
  return (Value.num 0))
initialize field thisClass "moves" (fun self => do
  return (Value.bool false))
initialize field thisClass "tag" (fun self => do
  return (Value.num 0))
initialize field thisClass "launch" (fun self => do
  return (Value.str ("given")))
initialize field thisClass "ecc" (fun self => do
  return (Value.num 0))
end C_Body


