-- GENERATED by `npx ray gen` from implementation/physics.ray - do not edit
import OrbitMines.Physics.Runtime
set_option linter.unusedVariables false
set_option maxHeartbeats 0
set_option maxRecDepth 100000
open Rt


namespace C_Geometry
def thisClass : String := "Geometry"
initialize defineClass thisClass "Node"
initialize fieldNone thisClass "name"
initialize fieldNone thisClass "offsets"
initialize getter thisClass "D" (fun self a1 => do
  if true then return (← lenOf (← gm (← elemv (← gm self "offsets") (Value.num 0)) "components"))
  return Value.null)
initialize getter thisClass "DEG" (fun self a1 => do
  if true then return (← lenOf (← gm self "offsets"))
  return Value.null)
initialize method thisClass "V" (fun self a1 => do
  let d_0 ← IO.mkRef (arg a1 0)
  if true then return (← gm (← elemv (← gm self "offsets") (← d_0.get)) "unit")
  return Value.null)
initialize method thisClass "steps" (fun self a1 => do
  let d_0 ← IO.mkRef (arg a1 0)
  if true then return (← gm (← elemv (← gm self "offsets") (← d_0.get)) "norm")
  return Value.null)
initialize method thisClass "opposite" (fun self a1 => do
  let d_0 ← IO.mkRef (arg a1 0)
  if true then return (← m_index_of (← gm self "offsets") #[(← negV (← elemv (← gm self "offsets") (← d_0.get)))])
  return Value.null)
initialize statik thisClass "shells" (fun self a1 => do
  let D_0 ← IO.mkRef (arg a1 0)
  let squared_0 ← IO.mkRef (arg a1 1)
  let radius_0 ← IO.mkRef Value.null
  radius_0.set ((← addV (← elemv (← m_most (← m_map (← squared_0.get) #[(mkFn (fun a4 => do
    let s_3 ← IO.mkRef (arg a4 0)
    if true then return (← m_floor (← m_sqrt (← s_3.get)))
    return Value.null))]) #[(mkFn (fun a3 => do
    let r_2 ← IO.mkRef (arg a3 0)
    if true then return (← r_2.get)
    return Value.null))]) (Value.num 0)) (Value.num 1)) : Value)
  let all_0 ← IO.mkRef Value.null
  all_0.set ((← m_sorted_by (← m_filter (← cm (← K "Geometry") "box" #[(← D_0.get), (← radius_0.get)]) #[(mkFn (fun a4 => do
    let v_3 ← IO.mkRef (arg a4 0)
    if true then return (← gtV (← gm (← v_3.get) "norm") (Value.num 0))
    return Value.null))]) #[(mkFn (fun a3 => do
    let v_2 ← IO.mkRef (arg a3 0)
    if true then return (← gm (← v_2.get) "norm")
    return Value.null))]) : Value)
  let chosen_0 ← IO.mkRef Value.null
  chosen_0.set ((← lst #[]) : Value)
  for e1 in (← itemsv (← squared_0.get)) do
    let s_1 ← IO.mkRef e1
    for e2 in (← itemsv (← all_0.get)) do
      let v_2 ← IO.mkRef e2
      if truthy (← eqV (← cm (← v_2.get) "dot" #[(← v_2.get)]) (← s_1.get)) then
        (← m_push (← chosen_0.get) #[(← v_2.get)]) |> sink
        pure ()
      pure ()
    Value.null |> sink
    pure ()
  Value.null |> sink
  let joined_0 ← IO.mkRef Value.null
  joined_0.set ((← m_join (← squared_0.get) #[(Value.str ("+"))]) : Value)
  if true then return (← mk "Geometry" #[(Value.kw "name" (Value.str ("shells-" ++ (← strv (← D_0.get)) ++ "-" ++ (← strv (← joined_0.get)) ++ ""))), (Value.kw "offsets" (← chosen_0.get))])
  return Value.null)
initialize statik thisClass "nearest" (fun self a1 => do
  let D_0 ← IO.mkRef (arg a1 0)
  let DEG_0 ← IO.mkRef (arg a1 1)
  let radius_0 ← IO.mkRef Value.null
  radius_0.set ((Value.num 1) : Value)
  let candidates_0 ← IO.mkRef Value.null
  candidates_0.set ((← lst #[]) : Value)
  while truthy (← ltV (← lenOf (← candidates_0.get)) (← DEG_0.get)) do
    (← wr candidates_0 (← m_filter (← cm (← K "Geometry") "box" #[(← D_0.get), (← radius_0.get)]) #[(mkFn (fun a3 => do
      let v_2 ← IO.mkRef (arg a3 0)
      if true then return (← gtV (← gm (← v_2.get) "norm") (Value.num 0))
      return Value.null))])) |> sink
    (← wr candidates_0 (← m_sorted_by (← candidates_0.get) #[(mkFn (fun a3 => do
      let v_2 ← IO.mkRef (arg a3 0)
      if true then return (← gm (← v_2.get) "norm")
      return Value.null))])) |> sink
    (← wr radius_0 (← addV (← radius_0.get) (Value.num 1))) |> sink
    pure ()
  let cut_0 ← IO.mkRef Value.null
  cut_0.set ((← gm (← elemv (← candidates_0.get) (← subV (← DEG_0.get) (Value.num 1))) "norm") : Value)
  let chosen_0 ← IO.mkRef Value.null
  chosen_0.set ((← m_filter (← candidates_0.get) #[(mkFn (fun a3 => do
    let v_2 ← IO.mkRef (arg a3 0)
    if true then return (← leV (← gm (← v_2.get) "norm") (← cut_0.get))
    return Value.null))]) : Value)
  if !truthy (← eqV (← lenOf (← chosen_0.get)) (← DEG_0.get)) then throw (IO.userError "(← eqV (← lenOf (← chosen_0.get)) (← DEG_0.get))")
  if true then return (← mk "Geometry" #[(Value.kw "name" (Value.str ("nearest-" ++ (← strv (← D_0.get)) ++ "-" ++ (← strv (← DEG_0.get)) ++ ""))), (Value.kw "offsets" (← chosen_0.get))])
  return Value.null)
initialize statik thisClass "box" (fun self a1 => do
  let D_0 ← IO.mkRef (arg a1 0)
  let radius_0 ← IO.mkRef (arg a1 1)
  let points_0 ← IO.mkRef Value.null
  points_0.set ((← lst #[(← mk "Vector" #[(Value.kw "components" (← lst #[]))])]) : Value)
  let i_0 ← IO.mkRef Value.null
  i_0.set ((Value.num 0) : Value)
  while truthy (← ltV (← i_0.get) (← D_0.get)) do
    let grown_0 ← IO.mkRef Value.null
    grown_0.set ((← lst #[]) : Value)
    for e1 in (← itemsv (← points_0.get)) do
      let p_1 ← IO.mkRef e1
      let k_1 ← IO.mkRef Value.null
      k_1.set ((← subV (Value.num 0) (← radius_0.get)) : Value)
      while truthy (← leV (← k_1.get) (← radius_0.get)) do
        (← m_push (← grown_0.get) #[(← mk "Vector" #[(Value.kw "components" (← m_concat (← gm (← p_1.get) "components") #[(← lst #[(← k_1.get)])]))])]) |> sink
        (← wr k_1 (← addV (← k_1.get) (Value.num 1))) |> sink
        pure ()
      pure ()
    Value.null |> sink
    (← wr points_0 (← grown_0.get)) |> sink
    (← wr i_0 (← addV (← i_0.get) (Value.num 1))) |> sink
    pure ()
  if true then return (← points_0.get)
  return Value.null)
end C_Geometry


