-- GENERATED by `npx ray gen` from implementation/physics.ray - do not edit
import OrbitMines.Physics.Runtime
set_option linter.unusedVariables false
set_option maxHeartbeats 0
set_option maxRecDepth 100000
open Rt


namespace C_Asked
def thisClass : String := "Asked"
initialize defineClass thisClass "Node"
initialize fieldNone thisClass "asks"
initialize fieldNone thisClass "about"
initialize field thisClass "also" (fun self => do
  return Value.null)
initialize field thisClass "leads" (fun self => do
  return Value.null)
initialize field thisClass "then" (fun self => do
  return Value.null)
initialize field thisClass "chain" (fun self => do
  return Value.null)
end C_Asked


