-- GENERATED by `npx ray gen` from implementation/physics.ray - do not edit
import OrbitMines.Physics.Globals
set_option linter.unusedVariables false
set_option autoImplicit false
set_option maxHeartbeats 0
set_option maxRecDepth 100000
namespace OrbitMines.Physics


namespace Strip
ray_impl_sfield "PAD" : Value := do
  return (12 : Float)
ray_impl_sfield "MID" : Value := do
  return (30 : Float)
ray_impl_sfield "PANE" : Value := do
  return (← ωadd (← ωdiv ((← ωsub (← ωsub (900 : Float) (← ωmul (2 : Float) (12 : Float))) (30 : Float))) (2 : Float)) (← ωmul (2 : Float) (12 : Float)))
ray_impl_static "line" (theory_0 : Theory) (N_0 : Float) : World := do
  if true then return (← call! (← theory_0.get) "seed" ((← ωglobal_LINE2), (← N_0.get), (0 : Float), (250000 : Float), (2 : Float)))
  return ωnull
ray_impl_static "exit_toward" (w_0 : World) (sign_0 : Float) : Float := do
  if true then return (← dot! (← dot! (← ωrrange (← ωget (← ωget (← w_0.get) "geometry") "DEG")) rfilter ((fn! [d_2] do
    if true then return (← ωgt (← ωmul (← ωelem (← ωget (← call! (← ωget (← w_0.get) "geometry") "V" ((← d_2.get))) "components") (0 : Float)) (← sign_0.get)) (0 : Float))
    return ωnull))) rfirst ())
  return ωnull
ray_impl_static "point_at" (w_0 : World) (at__0 : Float) : Vertex := do
  if true then return (← call! (← w_0.get) "at" ((← new! Vector («components» := (← ωlst #[(← at__0.get)])))))
  return ωnull
ray_impl_static "light" (w_0 : World) (at__0 : Float) (sign_0 : Float) : Value := do
  if true then return (← ωget (← ωelem (← ωget (← call! (← cls% Strip) "point_at" ((← w_0.get), (← at__0.get))) "rays") (← call! (← cls% Strip) "exit_toward" ((← w_0.get), (← sign_0.get)))) "activate")
  return ωnull
ray_impl_static "meeting" (theory_0 : Theory) : World := do
  let w_0 ← IO.mkRef (← call! (← cls% Strip) "line" ((← theory_0.get), (2 : Float)))
  (← call! (← cls% Strip) "light" ((← w_0.get), (0 : Float), (1 : Float))) |> ωsink
  (← call! (← cls% Strip) "light" ((← w_0.get), (1 : Float), (← ωsub (0 : Float) (1 : Float)))) |> ωsink
  if true then return (← w_0.get)
  return ωnull
ray_impl_static "left" (theory_0 : Theory) (laying_0 : Value) (ids_0 : (RList String)) : World := do
  let w_0 ← IO.mkRef (← app! (← laying_0.get) ((← theory_0.get)))
  (← call! (← cls% Strip) "run" ((← w_0.get), (← ids_0.get))) |> ωsink
  if true then return (← w_0.get)
  return ωnull
ray_impl_static "point" (theory_0 : Theory) : World := do
  if true then return (← call! (← theory_0.get) "seed" ((← ωglobal_LINE2), (1 : Float), (0 : Float), (250000 : Float), (16 : Float)))
  return ωnull
ray_impl_static "heading" (theory_0 : Theory) (sign_0 : Float) : World := do
  let w_0 ← IO.mkRef (← call! (← cls% Strip) "line" ((← theory_0.get), (3 : Float)))
  (← call! (← cls% Strip) "light" ((← w_0.get), (1 : Float), (← sign_0.get))) |> ωsink
  if true then return (← w_0.get)
  return ωnull
ray_impl_static "run" (w_0 : World) (ids_0 : (RList String)) : Value := do
  for e1 in (← ωitems (← ids_0.get)) do
    let rid_1 ← IO.mkRef e1
    let rule_1 ← IO.mkRef (← dot! (← dot! (← ωget (← ωget (← w_0.get) "theory") "rules") rfilter ((fn! [r_3] do
      if true then return (← ωeqv (← ωget (← r_3.get) "id") (← rid_1.get))
      return ωnull))) rfirst ())
    if ωtruthy (ωisNull (← rule_1.get)) then
      (← app! fail (("" ++ (← ωtoStr (← ωget (← ωget (← w_0.get) "theory") "name")) ++ " has no rule " ++ (← ωtoStr (← rid_1.get)) ++ "" : String))) |> ωsink
      pure ()
    for e2 in (← ωitems (← call! (← rule_1.get) "matches" ((← w_0.get)))) do
      let x_2 ← IO.mkRef e2
      (← call! (← rule_1.get) "apply" ((← x_2.get))) |> ωsink
      pure ()
    Value.null |> ωsink
    pure ()
  Value.null |> ωsink
  return ωnull
ray_impl_static "begin" (w_0 : World) : Value := do
  (ωsetter (← w_0.get) "ticks") (← ωadd (← ωget (← w_0.get) "ticks") (1 : Float))
  for e1 in (← ωitems (← ωget (← w_0.get) "sources")) do
    let s_1 ← IO.mkRef e1
    (ωsetter (← s_1.get) "stepped") false
    (ωsetter (← s_1.get) "moved_along") ωnull
    pure ()
  Value.null |> ωsink
  return ωnull
ray_impl_static "lit" (was_0 : Lane) (now_0 : Lane) : (RList Side) := do
  if true then return (← dot! (← ωget (← now_0.get) "sides") rfilter ((fn! [sd_2] do
    if true then return (← dot! (← ωget (← was_0.get) "sides") revery ((fn! [o_4] do
      if true then return (← ωorV (← ωnev (← ωget (← o_4.get) "at") (← ωget (← sd_2.get) "at")) (do pure (← ωnev (← ωget (← o_4.get) "sign") (← ωget (← sd_2.get) "sign"))))
      return ωnull)))
    return ωnull)))
  return ωnull
ray_impl_static "emitting" (was_0 : Lane) (now_0 : Lane) : String := do
  let new_rays_0 ← IO.mkRef (← call! (← cls% Strip) "lit" ((← was_0.get), (← now_0.get)))
  let left_0 ← IO.mkRef (← dot! (← new_rays_0.get) rsome ((fn! [sd_2] do
    if true then return (← ωlt (← ωget (← sd_2.get) "sign") (0 : Float))
    return ωnull)))
  let right_0 ← IO.mkRef (← dot! (← new_rays_0.get) rsome ((fn! [sd_2] do
    if true then return (← ωgt (← ωget (← sd_2.get) "sign") (0 : Float))
    return ωnull)))
  if ωtruthy (← ωandV (← left_0.get) (do pure (← right_0.get))) then
    if true then return ("emits both ways" : String)
    pure ()
  if ωtruthy (← left_0.get) then
    if true then return ("emits left" : String)
    pure ()
  if ωtruthy (← right_0.get) then
    if true then return ("emits right" : String)
    pure ()
  if true then return ("" : String)
  return ωnull
ray_impl_static "lane" (w_0 : World) (ink_0 : Ink) : Lane := do
  let pts_0 ← IO.mkRef (← dot! (← ωget (← w_0.get) "live") rmap ((fn! [v_2] do
    if true then return (← ωelem (← ωget (← ωget (← v_2.get) "at") "components") (0 : Float))
    return ωnull)))
  let sides_0 ← IO.mkRef (← ωlst #[])
  for e1 in (← ωitems (← ωget (← w_0.get) "live")) do
    let v_1 ← IO.mkRef e1
    for e2 in (← ωitems (← ωget (← v_1.get) "rays")) do
      let r_2 ← IO.mkRef e2
      if ωtruthy (← ωget (← r_2.get) "active") then
        (← dot! (← sides_0.get) rpush ((← new! Side («at» := (← ωelem (← ωget (← ωget (← v_1.get) "at") "components") (0 : Float)), «sign» := (← ωelem (← ωget (← ωget (← r_2.get) "along") "components") (0 : Float)), «ink» := (← call! (← ink_0.get) "ink_of" ((← r_2.get))))))) |> ωsink
        pure ()
      pure ()
    Value.null |> ωsink
    pure ()
  Value.null |> ωsink
  let l_0 ← IO.mkRef (← new! Lane («points» := (← pts_0.get), «sides» := (← sides_0.get)))
  for e1 in (← ωitems (← ωget (← w_0.get) "sources")) do
    let s_1 ← IO.mkRef e1
    for e2 in (← ωitems (← ωget (← s_1.get) "cells")) do
      let c_2 ← IO.mkRef e2
      (← dot! (← ωget (← l_0.get) "sources") rpush ((← ωelem (← ωget (← ωget (← c_2.get) "at") "components") (0 : Float)))) |> ωsink
      pure ()
    Value.null |> ωsink
    pure ()
  Value.null |> ωsink
  if true then return (← l_0.get)
  return ωnull
ray_impl_static "of" (id_0 : String) (what_0 : String) (theory_0 : Theory) (ids_0 : (RList String)) (seeds_0 : (RList Value)) (ink_0 : Ink) : Picture := do
  let rows_0 ← IO.mkRef (← dot! (← seeds_0.get) rmap ((fn! [laying_2] do
    let w_2 ← IO.mkRef (← app! (← laying_2.get) ((← theory_0.get)))
    let before_2 ← IO.mkRef (← call! (← cls% Strip) "lane" ((← w_2.get), (← ink_0.get)))
    (← call! (← cls% Strip) "run" ((← w_2.get), (← ids_0.get))) |> ωsink
    if true then return (← ωlst #[(← before_2.get), (← call! (← cls% Strip) "lane" ((← w_2.get), (← ink_0.get)))])
    return ωnull)))
  let H_0 ← IO.mkRef (← ωmul (70 : Float) (← dot! (← rows_0.get) rlength ()))
  let pic_0 ← IO.mkRef (← call! (← cls% Picture) "still" ((← id_0.get), (← what_0.get), (900 : Float), (← H_0.get), (fn! [(s_2 : Surface)] do
    if true then return (← call! (← cls% Strip) "paint" ((← s_2.get), (← rows_0.get), (← ink_0.get), (← ωlst #[(0 : Float), (1 : Float)])))
    return ωnull)))
  (ωsetter (← pic_0.get) "panes") (← ωlst #[(← new! Pane («name» := ("before" : String), «width» := (← ωget (← cls% Strip) "PANE"), «height» := (← H_0.get), «paints» := (fn! [(s_2 : Surface)] do
    if true then return (← call! (← cls% Strip) "paint" ((← s_2.get), (← rows_0.get), (← ink_0.get), (← ωlst #[(0 : Float)])))
    return ωnull))), (← new! Pane («name» := ("after" : String), «width» := (← ωget (← cls% Strip) "PANE"), «height» := (← H_0.get), «paints» := (fn! [(s_2 : Surface)] do
    if true then return (← call! (← cls% Strip) "paint" ((← s_2.get), (← rows_0.get), (← ink_0.get), (← ωlst #[(1 : Float)])))
    return ωnull)))])
  if true then return (← pic_0.get)
  return ωnull
ray_impl_static "history" (theory_0 : Theory) (laying_0 : Value) (ticks_0 : Float) (ink_0 : Ink) : (RList Lane) := do
  let w_0 ← IO.mkRef (← app! (← laying_0.get) ((← theory_0.get)))
  let lanes_0 ← IO.mkRef (← ωlst #[(← call! (← cls% Strip) "lane" ((← w_0.get), (← ink_0.get)))])
  for i1 in [0:ωrangeN (← ticks_0.get)] do
    let t_1 ← IO.mkRef (ωnatF i1)
    (← ωget (← w_0.get) "tick") |> ωsink
    (← dot! (← lanes_0.get) rpush ((← call! (← cls% Strip) "lane" ((← w_0.get), (← ink_0.get))))) |> ωsink
    pure ()
  Value.null |> ωsink
  if true then return (← lanes_0.get)
  return ωnull
ray_impl_static "film" (id_0 : String) (what_0 : String) (theory_0 : Theory) (laying_0 : Value) (ticks_0 : Float) (ink_0 : Ink) : Picture := do
  let lanes_0 ← IO.mkRef (← call! (← cls% Strip) "history" ((← theory_0.get), (← laying_0.get), (← ticks_0.get), (← ink_0.get)))
  (ωsetter (← ink_0.get) "centre") (← call! (← cls% Strip) "centre_of" ((← lanes_0.get)))
  let PER_0 ← IO.mkRef (14 : Float)
  let HOLD_0 ← IO.mkRef (3 : Float)
  if true then return (← new! Picture («id» := (← id_0.get), «what» := (← what_0.get), «width» := (900 : Float), «height» := (90 : Float), «frames» := (← ωmul ((← ωadd (← ωadd (← ticks_0.get) (1 : Float)) (← HOLD_0.get))) (← PER_0.get)), «paint» := (fn! [(played_2 : Played)] do
    if true then return (← new! Unrolling («lanes» := (← lanes_0.get), «ink» := (← ink_0.get), «per» := (← PER_0.get)))
    return ωnull)))
  return ωnull
ray_impl_static "tell" (id_0 : String) (what_0 : String) (lanes_0 : (RList Lane)) (ink_0 : Ink) : Picture := do
  (ωsetter (← ink_0.get) "centre") (← call! (← cls% Strip) "centre_of" ((← lanes_0.get)))
  let PER_0 ← IO.mkRef (40 : Float)
  let HOLD_0 ← IO.mkRef (1 : Float)
  if true then return (← new! Picture («id» := (← id_0.get), «what» := (← what_0.get), «width» := (900 : Float), «height» := (110 : Float), «frames» := (← ωmul ((← ωadd (← dot! (← lanes_0.get) rlength ()) (← HOLD_0.get))) (← PER_0.get)), «paint» := (fn! [(played_2 : Played)] do
    if true then return (← new! Unrolling («lanes» := (← lanes_0.get), «ink» := (← ink_0.get), «per» := (← PER_0.get)))
    return ωnull)))
  return ωnull
ray_impl_static "relevant" (pair_0 : (RList Lane)) : object := do
  let rel_0 ← IO.mkRef (← RMap.new)
  for e1 in (← ωitems (← pair_0.get)) do
    let l_1 ← IO.mkRef e1
    for e2 in (← ωitems (← ωget (← l_1.get) "sides")) do
      let sd_2 ← IO.mkRef e2
      (← (ωatSetter (← rel_0.get) ("" ++ (← ωtoStr (← ωget (← sd_2.get) "at")) ++ "" : String)) true) |> ωsink
      (← (ωatSetter (← rel_0.get) ("" ++ (← ωtoStr (← ωadd (← ωget (← sd_2.get) "at") (← ωget (← sd_2.get) "sign"))) ++ "" : String)) true) |> ωsink
      pure ()
    Value.null |> ωsink
    pure ()
  Value.null |> ωsink
  for e1 in (← ωitems (← pair_0.get)) do
    let l_1 ← IO.mkRef e1
    for e2 in (← ωitems (← ωget (← l_1.get) "sources")) do
      let p_2 ← IO.mkRef e2
      (← (ωatSetter (← rel_0.get) ("" ++ (← ωtoStr (← p_2.get)) ++ "" : String)) true) |> ωsink
      pure ()
    Value.null |> ωsink
    pure ()
  Value.null |> ωsink
  let has0_0 ← IO.mkRef (← RMap.new)
  let has1_0 ← IO.mkRef (← RMap.new)
  for e1 in (← ωitems (← ωget (← ωelem (← pair_0.get) (0 : Float)) "points")) do
    let p_1 ← IO.mkRef e1
    (← (ωatSetter (← has0_0.get) ("" ++ (← ωtoStr (← p_1.get)) ++ "" : String)) true) |> ωsink
    pure ()
  Value.null |> ωsink
  for e1 in (← ωitems (← ωget (← ωelem (← pair_0.get) (1 : Float)) "points")) do
    let p_1 ← IO.mkRef e1
    (← (ωatSetter (← has1_0.get) ("" ++ (← ωtoStr (← p_1.get)) ++ "" : String)) true) |> ωsink
    pure ()
  Value.null |> ωsink
  for e1 in (← ωitems (← ωget (← ωelem (← pair_0.get) (0 : Float)) "points")) do
    let p_1 ← IO.mkRef e1
    if ωtruthy (ωisNull (← ωelem (← has1_0.get) ("" ++ (← ωtoStr (← p_1.get)) ++ "" : String))) then
      (← (ωatSetter (← rel_0.get) ("" ++ (← ωtoStr (← p_1.get)) ++ "" : String)) true) |> ωsink
      pure ()
    pure ()
  Value.null |> ωsink
  for e1 in (← ωitems (← ωget (← ωelem (← pair_0.get) (1 : Float)) "points")) do
    let p_1 ← IO.mkRef e1
    if ωtruthy (ωisNull (← ωelem (← has0_0.get) ("" ++ (← ωtoStr (← p_1.get)) ++ "" : String))) then
      (← (ωatSetter (← rel_0.get) ("" ++ (← ωtoStr (← p_1.get)) ++ "" : String)) true) |> ωsink
      pure ()
    pure ()
  Value.null |> ωsink
  if true then return (← rel_0.get)
  return ωnull
ray_impl_static "centre_of" (lanes_0 : (RList Lane)) : Float := do
  let xs_0 ← IO.mkRef (← ωlst #[])
  for e1 in (← ωitems (← lanes_0.get)) do
    let l_1 ← IO.mkRef e1
    for e2 in (← ωitems (← ωget (← l_1.get) "sources")) do
      let p_2 ← IO.mkRef e2
      (← dot! (← xs_0.get) rpush ((← p_2.get))) |> ωsink
      pure ()
    Value.null |> ωsink
    pure ()
  Value.null |> ωsink
  if ωtruthy (← dot! (← xs_0.get) rempty ()) then
    (← ωwr xs_0 (← ωget (← dot! (← lanes_0.get) rfirst ()) "points")) |> ωsink
    pure ()
  if ωtruthy (← dot! (← xs_0.get) rempty ()) then
    if true then return (0 : Float)
    pure ()
  if true then return (← ωdiv ((← ωadd (← dot! (← xs_0.get) rreduce ((← dot! (← xs_0.get) rfirst ()), (fn! [a__2 b__2] do
    if true then return (← call! (← cls% Fmt) "min" ((← a__2.get), (← b__2.get)))
    return ωnull))) (← dot! (← xs_0.get) rreduce ((← dot! (← xs_0.get) rfirst ()), (fn! [a__2 b__2] do
    if true then return (← call! (← cls% Fmt) "max" ((← a__2.get), (← b__2.get)))
    return ωnull))))) (2 : Float))
  return ωnull
ray_impl_static "paint" (s_0 : Surface) (rows_0 : (RList (RList Lane))) (ink_0 : Ink) (lanes_0 : (RList Float)) : Value := do
  let width_0 ← IO.mkRef (← ωget (← s_0.get) "width")
  let H_0 ← IO.mkRef (← ωget (← s_0.get) "height")
  (← call! (← s_0.get) "clear_rect" ((0 : Float), (0 : Float), (← width_0.get), (← H_0.get))) |> ωsink
  (← call! (← s_0.get) "fill_style" ((← ωget (← cls% Ink) "BACK"))) |> ωsink
  (← call! (← s_0.get) "fill_rect" ((0 : Float), (0 : Float), (← width_0.get), (← H_0.get))) |> ωsink
  if ωtruthy (← dot! (← rows_0.get) rempty ()) then
    if true then return ωnull
    pure ()
  let seen_0 ← IO.mkRef false
  let lo_0 ← IO.mkRef (0 : Float)
  let hi_0 ← IO.mkRef (0 : Float)
  for e1 in (← ωitems (← rows_0.get)) do
    let pair_1 ← IO.mkRef e1
    for e2 in (← ωitems (← pair_1.get)) do
      let l_2 ← IO.mkRef e2
      for e3 in (← ωitems (← ωget (← l_2.get) "sides")) do
        let sd_3 ← IO.mkRef e3
        let to_3 ← IO.mkRef (← ωadd (← ωget (← sd_3.get) "at") (← ωget (← sd_3.get) "sign"))
        if !ωtruthy (← seen_0.get) then
          (← ωwr lo_0 (← ωget (← sd_3.get) "at")) |> ωsink
          (← ωwr hi_0 (← ωget (← sd_3.get) "at")) |> ωsink
          (← ωwr seen_0 true) |> ωsink
          pure ()
        (← ωwr lo_0 (← call! (← cls% Fmt) "min" ((← lo_0.get), (← call! (← cls% Fmt) "min" ((← ωget (← sd_3.get) "at"), (← to_3.get)))))) |> ωsink
        (← ωwr hi_0 (← call! (← cls% Fmt) "max" ((← hi_0.get), (← call! (← cls% Fmt) "max" ((← ωget (← sd_3.get) "at"), (← to_3.get)))))) |> ωsink
        pure ()
      Value.null |> ωsink
      pure ()
    Value.null |> ωsink
    pure ()
  Value.null |> ωsink
  for e1 in (← ωitems (← rows_0.get)) do
    let pair_1 ← IO.mkRef e1
    for e2 in (← ωitems (← pair_1.get)) do
      let l_2 ← IO.mkRef e2
      for e3 in (← ωitems (← ωget (← l_2.get) "sources")) do
        let p_3 ← IO.mkRef e3
        if !ωtruthy (← seen_0.get) then
          (← ωwr lo_0 (← p_3.get)) |> ωsink
          (← ωwr hi_0 (← p_3.get)) |> ωsink
          (← ωwr seen_0 true) |> ωsink
          pure ()
        (← ωwr lo_0 (← call! (← cls% Fmt) "min" ((← lo_0.get), (← ωsub (← p_3.get) (1 : Float))))) |> ωsink
        (← ωwr hi_0 (← call! (← cls% Fmt) "max" ((← hi_0.get), (← ωadd (← p_3.get) (1 : Float))))) |> ωsink
        pure ()
      Value.null |> ωsink
      pure ()
    Value.null |> ωsink
    pure ()
  Value.null |> ωsink
  if !ωtruthy (← ωget (← ink_0.get) "every") then
    for e1 in (← ωitems (← rows_0.get)) do
      let pair_1 ← IO.mkRef e1
      let rel_1 ← IO.mkRef (← call! (← cls% Strip) "relevant" ((← pair_1.get)))
      for e2 in (← ωitems (← pair_1.get)) do
        let l_2 ← IO.mkRef e2
        for e3 in (← ωitems (← ωget (← l_2.get) "points")) do
          let p_3 ← IO.mkRef e3
          if ωtruthy (!ωisNull (← ωelem (← rel_1.get) ("" ++ (← ωtoStr (← p_3.get)) ++ "" : String))) then
            if !ωtruthy (← seen_0.get) then
              (← ωwr lo_0 (← p_3.get)) |> ωsink
              (← ωwr hi_0 (← p_3.get)) |> ωsink
              (← ωwr seen_0 true) |> ωsink
              pure ()
            (← ωwr lo_0 (← call! (← cls% Fmt) "min" ((← lo_0.get), (← p_3.get)))) |> ωsink
            (← ωwr hi_0 (← call! (← cls% Fmt) "max" ((← hi_0.get), (← p_3.get)))) |> ωsink
            pure ()
          pure ()
        Value.null |> ωsink
        pure ()
      Value.null |> ωsink
      pure ()
    Value.null |> ωsink
    pure ()
  if !ωtruthy (← seen_0.get) then
    (← ωwr lo_0 (← ωsub (0 : Float) (1 : Float))) |> ωsink
    (← ωwr hi_0 (0 : Float)) |> ωsink
    pure ()
  let EXT_0 ← IO.mkRef (← ωadd (← ωdiv ((← ωsub (← hi_0.get) (← lo_0.get))) (2 : Float)) 0.4)
  if ωtruthy (!ωisNull (← ωget (← ink_0.get) "centre")) then
    (← ωwr EXT_0 (← ωadd (← call! (← cls% Fmt) "max" ((← ωsub (← ωget (← ink_0.get) "centre") (← lo_0.get)), (← ωsub (← hi_0.get) (← ωget (← ink_0.get) "centre")))) 0.4)) |> ωsink
    pure ()
  let HEAD_0 ← IO.mkRef (← ωget (← ink_0.get) "top")
  let PAD_0 ← IO.mkRef (← ωget (← cls% Strip) "PAD")
  let MID_0 ← IO.mkRef (← ωget (← cls% Strip) "MID")
  let lanew_0 ← IO.mkRef (← ωdiv ((← ωsub (← ωsub (← width_0.get) (← ωmul (2 : Float) (← PAD_0.get))) (← ωmul (← MID_0.get) ((← ωsub (← dot! (← lanes_0.get) rlength ()) (1 : Float)))))) (← dot! (← lanes_0.get) rlength ()))
  let origin_0 ← IO.mkRef ωnull
  origin_0.set (fn! [(k_ : Float)] do
      if true then return (← ωadd (← PAD_0.get) (← ωmul k_ ((← ωadd (← lanew_0.get) (← MID_0.get)))))
      return ωnull)
  let rowH_0 ← IO.mkRef (← ωdiv ((← ωsub (← H_0.get) (← HEAD_0.get))) (← dot! (← rows_0.get) rlength ()))
  let CELL_0 ← IO.mkRef (← ωdiv (← lanew_0.get) ((← ωadd (← ωmul (2 : Float) (← EXT_0.get)) (1 : Float))))
  let MID_AT_0 ← IO.mkRef (0 : Float)
  let X_0 ← IO.mkRef ωnull
  X_0.set (fn! [(k_ : Float) (x : Float)] do
      if true then return (← ωadd (← ωadd (← app! (← origin_0.get) (k_)) (← ωdiv (← lanew_0.get) (2 : Float))) (← ωmul ((← ωsub x (← MID_AT_0.get))) (← CELL_0.get)))
      return ωnull)
  for i1 in [0:ωrangeN (← dot! (← rows_0.get) rlength ())] do
    let r_1 ← IO.mkRef (ωnatF i1)
    let pair_1 ← IO.mkRef (← ωelem (← rows_0.get) (← r_1.get))
    let y_1 ← IO.mkRef (← ωadd (← HEAD_0.get) (← ωmul (← rowH_0.get) ((← ωadd (← r_1.get) 0.5))))
    let rel_1 ← IO.mkRef (← call! (← cls% Strip) "relevant" ((← pair_1.get)))
    for i2 in [0:ωrangeN (← dot! (← lanes_0.get) rlength ())] do
      let k__2 ← IO.mkRef (ωnatF i2)
      let fi_2 ← IO.mkRef (← ωelem (← lanes_0.get) (← k__2.get))
      let l_2 ← IO.mkRef (← ωelem (← pair_1.get) (← fi_2.get))
      let ox_2 ← IO.mkRef (← app! (← origin_0.get) ((← k__2.get)))
      if ωtruthy (!ωisNull (← ωget (← ink_0.get) "centre")) then
        (← ωwr MID_AT_0 (← ωget (← ink_0.get) "centre")) |> ωsink
        pure ()
      else
        let xs_2 ← IO.mkRef (← ωlst #[])
        for e3 in (← ωitems (← ωget (← l_2.get) "sides")) do
          let sd_3 ← IO.mkRef e3
          (← dot! (← xs_2.get) rpush ((← ωsub (← ωget (← sd_3.get) "at") 0.25))) |> ωsink
          (← dot! (← xs_2.get) rpush ((← ωadd (← ωget (← sd_3.get) "at") 0.25))) |> ωsink
          pure ()
        Value.null |> ωsink
        for e3 in (← ωitems (← ωget (← l_2.get) "sources")) do
          let p_3 ← IO.mkRef e3
          (← dot! (← xs_2.get) rpush ((← ωsub (← p_3.get) 0.3))) |> ωsink
          (← dot! (← xs_2.get) rpush ((← ωadd (← p_3.get) 0.3))) |> ωsink
          pure ()
        Value.null |> ωsink
        for e3 in (← ωitems (← ωget (← l_2.get) "points")) do
          let p_3 ← IO.mkRef e3
          if ωtruthy (← ωorV (← ωget (← ink_0.get) "every") (do pure (!ωisNull (← ωelem (← rel_1.get) ("" ++ (← ωtoStr (← p_3.get)) ++ "" : String))))) then
            (← dot! (← xs_2.get) rpush ((← p_3.get))) |> ωsink
            pure ()
          pure ()
        Value.null |> ωsink
        (← ωwr MID_AT_0 (← ωtern (ωtruthy (← dot! (← xs_2.get) rempty ())) (do pure (← ωdiv ((← ωadd (← lo_0.get) (← hi_0.get))) (2 : Float))) (do pure (← ωdiv ((← ωadd (← dot! (← xs_2.get) rreduce ((← dot! (← xs_2.get) rfirst ()), (fn! [a__4 b__4] do
          if true then return (← call! (← cls% Fmt) "min" ((← a__4.get), (← b__4.get)))
          return ωnull))) (← dot! (← xs_2.get) rreduce ((← dot! (← xs_2.get) rfirst ()), (fn! [a__4 b__4] do
          if true then return (← call! (← cls% Fmt) "max" ((← a__4.get), (← b__4.get)))
          return ωnull))))) (2 : Float))))) |> ωsink
        pure ()
      (← call! (← s_0.get) "stroke_style" (("rgba(" ++ (← ωtoStr (← ωget (← cls% Ink) "NEUTRAL")) ++ "," ++ (← ωtoStr (← ωget (← ink_0.get) "line")) ++ ")" : String))) |> ωsink
      (← call! (← s_0.get) "line_width" ((1 : Float))) |> ωsink
      (← ωget (← s_0.get) "begin_path") |> ωsink
      (← call! (← s_0.get) "move_to" ((← ox_2.get), (← y_1.get))) |> ωsink
      (← call! (← s_0.get) "line_to" ((← ωadd (← ox_2.get) (← lanew_0.get)), (← y_1.get))) |> ωsink
      (← ωget (← s_0.get) "stroke") |> ωsink
      for e3 in (← ωitems (← ωget (← l_2.get) "points")) do
        let p_3 ← IO.mkRef e3
        if ωtruthy (← ωorV (← ωget (← ink_0.get) "every") (do pure (!ωisNull (← ωelem (← rel_1.get) ("" ++ (← ωtoStr (← p_3.get)) ++ "" : String))))) then
          (← call! (← s_0.get) "fill_style" (("rgba(" ++ (← ωtoStr (← ωget (← cls% Ink) "NEUTRAL")) ++ "," ++ (← ωtoStr (← ωget (← ink_0.get) "dot")) ++ ")" : String))) |> ωsink
          (← ωget (← s_0.get) "begin_path") |> ωsink
          (← call! (← s_0.get) "arc" ((← app! (← X_0.get) ((← k__2.get), (← p_3.get))), (← y_1.get), 2.6, (0 : Float), (← ωmul (2 : Float) (3.141592653589793 : Float)))) |> ωsink
          (← ωget (← s_0.get) "fill") |> ωsink
          pure ()
        pure ()
      Value.null |> ωsink
      for e3 in (← ωitems (← ωget (← l_2.get) "sources")) do
        let p_3 ← IO.mkRef e3
        let half_3 ← IO.mkRef (← call! (← cls% Fmt) "max" ((9 : Float), (← call! (← cls% Fmt) "min" ((18 : Float), (← ωmul (← CELL_0.get) 0.3)))))
        let sx_3 ← IO.mkRef (← app! (← X_0.get) ((← k__2.get), (← p_3.get)))
        (← call! (← s_0.get) "fill_style" (("rgba(" ++ (← ωtoStr (← ωget (← cls% Ink) "SOURCE")) ++ ",0.14)" : String))) |> ωsink
        (← call! (← s_0.get) "fill_rect" ((← ωsub (← sx_3.get) (← half_3.get)), (← ωsub (← y_1.get) (← half_3.get)), (← ωmul (2 : Float) (← half_3.get)), (← ωmul (2 : Float) (← half_3.get)))) |> ωsink
        (← call! (← s_0.get) "stroke_style" (("rgba(" ++ (← ωtoStr (← ωget (← cls% Ink) "SOURCE")) ++ ",0.9)" : String))) |> ωsink
        (← call! (← s_0.get) "line_width" (1.5)) |> ωsink
        (← call! (← s_0.get) "stroke_rect" ((← ωsub (← sx_3.get) (← half_3.get)), (← ωsub (← y_1.get) (← half_3.get)), (← ωmul (2 : Float) (← half_3.get)), (← ωmul (2 : Float) (← half_3.get)))) |> ωsink
        if !ωtruthy (← dot! (← ωget (← l_2.get) "says") rempty ()) then
          (← call! (← s_0.get) "stroke_style" (("rgba(" ++ (← ωtoStr (← ωget (← cls% Ink) "SOURCE")) ++ ",0.9)" : String))) |> ωsink
          (← call! (← s_0.get) "line_width" ((1 : Float))) |> ωsink
          (← ωget (← s_0.get) "begin_path") |> ωsink
          (← call! (← s_0.get) "move_to" ((← sx_3.get), (← ωsub (← y_1.get) (← half_3.get)))) |> ωsink
          (← call! (← s_0.get) "line_to" ((← sx_3.get), (← ωsub (← ωsub (← y_1.get) (← half_3.get)) (16 : Float)))) |> ωsink
          (← ωget (← s_0.get) "stroke") |> ωsink
          (← call! (← s_0.get) "fill_style" (("rgba(" ++ (← ωtoStr (← ωget (← cls% Ink) "SOURCE")) ++ ",1)" : String))) |> ωsink
          (← call! (← s_0.get) "font" (("13px ui-monospace, monospace" : String))) |> ωsink
          (← call! (← s_0.get) "text_align" (("center" : String))) |> ωsink
          (← call! (← s_0.get) "text_baseline" (("bottom" : String))) |> ωsink
          (← call! (← s_0.get) "fill_text" ((← ωget (← l_2.get) "says"), (← sx_3.get), (← ωsub (← ωsub (← y_1.get) (← half_3.get)) (20 : Float)))) |> ωsink
          pure ()
        pure ()
      Value.null |> ωsink
      let HEADW_2 ← IO.mkRef (← call! (← cls% Fmt) "max" ((7 : Float), (← call! (← cls% Fmt) "min" ((12 : Float), (← ωmul (← CELL_0.get) 0.20)))))
      let REACH_2 ← IO.mkRef (← ωmul (← CELL_0.get) 0.25)
      let BAR_2 ← IO.mkRef (← call! (← cls% Fmt) "max" (2.5, (← call! (← cls% Fmt) "min" (4.5, (← ωmul (← CELL_0.get) 0.075)))))
      let BASE_2 ← IO.mkRef (← ωmul (← HEADW_2.get) 0.45)
      let TIP_2 ← IO.mkRef (← ωmul (← HEADW_2.get) 0.55)
      let LEN_2 ← IO.mkRef (← ωsub (← REACH_2.get) (← BASE_2.get))
      let SEEN_2 ← IO.mkRef (← ωsub (← TIP_2.get) (← ωdiv (← BAR_2.get) 0.84))
      for e3 in (← ωitems (← ωget (← l_2.get) "sides")) do
        let sd_3 ← IO.mkRef e3
        let px_3 ← IO.mkRef (← app! (← X_0.get) ((← k__2.get), (← ωget (← sd_3.get) "at")))
        (← call! (← s_0.get) "stroke_style" (("rgba(" ++ (← ωtoStr (← ωget (← sd_3.get) "ink")) ++ "," ++ (← ωtoStr (← ωget (← ink_0.get) "behind")) ++ ")" : String))) |> ωsink
        (← call! (← s_0.get) "line_width" ((← BAR_2.get))) |> ωsink
        (← ωget (← s_0.get) "begin_path") |> ωsink
        (← call! (← s_0.get) "move_to" ((← ωsub (← px_3.get) (← ωmul (← ωget (← sd_3.get) "sign") ((← ωadd (← BASE_2.get) (← LEN_2.get))))), (← y_1.get))) |> ωsink
        (← call! (← s_0.get) "line_to" ((← ωsub (← px_3.get) (← ωmul (← ωget (← sd_3.get) "sign") (← BASE_2.get))), (← y_1.get))) |> ωsink
        (← ωget (← s_0.get) "stroke") |> ωsink
        (← call! (← s_0.get) "stroke_style" (("rgba(" ++ (← ωtoStr (← ωget (← sd_3.get) "ink")) ++ "," ++ (← ωtoStr (← ωget (← ink_0.get) "front")) ++ ")" : String))) |> ωsink
        (← ωget (← s_0.get) "begin_path") |> ωsink
        (← call! (← s_0.get) "move_to" ((← px_3.get), (← y_1.get))) |> ωsink
        (← call! (← s_0.get) "line_to" ((← ωadd (← px_3.get) (← ωmul (← ωget (← sd_3.get) "sign") ((← ωadd (← SEEN_2.get) (← LEN_2.get))))), (← y_1.get))) |> ωsink
        (← ωget (← s_0.get) "stroke") |> ωsink
        pure ()
      Value.null |> ωsink
      for e3 in (← ωitems (← ωget (← l_2.get) "sides")) do
        let sd_3 ← IO.mkRef e3
        let px_3 ← IO.mkRef (← app! (← X_0.get) ((← k__2.get), (← ωget (← sd_3.get) "at")))
        (← call! (← s_0.get) "fill_style" (("rgba(" ++ (← ωtoStr (← ωget (← sd_3.get) "ink")) ++ "," ++ (← ωtoStr (← ωget (← ink_0.get) "head")) ++ ")" : String))) |> ωsink
        (← ωget (← s_0.get) "begin_path") |> ωsink
        (← call! (← s_0.get) "move_to" ((← ωadd (← px_3.get) (← ωmul (← ωget (← sd_3.get) "sign") (← TIP_2.get))), (← y_1.get))) |> ωsink
        (← call! (← s_0.get) "line_to" ((← ωsub (← px_3.get) (← ωmul (← ωget (← sd_3.get) "sign") (← BASE_2.get))), (← ωsub (← y_1.get) (← ωmul (← HEADW_2.get) 0.42)))) |> ωsink
        (← call! (← s_0.get) "line_to" ((← ωsub (← px_3.get) (← ωmul (← ωget (← sd_3.get) "sign") (← BASE_2.get))), (← ωadd (← y_1.get) (← ωmul (← HEADW_2.get) 0.42)))) |> ωsink
        (← ωget (← s_0.get) "fill") |> ωsink
        pure ()
      Value.null |> ωsink
      pure ()
    Value.null |> ωsink
    pure ()
  Value.null |> ωsink
  return ωnull
end Strip



end OrbitMines.Physics
