-- GENERATED by `npx ray gen` from implementation/physics.ray - do not edit
import OrbitMines.Physics.Globals
set_option linter.unusedVariables false
set_option autoImplicit false
set_option maxHeartbeats 0
set_option maxRecDepth 100000
namespace OrbitMines.Physics


namespace Painter
ray_impl_getter "start" : Value := do

  return ωnull
ray_impl_method "frame" (s_0 : Surface) (dt_0 : Float) : Value := do

  return ωnull
ray_impl_method "warm" (budget_0 : Float) : Float := do
  if true then return (1 : Float)
  return ωnull
end Painter



end OrbitMines.Physics
