-- GENERATED by `npx ray gen` from implementation/physics.ray - do not edit
import OrbitMines.Physics.Globals
set_option linter.unusedVariables false
set_option autoImplicit false
set_option maxHeartbeats 0
set_option maxRecDepth 100000
namespace OrbitMines.Physics


namespace Forming
ray_impl_field "formed" : Measured := do
  return ωnull
ray_impl_field "shown_frames" : Float := do
  return (0 : Float)
ray_impl_method "frame" (s_0 : Surface) (dt_0 : Float) : Value := do
  (← call! (← cls% Galaxies) "formed_panel" ((← s_0.get), (← ωget self "formed"), (← ωget self "shown_frames"))) |> ωsink
  (ωsetter self "shown_frames") (← ωadd (← ωget self "shown_frames") (1 : Float))
  return ωnull
end Forming



end OrbitMines.Physics
