-- GENERATED by `npx ray gen` from implementation/physics.ray - do not edit
import OrbitMines.Physics.Runtime
set_option linter.unusedVariables false
set_option maxHeartbeats 0
set_option maxRecDepth 100000
open Rt


namespace C_Args
def thisClass : String := "Args"
initialize defineClass thisClass "Node"
initialize fieldNone thisClass "got"
initialize fieldNone thisClass "end"
end C_Args


