-- GENERATED by `npx ray gen` from implementation/physics.ray - do not edit
import OrbitMines.Physics.Globals
set_option linter.unusedVariables false
set_option autoImplicit false
set_option maxHeartbeats 0
set_option maxRecDepth 100000
namespace OrbitMines.Physics


namespace Braced
ray_impl_field "body" : String := do
  return ωnull
ray_impl_field "end" : Float := do
  return ωnull
end Braced



end OrbitMines.Physics
