-- GENERATED by `npx ray gen` from implementation/physics.ray - do not edit
import OrbitMines.Physics.Runtime
set_option linter.unusedVariables false
set_option maxHeartbeats 0
set_option maxRecDepth 100000
open Rt


namespace C_Source
def thisClass : String := "Source"
initialize defineClass thisClass "Node"
initialize fieldNone thisClass "world"
initialize field thisClass "cells" (fun self => do
  return (← lst #[]))
initialize fieldNone thisClass "at"
initialize field thisClass "half" (fun self => do
  return Value.null)
initialize field thisClass "radius" (fun self => do
  return (Value.num 0))
initialize field thisClass "moves" (fun self => do
  return (Value.bool false))
initialize fieldNone thisClass "momentum"
initialize fieldNone thisClass "advance"
initialize field thisClass "stepped" (fun self => do
  return (Value.bool false))
initialize field thisClass "moved_along" (fun self => do
  return Value.null)
initialize getter thisClass "spare" (fun self a1 => do
  if true then return (← notV (← gm self "stepped"))
  return Value.null)
initialize getter thisClass "mass" (fun self a1 => do
  if true then return (← inv (← choose self "mass") #[])
  return Value.null)
initialize field thisClass "absorbs" (fun self => do
  return (Value.bool true))
initialize method thisClass "choose emit?" (fun self a0 => throwMsg "the choice emit? is not defined by anyone")
initialize method thisClass "choose mass" (fun self a0 => throwMsg "the choice mass is not defined by anyone")
initialize method thisClass "emits" (fun self a1 => do
  let exit_0 ← IO.mkRef (arg a1 0)
  if true then return (← andV (← inv (← choose self "emit?") #[(← exit_0.get)]) (do pure (← neV (← gm self "moved_along") (← exit_0.get))))
  return Value.null)
initialize method thisClass "ahead" (fun self a1 => do
  let d_0 ← IO.mkRef (arg a1 0)
  if true then return (← m_map (← gm self "cells") #[(mkFn (fun a3 => do
    let c_2 ← IO.mkRef (arg a3 0)
    if true then return (← cm (← c_2.get) "outward" #[(← d_0.get)])
    return Value.null))])
  return Value.null)
end C_Source


