-- GENERATED by `npx ray gen` from implementation/physics.ray - do not edit
import OrbitMines.Physics.Runtime
set_option linter.unusedVariables false
set_option maxHeartbeats 0
set_option maxRecDepth 100000
open Rt


namespace C_Grid
def thisClass : String := "Grid"
initialize defineClass thisClass "Node"
initialize fieldNone thisClass "L"
initialize fieldNone thisClass "n"
initialize fieldNone thisClass "s"
initialize fieldNone thisClass "rho"
initialize fieldNone thisClass "passes"
initialize fieldNone thisClass "settled"
initialize fieldNone thisClass "imbalance"
end C_Grid


