// swift-tools-version:6.0
// GENERATED by `npx ray gen` from implementation/physics.ray - do not edit
// swift run -c release TestG [filter]
import PackageDescription

let package = Package(
  name: "TestG",
  dependencies: [.package(path: "../../languages/physics.swift")],
  targets: [
    .executableTarget(name: "TestG", dependencies: [.product(name: "OrbitMinesPhysics", package: "physics.swift")], path: "Sources/TestG"),
  ],
  swiftLanguageModes: [.v5]
)
